// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: order/v1/order_shipping_document.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationOrderShippingDocumentServiceAddShippingDocument = "/order.v1.OrderShippingDocumentService/AddShippingDocument"
const OperationOrderShippingDocumentServiceListShippingDocuments = "/order.v1.OrderShippingDocumentService/ListShippingDocuments"
const OperationOrderShippingDocumentServiceRemoveShippingDocument = "/order.v1.OrderShippingDocumentService/RemoveShippingDocument"
const OperationOrderShippingDocumentServiceTransitionShippingDocumentStatus = "/order.v1.OrderShippingDocumentService/TransitionShippingDocumentStatus"
const OperationOrderShippingDocumentServiceUpdateShippingDocument = "/order.v1.OrderShippingDocumentService/UpdateShippingDocument"

type OrderShippingDocumentServiceHTTPServer interface {
	// AddShippingDocument AddShippingDocument 添加订单提单，初始状态为草稿。
	AddShippingDocument(context.Context, *AddShippingDocumentRequest) (*OrderShippingDocumentReply, error)
	// ListShippingDocuments ListShippingDocuments 获取指定订单的提单列表。
	ListShippingDocuments(context.Context, *ListShippingDocumentsRequest) (*OrderShippingDocumentListReply, error)
	// RemoveShippingDocument RemoveShippingDocument 移除提单，已放货的提单不可删除。
	RemoveShippingDocument(context.Context, *RemoveShippingDocumentRequest) (*OrderShippingDocumentOperationReply, error)
	// TransitionShippingDocumentStatus TransitionShippingDocumentStatus 流转提单状态，仅允许向前单步流转。
	TransitionShippingDocumentStatus(context.Context, *TransitionShippingDocumentStatusRequest) (*OrderShippingDocumentReply, error)
	// UpdateShippingDocument UpdateShippingDocument 更新提单字段，草稿与已确认状态可改，已放货后不可改。
	UpdateShippingDocument(context.Context, *UpdateShippingDocumentRequest) (*OrderShippingDocumentReply, error)
}

func RegisterOrderShippingDocumentServiceHTTPServer(s *http.Server, srv OrderShippingDocumentServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/api/v1/orders/{order_id}/shipping-documents", _OrderShippingDocumentService_ListShippingDocuments0_HTTP_Handler(srv))
	r.Handle("POST", "/api/v1/orders/{order_id}/shipping-documents", _OrderShippingDocumentService_AddShippingDocument0_HTTP_Handler(srv))
	r.Handle("PUT", "/api/v1/orders/{order_id}/shipping-documents/{id}", _OrderShippingDocumentService_UpdateShippingDocument0_HTTP_Handler(srv))
	r.Handle("POST", "/api/v1/orders/{order_id}/shipping-documents/{id}/transition", _OrderShippingDocumentService_TransitionShippingDocumentStatus0_HTTP_Handler(srv))
	r.Handle("DELETE", "/api/v1/orders/{order_id}/shipping-documents/{id}", _OrderShippingDocumentService_RemoveShippingDocument0_HTTP_Handler(srv))
}

func _OrderShippingDocumentService_ListShippingDocuments0_HTTP_Handler(srv OrderShippingDocumentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListShippingDocumentsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderShippingDocumentServiceListShippingDocuments)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListShippingDocuments(ctx, req.(*ListShippingDocumentsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OrderShippingDocumentListReply)
		return ctx.Result(200, reply)
	}
}

func _OrderShippingDocumentService_AddShippingDocument0_HTTP_Handler(srv OrderShippingDocumentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddShippingDocumentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderShippingDocumentServiceAddShippingDocument)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddShippingDocument(ctx, req.(*AddShippingDocumentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OrderShippingDocumentReply)
		return ctx.Result(200, reply)
	}
}

func _OrderShippingDocumentService_UpdateShippingDocument0_HTTP_Handler(srv OrderShippingDocumentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateShippingDocumentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderShippingDocumentServiceUpdateShippingDocument)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateShippingDocument(ctx, req.(*UpdateShippingDocumentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OrderShippingDocumentReply)
		return ctx.Result(200, reply)
	}
}

func _OrderShippingDocumentService_TransitionShippingDocumentStatus0_HTTP_Handler(srv OrderShippingDocumentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TransitionShippingDocumentStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderShippingDocumentServiceTransitionShippingDocumentStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.TransitionShippingDocumentStatus(ctx, req.(*TransitionShippingDocumentStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OrderShippingDocumentReply)
		return ctx.Result(200, reply)
	}
}

func _OrderShippingDocumentService_RemoveShippingDocument0_HTTP_Handler(srv OrderShippingDocumentServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RemoveShippingDocumentRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationOrderShippingDocumentServiceRemoveShippingDocument)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RemoveShippingDocument(ctx, req.(*RemoveShippingDocumentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*OrderShippingDocumentOperationReply)
		return ctx.Result(200, reply)
	}
}

type OrderShippingDocumentServiceHTTPClient interface {
	// AddShippingDocument AddShippingDocument 添加订单提单，初始状态为草稿。
	AddShippingDocument(ctx context.Context, req *AddShippingDocumentRequest, opts ...http.CallOption) (rsp *OrderShippingDocumentReply, err error)
	// ListShippingDocuments ListShippingDocuments 获取指定订单的提单列表。
	ListShippingDocuments(ctx context.Context, req *ListShippingDocumentsRequest, opts ...http.CallOption) (rsp *OrderShippingDocumentListReply, err error)
	// RemoveShippingDocument RemoveShippingDocument 移除提单，已放货的提单不可删除。
	RemoveShippingDocument(ctx context.Context, req *RemoveShippingDocumentRequest, opts ...http.CallOption) (rsp *OrderShippingDocumentOperationReply, err error)
	// TransitionShippingDocumentStatus TransitionShippingDocumentStatus 流转提单状态，仅允许向前单步流转。
	TransitionShippingDocumentStatus(ctx context.Context, req *TransitionShippingDocumentStatusRequest, opts ...http.CallOption) (rsp *OrderShippingDocumentReply, err error)
	// UpdateShippingDocument UpdateShippingDocument 更新提单字段，草稿与已确认状态可改，已放货后不可改。
	UpdateShippingDocument(ctx context.Context, req *UpdateShippingDocumentRequest, opts ...http.CallOption) (rsp *OrderShippingDocumentReply, err error)
}

type OrderShippingDocumentServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewOrderShippingDocumentServiceHTTPClient(client *http.Client) OrderShippingDocumentServiceHTTPClient {
	return &OrderShippingDocumentServiceHTTPClientImpl{client}
}

// AddShippingDocument AddShippingDocument 添加订单提单，初始状态为草稿。
func (c *OrderShippingDocumentServiceHTTPClientImpl) AddShippingDocument(ctx context.Context, in *AddShippingDocumentRequest, opts ...http.CallOption) (*OrderShippingDocumentReply, error) {
	var out OrderShippingDocumentReply
	pattern := "/api/v1/orders/{order_id}/shipping-documents"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationOrderShippingDocumentServiceAddShippingDocument),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListShippingDocuments ListShippingDocuments 获取指定订单的提单列表。
func (c *OrderShippingDocumentServiceHTTPClientImpl) ListShippingDocuments(ctx context.Context, in *ListShippingDocumentsRequest, opts ...http.CallOption) (*OrderShippingDocumentListReply, error) {
	var out OrderShippingDocumentListReply
	pattern := "/api/v1/orders/{order_id}/shipping-documents"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationOrderShippingDocumentServiceListShippingDocuments),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RemoveShippingDocument RemoveShippingDocument 移除提单，已放货的提单不可删除。
func (c *OrderShippingDocumentServiceHTTPClientImpl) RemoveShippingDocument(ctx context.Context, in *RemoveShippingDocumentRequest, opts ...http.CallOption) (*OrderShippingDocumentOperationReply, error) {
	var out OrderShippingDocumentOperationReply
	pattern := "/api/v1/orders/{order_id}/shipping-documents/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationOrderShippingDocumentServiceRemoveShippingDocument),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// TransitionShippingDocumentStatus TransitionShippingDocumentStatus 流转提单状态，仅允许向前单步流转。
func (c *OrderShippingDocumentServiceHTTPClientImpl) TransitionShippingDocumentStatus(ctx context.Context, in *TransitionShippingDocumentStatusRequest, opts ...http.CallOption) (*OrderShippingDocumentReply, error) {
	var out OrderShippingDocumentReply
	pattern := "/api/v1/orders/{order_id}/shipping-documents/{id}/transition"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationOrderShippingDocumentServiceTransitionShippingDocumentStatus),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateShippingDocument UpdateShippingDocument 更新提单字段，草稿与已确认状态可改，已放货后不可改。
func (c *OrderShippingDocumentServiceHTTPClientImpl) UpdateShippingDocument(ctx context.Context, in *UpdateShippingDocumentRequest, opts ...http.CallOption) (*OrderShippingDocumentReply, error) {
	var out OrderShippingDocumentReply
	pattern := "/api/v1/orders/{order_id}/shipping-documents/{id}"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationOrderShippingDocumentServiceUpdateShippingDocument),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
