// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: order/v1/sea_cargo_allocation.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SeaCargoAllocationService_GetSeaCargoAllocation_FullMethodName                 = "/order.v1.SeaCargoAllocationService/GetSeaCargoAllocation"
	SeaCargoAllocationService_SaveSeaCargoAllocationDraft_FullMethodName           = "/order.v1.SeaCargoAllocationService/SaveSeaCargoAllocationDraft"
	SeaCargoAllocationService_ConfirmSeaCargoAllocation_FullMethodName             = "/order.v1.SeaCargoAllocationService/ConfirmSeaCargoAllocation"
	SeaCargoAllocationService_WithdrawSeaCargoAllocation_FullMethodName            = "/order.v1.SeaCargoAllocationService/WithdrawSeaCargoAllocation"
	SeaCargoAllocationService_ApplySeaOrderCargoSummaryToMasterBill_FullMethodName = "/order.v1.SeaCargoAllocationService/ApplySeaOrderCargoSummaryToMasterBill"
	SeaCargoAllocationService_ApplySeaHouseBillAllocationSummary_FullMethodName    = "/order.v1.SeaCargoAllocationService/ApplySeaHouseBillAllocationSummary"
)

// SeaCargoAllocationServiceClient is the client API for SeaCargoAllocationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SeaCargoAllocationService 海运出口箱货定量分配服务。
type SeaCargoAllocationServiceClient interface {
	// GetSeaCargoAllocation 获取海运箱货分配聚合信息。
	GetSeaCargoAllocation(ctx context.Context, in *GetSeaCargoAllocationRequest, opts ...grpc.CallOption) (*GetSeaCargoAllocationResponse, error)
	// SaveSeaCargoAllocationDraft 全量替换保存箱货分配草稿。
	SaveSeaCargoAllocationDraft(ctx context.Context, in *SaveSeaCargoAllocationDraftRequest, opts ...grpc.CallOption) (*SaveSeaCargoAllocationDraftResponse, error)
	// ConfirmSeaCargoAllocation 确认海运箱货分配（严格守恒门禁）。
	ConfirmSeaCargoAllocation(ctx context.Context, in *ConfirmSeaCargoAllocationRequest, opts ...grpc.CallOption) (*ConfirmSeaCargoAllocationResponse, error)
	// WithdrawSeaCargoAllocation 撤回海运箱货分配确认。
	WithdrawSeaCargoAllocation(ctx context.Context, in *WithdrawSeaCargoAllocationRequest, opts ...grpc.CallOption) (*WithdrawSeaCargoAllocationResponse, error)
	// ApplySeaOrderCargoSummaryToMasterBill DIRECT 下用操作票货物汇总填入 MBL 提单内容。
	ApplySeaOrderCargoSummaryToMasterBill(ctx context.Context, in *ApplySeaOrderCargoSummaryToMasterBillRequest, opts ...grpc.CallOption) (*ApplySeaOrderCargoSummaryToMasterBillResponse, error)
	// ApplySeaHouseBillAllocationSummary HOUSE 下用分配汇总填入目标 HBL 提单内容。
	ApplySeaHouseBillAllocationSummary(ctx context.Context, in *ApplySeaHouseBillAllocationSummaryRequest, opts ...grpc.CallOption) (*ApplySeaHouseBillAllocationSummaryResponse, error)
}

type seaCargoAllocationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSeaCargoAllocationServiceClient(cc grpc.ClientConnInterface) SeaCargoAllocationServiceClient {
	return &seaCargoAllocationServiceClient{cc}
}

func (c *seaCargoAllocationServiceClient) GetSeaCargoAllocation(ctx context.Context, in *GetSeaCargoAllocationRequest, opts ...grpc.CallOption) (*GetSeaCargoAllocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSeaCargoAllocationResponse)
	err := c.cc.Invoke(ctx, SeaCargoAllocationService_GetSeaCargoAllocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seaCargoAllocationServiceClient) SaveSeaCargoAllocationDraft(ctx context.Context, in *SaveSeaCargoAllocationDraftRequest, opts ...grpc.CallOption) (*SaveSeaCargoAllocationDraftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveSeaCargoAllocationDraftResponse)
	err := c.cc.Invoke(ctx, SeaCargoAllocationService_SaveSeaCargoAllocationDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seaCargoAllocationServiceClient) ConfirmSeaCargoAllocation(ctx context.Context, in *ConfirmSeaCargoAllocationRequest, opts ...grpc.CallOption) (*ConfirmSeaCargoAllocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmSeaCargoAllocationResponse)
	err := c.cc.Invoke(ctx, SeaCargoAllocationService_ConfirmSeaCargoAllocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seaCargoAllocationServiceClient) WithdrawSeaCargoAllocation(ctx context.Context, in *WithdrawSeaCargoAllocationRequest, opts ...grpc.CallOption) (*WithdrawSeaCargoAllocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WithdrawSeaCargoAllocationResponse)
	err := c.cc.Invoke(ctx, SeaCargoAllocationService_WithdrawSeaCargoAllocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seaCargoAllocationServiceClient) ApplySeaOrderCargoSummaryToMasterBill(ctx context.Context, in *ApplySeaOrderCargoSummaryToMasterBillRequest, opts ...grpc.CallOption) (*ApplySeaOrderCargoSummaryToMasterBillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplySeaOrderCargoSummaryToMasterBillResponse)
	err := c.cc.Invoke(ctx, SeaCargoAllocationService_ApplySeaOrderCargoSummaryToMasterBill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seaCargoAllocationServiceClient) ApplySeaHouseBillAllocationSummary(ctx context.Context, in *ApplySeaHouseBillAllocationSummaryRequest, opts ...grpc.CallOption) (*ApplySeaHouseBillAllocationSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplySeaHouseBillAllocationSummaryResponse)
	err := c.cc.Invoke(ctx, SeaCargoAllocationService_ApplySeaHouseBillAllocationSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SeaCargoAllocationServiceServer is the server API for SeaCargoAllocationService service.
// All implementations must embed UnimplementedSeaCargoAllocationServiceServer
// for forward compatibility.
//
// SeaCargoAllocationService 海运出口箱货定量分配服务。
type SeaCargoAllocationServiceServer interface {
	// GetSeaCargoAllocation 获取海运箱货分配聚合信息。
	GetSeaCargoAllocation(context.Context, *GetSeaCargoAllocationRequest) (*GetSeaCargoAllocationResponse, error)
	// SaveSeaCargoAllocationDraft 全量替换保存箱货分配草稿。
	SaveSeaCargoAllocationDraft(context.Context, *SaveSeaCargoAllocationDraftRequest) (*SaveSeaCargoAllocationDraftResponse, error)
	// ConfirmSeaCargoAllocation 确认海运箱货分配（严格守恒门禁）。
	ConfirmSeaCargoAllocation(context.Context, *ConfirmSeaCargoAllocationRequest) (*ConfirmSeaCargoAllocationResponse, error)
	// WithdrawSeaCargoAllocation 撤回海运箱货分配确认。
	WithdrawSeaCargoAllocation(context.Context, *WithdrawSeaCargoAllocationRequest) (*WithdrawSeaCargoAllocationResponse, error)
	// ApplySeaOrderCargoSummaryToMasterBill DIRECT 下用操作票货物汇总填入 MBL 提单内容。
	ApplySeaOrderCargoSummaryToMasterBill(context.Context, *ApplySeaOrderCargoSummaryToMasterBillRequest) (*ApplySeaOrderCargoSummaryToMasterBillResponse, error)
	// ApplySeaHouseBillAllocationSummary HOUSE 下用分配汇总填入目标 HBL 提单内容。
	ApplySeaHouseBillAllocationSummary(context.Context, *ApplySeaHouseBillAllocationSummaryRequest) (*ApplySeaHouseBillAllocationSummaryResponse, error)
	mustEmbedUnimplementedSeaCargoAllocationServiceServer()
}

// UnimplementedSeaCargoAllocationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSeaCargoAllocationServiceServer struct{}

func (UnimplementedSeaCargoAllocationServiceServer) GetSeaCargoAllocation(context.Context, *GetSeaCargoAllocationRequest) (*GetSeaCargoAllocationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSeaCargoAllocation not implemented")
}
func (UnimplementedSeaCargoAllocationServiceServer) SaveSeaCargoAllocationDraft(context.Context, *SaveSeaCargoAllocationDraftRequest) (*SaveSeaCargoAllocationDraftResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveSeaCargoAllocationDraft not implemented")
}
func (UnimplementedSeaCargoAllocationServiceServer) ConfirmSeaCargoAllocation(context.Context, *ConfirmSeaCargoAllocationRequest) (*ConfirmSeaCargoAllocationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmSeaCargoAllocation not implemented")
}
func (UnimplementedSeaCargoAllocationServiceServer) WithdrawSeaCargoAllocation(context.Context, *WithdrawSeaCargoAllocationRequest) (*WithdrawSeaCargoAllocationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WithdrawSeaCargoAllocation not implemented")
}
func (UnimplementedSeaCargoAllocationServiceServer) ApplySeaOrderCargoSummaryToMasterBill(context.Context, *ApplySeaOrderCargoSummaryToMasterBillRequest) (*ApplySeaOrderCargoSummaryToMasterBillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplySeaOrderCargoSummaryToMasterBill not implemented")
}
func (UnimplementedSeaCargoAllocationServiceServer) ApplySeaHouseBillAllocationSummary(context.Context, *ApplySeaHouseBillAllocationSummaryRequest) (*ApplySeaHouseBillAllocationSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplySeaHouseBillAllocationSummary not implemented")
}
func (UnimplementedSeaCargoAllocationServiceServer) mustEmbedUnimplementedSeaCargoAllocationServiceServer() {
}
func (UnimplementedSeaCargoAllocationServiceServer) testEmbeddedByValue() {}

// UnsafeSeaCargoAllocationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SeaCargoAllocationServiceServer will
// result in compilation errors.
type UnsafeSeaCargoAllocationServiceServer interface {
	mustEmbedUnimplementedSeaCargoAllocationServiceServer()
}

func RegisterSeaCargoAllocationServiceServer(s grpc.ServiceRegistrar, srv SeaCargoAllocationServiceServer) {
	// If the following call panics, it indicates UnimplementedSeaCargoAllocationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SeaCargoAllocationService_ServiceDesc, srv)
}

func _SeaCargoAllocationService_GetSeaCargoAllocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSeaCargoAllocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeaCargoAllocationServiceServer).GetSeaCargoAllocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeaCargoAllocationService_GetSeaCargoAllocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeaCargoAllocationServiceServer).GetSeaCargoAllocation(ctx, req.(*GetSeaCargoAllocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeaCargoAllocationService_SaveSeaCargoAllocationDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveSeaCargoAllocationDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeaCargoAllocationServiceServer).SaveSeaCargoAllocationDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeaCargoAllocationService_SaveSeaCargoAllocationDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeaCargoAllocationServiceServer).SaveSeaCargoAllocationDraft(ctx, req.(*SaveSeaCargoAllocationDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeaCargoAllocationService_ConfirmSeaCargoAllocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmSeaCargoAllocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeaCargoAllocationServiceServer).ConfirmSeaCargoAllocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeaCargoAllocationService_ConfirmSeaCargoAllocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeaCargoAllocationServiceServer).ConfirmSeaCargoAllocation(ctx, req.(*ConfirmSeaCargoAllocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeaCargoAllocationService_WithdrawSeaCargoAllocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawSeaCargoAllocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeaCargoAllocationServiceServer).WithdrawSeaCargoAllocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeaCargoAllocationService_WithdrawSeaCargoAllocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeaCargoAllocationServiceServer).WithdrawSeaCargoAllocation(ctx, req.(*WithdrawSeaCargoAllocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeaCargoAllocationService_ApplySeaOrderCargoSummaryToMasterBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplySeaOrderCargoSummaryToMasterBillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeaCargoAllocationServiceServer).ApplySeaOrderCargoSummaryToMasterBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeaCargoAllocationService_ApplySeaOrderCargoSummaryToMasterBill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeaCargoAllocationServiceServer).ApplySeaOrderCargoSummaryToMasterBill(ctx, req.(*ApplySeaOrderCargoSummaryToMasterBillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeaCargoAllocationService_ApplySeaHouseBillAllocationSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplySeaHouseBillAllocationSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeaCargoAllocationServiceServer).ApplySeaHouseBillAllocationSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SeaCargoAllocationService_ApplySeaHouseBillAllocationSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeaCargoAllocationServiceServer).ApplySeaHouseBillAllocationSummary(ctx, req.(*ApplySeaHouseBillAllocationSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SeaCargoAllocationService_ServiceDesc is the grpc.ServiceDesc for SeaCargoAllocationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SeaCargoAllocationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.v1.SeaCargoAllocationService",
	HandlerType: (*SeaCargoAllocationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSeaCargoAllocation",
			Handler:    _SeaCargoAllocationService_GetSeaCargoAllocation_Handler,
		},
		{
			MethodName: "SaveSeaCargoAllocationDraft",
			Handler:    _SeaCargoAllocationService_SaveSeaCargoAllocationDraft_Handler,
		},
		{
			MethodName: "ConfirmSeaCargoAllocation",
			Handler:    _SeaCargoAllocationService_ConfirmSeaCargoAllocation_Handler,
		},
		{
			MethodName: "WithdrawSeaCargoAllocation",
			Handler:    _SeaCargoAllocationService_WithdrawSeaCargoAllocation_Handler,
		},
		{
			MethodName: "ApplySeaOrderCargoSummaryToMasterBill",
			Handler:    _SeaCargoAllocationService_ApplySeaOrderCargoSummaryToMasterBill_Handler,
		},
		{
			MethodName: "ApplySeaHouseBillAllocationSummary",
			Handler:    _SeaCargoAllocationService_ApplySeaHouseBillAllocationSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order/v1/sea_cargo_allocation.proto",
}
