// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: order/v1/sea_order_change.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationSeaOrderChangeServiceExecuteSeaOrderReassignment = "/order.v1.SeaOrderChangeService/ExecuteSeaOrderReassignment"
const OperationSeaOrderChangeServiceExecuteSeaOrderSplit = "/order.v1.SeaOrderChangeService/ExecuteSeaOrderSplit"
const OperationSeaOrderChangeServiceGetSeaOrderChangeActions = "/order.v1.SeaOrderChangeService/GetSeaOrderChangeActions"
const OperationSeaOrderChangeServiceGetSeaOrderChangeEvent = "/order.v1.SeaOrderChangeService/GetSeaOrderChangeEvent"
const OperationSeaOrderChangeServiceGetSeaOrderSplitContext = "/order.v1.SeaOrderChangeService/GetSeaOrderSplitContext"
const OperationSeaOrderChangeServiceListSeaOrderChangeEvents = "/order.v1.SeaOrderChangeService/ListSeaOrderChangeEvents"
const OperationSeaOrderChangeServicePreviewSeaOrderReassignment = "/order.v1.SeaOrderChangeService/PreviewSeaOrderReassignment"
const OperationSeaOrderChangeServicePreviewSeaOrderSplit = "/order.v1.SeaOrderChangeService/PreviewSeaOrderSplit"

type SeaOrderChangeServiceHTTPServer interface {
	// ExecuteSeaOrderReassignment ExecuteSeaOrderReassignment 执行整体改配。
	ExecuteSeaOrderReassignment(context.Context, *ExecuteSeaOrderReassignmentRequest) (*ExecuteSeaOrderReassignmentResponse, error)
	// ExecuteSeaOrderSplit ExecuteSeaOrderSplit 执行部分拆票。
	ExecuteSeaOrderSplit(context.Context, *ExecuteSeaOrderSplitRequest) (*ExecuteSeaOrderSplitResponse, error)
	// GetSeaOrderChangeActions GetSeaOrderChangeActions 获取订单可执行动作及阻断原因。
	GetSeaOrderChangeActions(context.Context, *GetSeaOrderChangeActionsRequest) (*GetSeaOrderChangeActionsResponse, error)
	// GetSeaOrderChangeEvent GetSeaOrderChangeEvent 获取单个拆票或改配事件详情。
	GetSeaOrderChangeEvent(context.Context, *GetSeaOrderChangeEventRequest) (*GetSeaOrderChangeEventResponse, error)
	// GetSeaOrderSplitContext GetSeaOrderSplitContext 获取拆票上下文事实与可分配数据。
	GetSeaOrderSplitContext(context.Context, *GetSeaOrderSplitContextRequest) (*GetSeaOrderSplitContextResponse, error)
	// ListSeaOrderChangeEvents ListSeaOrderChangeEvents 查询订单拆票与改配事件历史。
	ListSeaOrderChangeEvents(context.Context, *ListSeaOrderChangeEventsRequest) (*ListSeaOrderChangeEventsResponse, error)
	// PreviewSeaOrderReassignment PreviewSeaOrderReassignment 预览整体改配航程差异。
	PreviewSeaOrderReassignment(context.Context, *PreviewSeaOrderReassignmentRequest) (*PreviewSeaOrderReassignmentResponse, error)
	// PreviewSeaOrderSplit PreviewSeaOrderSplit 预览拆票结果、守恒计算与计划重算。
	PreviewSeaOrderSplit(context.Context, *PreviewSeaOrderSplitRequest) (*PreviewSeaOrderSplitResponse, error)
}

func RegisterSeaOrderChangeServiceHTTPServer(s *http.Server, srv SeaOrderChangeServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/api/v1/orders/{order_id}/sea-order-change/actions", _SeaOrderChangeService_GetSeaOrderChangeActions0_HTTP_Handler(srv))
	r.Handle("GET", "/api/v1/orders/{order_id}/sea-order-change/split-context", _SeaOrderChangeService_GetSeaOrderSplitContext0_HTTP_Handler(srv))
	r.Handle("POST", "/api/v1/orders/{order_id}/sea-order-change/split/preview", _SeaOrderChangeService_PreviewSeaOrderSplit0_HTTP_Handler(srv))
	r.Handle("POST", "/api/v1/orders/{order_id}/sea-order-change/split/execute", _SeaOrderChangeService_ExecuteSeaOrderSplit0_HTTP_Handler(srv))
	r.Handle("POST", "/api/v1/orders/{order_id}/sea-order-change/reassignment/preview", _SeaOrderChangeService_PreviewSeaOrderReassignment0_HTTP_Handler(srv))
	r.Handle("POST", "/api/v1/orders/{order_id}/sea-order-change/reassignment/execute", _SeaOrderChangeService_ExecuteSeaOrderReassignment0_HTTP_Handler(srv))
	r.Handle("GET", "/api/v1/orders/{order_id}/sea-order-change/events", _SeaOrderChangeService_ListSeaOrderChangeEvents0_HTTP_Handler(srv))
	r.Handle("GET", "/api/v1/orders/{order_id}/sea-order-change/events/{event_id}", _SeaOrderChangeService_GetSeaOrderChangeEvent0_HTTP_Handler(srv))
}

func _SeaOrderChangeService_GetSeaOrderChangeActions0_HTTP_Handler(srv SeaOrderChangeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSeaOrderChangeActionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSeaOrderChangeServiceGetSeaOrderChangeActions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSeaOrderChangeActions(ctx, req.(*GetSeaOrderChangeActionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetSeaOrderChangeActionsResponse)
		return ctx.Result(200, reply)
	}
}

func _SeaOrderChangeService_GetSeaOrderSplitContext0_HTTP_Handler(srv SeaOrderChangeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSeaOrderSplitContextRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSeaOrderChangeServiceGetSeaOrderSplitContext)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSeaOrderSplitContext(ctx, req.(*GetSeaOrderSplitContextRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetSeaOrderSplitContextResponse)
		return ctx.Result(200, reply)
	}
}

func _SeaOrderChangeService_PreviewSeaOrderSplit0_HTTP_Handler(srv SeaOrderChangeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PreviewSeaOrderSplitRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSeaOrderChangeServicePreviewSeaOrderSplit)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PreviewSeaOrderSplit(ctx, req.(*PreviewSeaOrderSplitRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PreviewSeaOrderSplitResponse)
		return ctx.Result(200, reply)
	}
}

func _SeaOrderChangeService_ExecuteSeaOrderSplit0_HTTP_Handler(srv SeaOrderChangeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ExecuteSeaOrderSplitRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSeaOrderChangeServiceExecuteSeaOrderSplit)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ExecuteSeaOrderSplit(ctx, req.(*ExecuteSeaOrderSplitRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ExecuteSeaOrderSplitResponse)
		return ctx.Result(200, reply)
	}
}

func _SeaOrderChangeService_PreviewSeaOrderReassignment0_HTTP_Handler(srv SeaOrderChangeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PreviewSeaOrderReassignmentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSeaOrderChangeServicePreviewSeaOrderReassignment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PreviewSeaOrderReassignment(ctx, req.(*PreviewSeaOrderReassignmentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PreviewSeaOrderReassignmentResponse)
		return ctx.Result(200, reply)
	}
}

func _SeaOrderChangeService_ExecuteSeaOrderReassignment0_HTTP_Handler(srv SeaOrderChangeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ExecuteSeaOrderReassignmentRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSeaOrderChangeServiceExecuteSeaOrderReassignment)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ExecuteSeaOrderReassignment(ctx, req.(*ExecuteSeaOrderReassignmentRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ExecuteSeaOrderReassignmentResponse)
		return ctx.Result(200, reply)
	}
}

func _SeaOrderChangeService_ListSeaOrderChangeEvents0_HTTP_Handler(srv SeaOrderChangeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSeaOrderChangeEventsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSeaOrderChangeServiceListSeaOrderChangeEvents)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSeaOrderChangeEvents(ctx, req.(*ListSeaOrderChangeEventsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSeaOrderChangeEventsResponse)
		return ctx.Result(200, reply)
	}
}

func _SeaOrderChangeService_GetSeaOrderChangeEvent0_HTTP_Handler(srv SeaOrderChangeServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSeaOrderChangeEventRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSeaOrderChangeServiceGetSeaOrderChangeEvent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSeaOrderChangeEvent(ctx, req.(*GetSeaOrderChangeEventRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetSeaOrderChangeEventResponse)
		return ctx.Result(200, reply)
	}
}

type SeaOrderChangeServiceHTTPClient interface {
	// ExecuteSeaOrderReassignment ExecuteSeaOrderReassignment 执行整体改配。
	ExecuteSeaOrderReassignment(ctx context.Context, req *ExecuteSeaOrderReassignmentRequest, opts ...http.CallOption) (rsp *ExecuteSeaOrderReassignmentResponse, err error)
	// ExecuteSeaOrderSplit ExecuteSeaOrderSplit 执行部分拆票。
	ExecuteSeaOrderSplit(ctx context.Context, req *ExecuteSeaOrderSplitRequest, opts ...http.CallOption) (rsp *ExecuteSeaOrderSplitResponse, err error)
	// GetSeaOrderChangeActions GetSeaOrderChangeActions 获取订单可执行动作及阻断原因。
	GetSeaOrderChangeActions(ctx context.Context, req *GetSeaOrderChangeActionsRequest, opts ...http.CallOption) (rsp *GetSeaOrderChangeActionsResponse, err error)
	// GetSeaOrderChangeEvent GetSeaOrderChangeEvent 获取单个拆票或改配事件详情。
	GetSeaOrderChangeEvent(ctx context.Context, req *GetSeaOrderChangeEventRequest, opts ...http.CallOption) (rsp *GetSeaOrderChangeEventResponse, err error)
	// GetSeaOrderSplitContext GetSeaOrderSplitContext 获取拆票上下文事实与可分配数据。
	GetSeaOrderSplitContext(ctx context.Context, req *GetSeaOrderSplitContextRequest, opts ...http.CallOption) (rsp *GetSeaOrderSplitContextResponse, err error)
	// ListSeaOrderChangeEvents ListSeaOrderChangeEvents 查询订单拆票与改配事件历史。
	ListSeaOrderChangeEvents(ctx context.Context, req *ListSeaOrderChangeEventsRequest, opts ...http.CallOption) (rsp *ListSeaOrderChangeEventsResponse, err error)
	// PreviewSeaOrderReassignment PreviewSeaOrderReassignment 预览整体改配航程差异。
	PreviewSeaOrderReassignment(ctx context.Context, req *PreviewSeaOrderReassignmentRequest, opts ...http.CallOption) (rsp *PreviewSeaOrderReassignmentResponse, err error)
	// PreviewSeaOrderSplit PreviewSeaOrderSplit 预览拆票结果、守恒计算与计划重算。
	PreviewSeaOrderSplit(ctx context.Context, req *PreviewSeaOrderSplitRequest, opts ...http.CallOption) (rsp *PreviewSeaOrderSplitResponse, err error)
}

type SeaOrderChangeServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewSeaOrderChangeServiceHTTPClient(client *http.Client) SeaOrderChangeServiceHTTPClient {
	return &SeaOrderChangeServiceHTTPClientImpl{client}
}

// ExecuteSeaOrderReassignment ExecuteSeaOrderReassignment 执行整体改配。
func (c *SeaOrderChangeServiceHTTPClientImpl) ExecuteSeaOrderReassignment(ctx context.Context, in *ExecuteSeaOrderReassignmentRequest, opts ...http.CallOption) (*ExecuteSeaOrderReassignmentResponse, error) {
	var out ExecuteSeaOrderReassignmentResponse
	pattern := "/api/v1/orders/{order_id}/sea-order-change/reassignment/execute"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationSeaOrderChangeServiceExecuteSeaOrderReassignment),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ExecuteSeaOrderSplit ExecuteSeaOrderSplit 执行部分拆票。
func (c *SeaOrderChangeServiceHTTPClientImpl) ExecuteSeaOrderSplit(ctx context.Context, in *ExecuteSeaOrderSplitRequest, opts ...http.CallOption) (*ExecuteSeaOrderSplitResponse, error) {
	var out ExecuteSeaOrderSplitResponse
	pattern := "/api/v1/orders/{order_id}/sea-order-change/split/execute"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationSeaOrderChangeServiceExecuteSeaOrderSplit),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetSeaOrderChangeActions GetSeaOrderChangeActions 获取订单可执行动作及阻断原因。
func (c *SeaOrderChangeServiceHTTPClientImpl) GetSeaOrderChangeActions(ctx context.Context, in *GetSeaOrderChangeActionsRequest, opts ...http.CallOption) (*GetSeaOrderChangeActionsResponse, error) {
	var out GetSeaOrderChangeActionsResponse
	pattern := "/api/v1/orders/{order_id}/sea-order-change/actions"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSeaOrderChangeServiceGetSeaOrderChangeActions),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetSeaOrderChangeEvent GetSeaOrderChangeEvent 获取单个拆票或改配事件详情。
func (c *SeaOrderChangeServiceHTTPClientImpl) GetSeaOrderChangeEvent(ctx context.Context, in *GetSeaOrderChangeEventRequest, opts ...http.CallOption) (*GetSeaOrderChangeEventResponse, error) {
	var out GetSeaOrderChangeEventResponse
	pattern := "/api/v1/orders/{order_id}/sea-order-change/events/{event_id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSeaOrderChangeServiceGetSeaOrderChangeEvent),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetSeaOrderSplitContext GetSeaOrderSplitContext 获取拆票上下文事实与可分配数据。
func (c *SeaOrderChangeServiceHTTPClientImpl) GetSeaOrderSplitContext(ctx context.Context, in *GetSeaOrderSplitContextRequest, opts ...http.CallOption) (*GetSeaOrderSplitContextResponse, error) {
	var out GetSeaOrderSplitContextResponse
	pattern := "/api/v1/orders/{order_id}/sea-order-change/split-context"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSeaOrderChangeServiceGetSeaOrderSplitContext),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListSeaOrderChangeEvents ListSeaOrderChangeEvents 查询订单拆票与改配事件历史。
func (c *SeaOrderChangeServiceHTTPClientImpl) ListSeaOrderChangeEvents(ctx context.Context, in *ListSeaOrderChangeEventsRequest, opts ...http.CallOption) (*ListSeaOrderChangeEventsResponse, error) {
	var out ListSeaOrderChangeEventsResponse
	pattern := "/api/v1/orders/{order_id}/sea-order-change/events"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationSeaOrderChangeServiceListSeaOrderChangeEvents),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PreviewSeaOrderReassignment PreviewSeaOrderReassignment 预览整体改配航程差异。
func (c *SeaOrderChangeServiceHTTPClientImpl) PreviewSeaOrderReassignment(ctx context.Context, in *PreviewSeaOrderReassignmentRequest, opts ...http.CallOption) (*PreviewSeaOrderReassignmentResponse, error) {
	var out PreviewSeaOrderReassignmentResponse
	pattern := "/api/v1/orders/{order_id}/sea-order-change/reassignment/preview"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationSeaOrderChangeServicePreviewSeaOrderReassignment),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// PreviewSeaOrderSplit PreviewSeaOrderSplit 预览拆票结果、守恒计算与计划重算。
func (c *SeaOrderChangeServiceHTTPClientImpl) PreviewSeaOrderSplit(ctx context.Context, in *PreviewSeaOrderSplitRequest, opts ...http.CallOption) (*PreviewSeaOrderSplitResponse, error) {
	var out PreviewSeaOrderSplitResponse
	pattern := "/api/v1/orders/{order_id}/sea-order-change/split/preview"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationSeaOrderChangeServicePreviewSeaOrderSplit),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
