// Code generated by ent, DO NOT EDIT.

package ordercontainerrequest

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldEQ(FieldUpdatedAt, v))
}

// OrderID applies equality check predicate on the "order_id" field. It's identical to OrderIDEQ.
func OrderID(v uuid.UUID) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldEQ(FieldOrderID, v))
}

// ContainerSpecID applies equality check predicate on the "container_spec_id" field. It's identical to ContainerSpecIDEQ.
func ContainerSpecID(v uuid.UUID) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldEQ(FieldContainerSpecID, v))
}

// Quantity applies equality check predicate on the "quantity" field. It's identical to QuantityEQ.
func Quantity(v int) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldEQ(FieldQuantity, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldLTE(FieldUpdatedAt, v))
}

// OrderIDEQ applies the EQ predicate on the "order_id" field.
func OrderIDEQ(v uuid.UUID) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldEQ(FieldOrderID, v))
}

// OrderIDNEQ applies the NEQ predicate on the "order_id" field.
func OrderIDNEQ(v uuid.UUID) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldNEQ(FieldOrderID, v))
}

// OrderIDIn applies the In predicate on the "order_id" field.
func OrderIDIn(vs ...uuid.UUID) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldIn(FieldOrderID, vs...))
}

// OrderIDNotIn applies the NotIn predicate on the "order_id" field.
func OrderIDNotIn(vs ...uuid.UUID) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldNotIn(FieldOrderID, vs...))
}

// ContainerSpecIDEQ applies the EQ predicate on the "container_spec_id" field.
func ContainerSpecIDEQ(v uuid.UUID) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldEQ(FieldContainerSpecID, v))
}

// ContainerSpecIDNEQ applies the NEQ predicate on the "container_spec_id" field.
func ContainerSpecIDNEQ(v uuid.UUID) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldNEQ(FieldContainerSpecID, v))
}

// ContainerSpecIDIn applies the In predicate on the "container_spec_id" field.
func ContainerSpecIDIn(vs ...uuid.UUID) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldIn(FieldContainerSpecID, vs...))
}

// ContainerSpecIDNotIn applies the NotIn predicate on the "container_spec_id" field.
func ContainerSpecIDNotIn(vs ...uuid.UUID) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldNotIn(FieldContainerSpecID, vs...))
}

// ContainerSpecIDGT applies the GT predicate on the "container_spec_id" field.
func ContainerSpecIDGT(v uuid.UUID) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldGT(FieldContainerSpecID, v))
}

// ContainerSpecIDGTE applies the GTE predicate on the "container_spec_id" field.
func ContainerSpecIDGTE(v uuid.UUID) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldGTE(FieldContainerSpecID, v))
}

// ContainerSpecIDLT applies the LT predicate on the "container_spec_id" field.
func ContainerSpecIDLT(v uuid.UUID) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldLT(FieldContainerSpecID, v))
}

// ContainerSpecIDLTE applies the LTE predicate on the "container_spec_id" field.
func ContainerSpecIDLTE(v uuid.UUID) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldLTE(FieldContainerSpecID, v))
}

// QuantityEQ applies the EQ predicate on the "quantity" field.
func QuantityEQ(v int) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldEQ(FieldQuantity, v))
}

// QuantityNEQ applies the NEQ predicate on the "quantity" field.
func QuantityNEQ(v int) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldNEQ(FieldQuantity, v))
}

// QuantityIn applies the In predicate on the "quantity" field.
func QuantityIn(vs ...int) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldIn(FieldQuantity, vs...))
}

// QuantityNotIn applies the NotIn predicate on the "quantity" field.
func QuantityNotIn(vs ...int) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldNotIn(FieldQuantity, vs...))
}

// QuantityGT applies the GT predicate on the "quantity" field.
func QuantityGT(v int) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldGT(FieldQuantity, v))
}

// QuantityGTE applies the GTE predicate on the "quantity" field.
func QuantityGTE(v int) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldGTE(FieldQuantity, v))
}

// QuantityLT applies the LT predicate on the "quantity" field.
func QuantityLT(v int) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldLT(FieldQuantity, v))
}

// QuantityLTE applies the LTE predicate on the "quantity" field.
func QuantityLTE(v int) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.FieldLTE(FieldQuantity, v))
}

// HasOrder applies the HasEdge predicate on the "order" edge.
func HasOrder() predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OrderTable, OrderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrderWith applies the HasEdge predicate on the "order" edge with a given conditions (other predicates).
func HasOrderWith(preds ...predicate.Order) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(func(s *sql.Selector) {
		step := newOrderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OrderContainerRequest) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OrderContainerRequest) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OrderContainerRequest) predicate.OrderContainerRequest {
	return predicate.OrderContainerRequest(sql.NotPredicates(p))
}
