package biz

import "github.com/google/wire"

// ProviderSet is biz providers.
var ProviderSet = wire.NewSet(NewAuthUsecase, NewPartnerUsecase, NewPartnerAccountUsecase, NewPartnerContractUsecase, NewPartnerSettlementRuleUsecase, NewPartnerAttachmentUsecase, NewPartnerShippingPresetUsecase, NewPartnerInvoiceProfileUsecase, NewAdminUsecase, NewMasterDataUsecase, NewIndustryReferenceUsecase, NewReferenceDataUsecase, NewOrderConfigUsecase, NewMilestoneConfigUsecase, NewOrderUsecase, NewOrderMilestoneUsecase, NewOrderAttachmentUsecase, NewOrderPersonnelUsecase, NewOrderContainerUsecase, NewOrderCargoItemUsecase, NewOrderShippingDocumentUsecase, NewOrderReleasePodUsecase, NewOrderAbnormalCaseUsecase, NewExchangeRateUsecase, NewFeeCatalogUsecase, NewOrderFeeUsecase, NewSettlementUsecase, NewFeeLedgerPreferenceUsecase, NewFinanceCustomSettingUsecase, NewFinanceBillUsecase, NewFinanceInvoiceUsecase, NewFinanceCashflowUsecase, NewVerificationUsecase, NewCommissionUsecase, NewBackgroundTaskUsecase, NewNotificationUsecase)
