package biz

import "github.com/google/wire"

// ProviderSet is biz providers.
var ProviderSet = wire.NewSet(NewEnterpriseResourceUsecase, NewBusinessTagUsecase, NewAuthUsecase, NewPartnerUsecase, NewPartnerAccountUsecase, NewPartnerContractUsecase, NewPartnerSettlementRuleUsecase, NewPartnerAttachmentUsecase, NewPartnerShippingPresetUsecase, NewPartnerInvoiceProfileUsecase, NewAdminUsecase, NewMasterDataUsecase, NewIndustryReferenceUsecase, NewReferenceDataUsecase, NewOrderConfigUsecase, NewOrderUsecase, NewOrderMilestoneUsecase, NewOrderAttachmentUsecase, NewOrderPersonnelUsecase, NewOrderContainerUsecase, NewOrderCargoItemUsecase, NewOrderShippingDocumentUsecase, NewSeaDocumentUsecase, NewSeaCargoAllocationUsecase, NewOrderReleasePodUsecase, NewOrderAbnormalCaseUsecase, NewExchangeRateUsecase, NewFeeCatalogUsecase, NewOrderFeeUsecase, NewSettlementUsecase, NewFeeLedgerPreferenceUsecase, NewFinanceCustomSettingUsecase, NewFinanceBillUsecase, NewFinanceInvoiceUsecase, NewFinanceCashflowUsecase, NewVerificationUsecase, NewCommissionUsecase, NewBackgroundTaskUsecase, NewNotificationUsecase, NewObjectDeletionUsecase)
