export interface FinanceFieldMeta {
  id: number;
  key: string;
  name: string;
  defaultVisible: boolean;
  category?: string;
  align?: 'left' | 'center' | 'right';
  width?: number;
}

export const ALL_153_FINANCE_FIELDS: FinanceFieldMeta[] = [
  { id: 1, key: 'direction', name: '属性', defaultVisible: true, align: 'center', width: 75 },
  { id: 2, key: 'creatorName', name: '订单创建人员', defaultVisible: false, width: 120 },
  { id: 3, key: 'commissionRate', name: '佣金比例（%）', defaultVisible: false, align: 'right', width: 100 },
  { id: 4, key: 'feeNo', name: '费用编号', defaultVisible: false, width: 140 },
  { id: 5, key: 'externalOrderNo', name: '简云订单编号', defaultVisible: false, width: 150 },
  { id: 6, key: 'masterNo', name: '主单号', defaultVisible: true, width: 140 },
  { id: 7, key: 'customerName', name: '委托单位', defaultVisible: true, width: 180 },
  { id: 8, key: 'settlementPartyName', name: '结算单位', defaultVisible: true, width: 180 },
  { id: 9, key: 'businessType', name: '业务类型', defaultVisible: true, width: 95 },
  { id: 10, key: 'feeName', name: '费用名称', defaultVisible: true, width: 130 },
  { id: 11, key: 'currency', name: '币种', defaultVisible: true, align: 'center', width: 70 },
  { id: 12, key: 'totalAmount', name: '金额', defaultVisible: true, align: 'right', width: 125 },
  { id: 13, key: 'externalBillNo', name: '简云账单编号', defaultVisible: false, width: 150 },
  { id: 14, key: 'invoiceNo', name: '发票号', defaultVisible: true, width: 130 },
  { id: 15, key: 'status', name: '费用状态', defaultVisible: true, width: 85 },
  { id: 16, key: 'exchangeRate', name: '汇率', defaultVisible: true, align: 'right', width: 85 },
  { id: 17, key: 'operatorName', name: '操作人员', defaultVisible: true, width: 110 },
  { id: 18, key: 'salesName', name: '业务人员', defaultVisible: true, width: 110 },
  { id: 19, key: 'csName', name: '客服人员', defaultVisible: true, width: 110 },
  { id: 20, key: 'invoiceDate', name: '开票时间', defaultVisible: false, width: 110 },
  { id: 21, key: 'relatedPersonnel', name: '关联人员', defaultVisible: true, width: 120 },
  { id: 22, key: 'containerTypeQty', name: '箱型箱量', defaultVisible: false, width: 110 },
  { id: 23, key: 'vesselName', name: '船名', defaultVisible: false, width: 130 },
  { id: 24, key: 'voyageFlightNo', name: '航次/航班号/班列号', defaultVisible: false, width: 140 },
  { id: 25, key: 'etd', name: 'ETD/班列日期', defaultVisible: false, width: 110 },
  { id: 26, key: 'polLocation', name: '起运港/上货站', defaultVisible: false, width: 120 },
  { id: 27, key: 'podLocation', name: '目的港/下货站', defaultVisible: false, width: 120 },
  { id: 28, key: 'note', name: '备注', defaultVisible: false, width: 140 },
  { id: 29, key: 'shipmentType', name: '托运类型', defaultVisible: false, width: 90 },
  { id: 30, key: 'carrierName', name: '航空/船/班列公司', defaultVisible: false, width: 140 },
  { id: 31, key: 'customerReferenceNo', name: '客户业务编号', defaultVisible: false, width: 130 },
  { id: 32, key: 'verificationDate', name: '核销时间', defaultVisible: false, width: 110 },
  { id: 33, key: 'billCreatedAt', name: '账单创建时间', defaultVisible: false, width: 140 },
  { id: 34, key: 'isReconciled', name: '是否对账', defaultVisible: false, width: 90 },
  { id: 35, key: 'billTag', name: '账单标签', defaultVisible: false, width: 100 },
  { id: 36, key: 'orderTag', name: '订单标签', defaultVisible: false, width: 100 },
  { id: 37, key: 'taxRate', name: '税率(%)', defaultVisible: true, align: 'right', width: 75 },
  { id: 38, key: 'taxAmount', name: '税金', defaultVisible: true, align: 'right', width: 95 },
  { id: 39, key: 'netAmount', name: '不含税总价', defaultVisible: true, align: 'right', width: 110 },
  { id: 40, key: 'isSingleFeeLocked', name: '单条费用锁定', defaultVisible: false, width: 100 },
  { id: 41, key: 'eta', name: 'ETA', defaultVisible: false, width: 110 },
  { id: 42, key: 'atd', name: 'ATD', defaultVisible: false, width: 110 },
  { id: 43, key: 'ata', name: 'ATA', defaultVisible: false, width: 110 },
  { id: 44, key: 'houseNo', name: '分单号', defaultVisible: true, width: 130 },
  { id: 45, key: 'internalReferenceNo', name: '企业内部编号', defaultVisible: false, width: 130 },
  { id: 46, key: 'orderCreatedAt', name: '订单创建时间', defaultVisible: false, width: 140 },
  { id: 47, key: 'billNo', name: '账单编号', defaultVisible: true, width: 150 },
  { id: 48, key: 'orderNo', name: '订单编号', defaultVisible: true, width: 155 },
  { id: 49, key: 'billExchangeRate', name: '账单汇率', defaultVisible: false, align: 'right', width: 90 },
  { id: 50, key: 'expenseDate', name: '费用时间', defaultVisible: true, width: 110 },
  { id: 51, key: 'soNo', name: 'SO号', defaultVisible: true, width: 130 },
  { id: 52, key: 'baseCurrencyAmount', name: '折本币总价', defaultVisible: true, align: 'right', width: 135 },
  { id: 53, key: 'businessDate', name: '业务时间', defaultVisible: false, width: 110 },
  { id: 54, key: 'importerName', name: '进口方', defaultVisible: false, width: 140 },
  { id: 55, key: 'exporterName', name: '出口方', defaultVisible: false, width: 140 },
  { id: 56, key: 'relatedInfo', name: '关联信息', defaultVisible: true, width: 130 },
  { id: 57, key: 'feeComment', name: '应收应付注释', defaultVisible: false, width: 130 },
  { id: 58, key: 'containerNo', name: '箱号', defaultVisible: false, width: 120 },
  { id: 59, key: 'sealNo', name: '封号', defaultVisible: false, width: 110 },
  { id: 60, key: 'contractNo', name: '合约号', defaultVisible: false, width: 120 },
  { id: 61, key: 'feeSource', name: '费用来源', defaultVisible: false, width: 100 },
  { id: 62, key: 'consignee', name: '收货人简称', defaultVisible: true, width: 120 },
  { id: 63, key: 'shipper', name: '发货人简称', defaultVisible: true, width: 120 },
  { id: 64, key: 'notifyParty', name: '通知人简称', defaultVisible: true, width: 120 },
  { id: 65, key: 'tradeTerm', name: '贸易条款', defaultVisible: false, width: 90 },
  { id: 66, key: 'feederPort', name: '驳船港', defaultVisible: false, width: 110 },
  { id: 67, key: 'destination', name: '目的地', defaultVisible: false, width: 120 },
  { id: 68, key: 'orderStage', name: '订单进程', defaultVisible: false, width: 100 },
  { id: 69, key: 'auditStatus', name: '审核状态', defaultVisible: false, width: 90 },
  { id: 70, key: 'invoicedAmount', name: '开票金额', defaultVisible: false, align: 'right', width: 110 },
  { id: 71, key: 'feeLockedAt', name: '单条费用锁定时间', defaultVisible: false, width: 140 },
  { id: 72, key: 'feeLockedBy', name: '单条费用锁定人', defaultVisible: false, width: 110 },
  { id: 73, key: 'operationNote', name: '操作备注', defaultVisible: false, width: 130 },
  { id: 74, key: 'verifiedAmount', name: '已核销金额', defaultVisible: true, align: 'right', width: 110 },
  { id: 75, key: 'unverifiedAmount', name: '未核销金额', defaultVisible: true, align: 'right', width: 110 },
  { id: 76, key: 'bookingNote', name: '订舱备注', defaultVisible: false, width: 130 },
  { id: 77, key: 'isDirectionFeeLocked', name: '应收/应付费用锁定', defaultVisible: false, width: 130 },
  { id: 78, key: 'directionFeeLockedBy', name: '应收/应付费用锁定人', defaultVisible: false, width: 130 },
  { id: 79, key: 'receivedAt', name: '接单时间', defaultVisible: false, width: 110 },
  { id: 80, key: 'allocationNote', name: '配舱备注', defaultVisible: false, width: 130 },
  { id: 81, key: 'directionFeeLockedAt', name: '应收/应付费用锁定时间', defaultVisible: false, width: 140 },
  { id: 82, key: 'terminalName', name: '码头', defaultVisible: false, width: 120 },
  { id: 83, key: 'shippingLineRoute', name: '航线', defaultVisible: false, width: 110 },
  { id: 84, key: 'cargoNameZh', name: '中文品名', defaultVisible: false, width: 120 },
  { id: 85, key: 'cargoNameEn', name: '英文品名', defaultVisible: false, width: 120 },
  { id: 86, key: 'chargeableWeight', name: '计费重量', defaultVisible: false, align: 'right', width: 100 },
  { id: 87, key: 'overseasPickupAddress', name: '海外提货地址', defaultVisible: false, width: 150 },
  { id: 88, key: 'overseasDeliveryAddress', name: '海外送货地址', defaultVisible: false, width: 150 },
  { id: 89, key: 'volumeWeight', name: '体积重', defaultVisible: false, align: 'right', width: 90 },
  { id: 90, key: 'paymentMethod', name: '付款方式', defaultVisible: false, width: 95 },
  { id: 91, key: 'settlementCurrency', name: '结算币种', defaultVisible: false, align: 'center', width: 80 },
  { id: 92, key: 'settlementExchangeRate', name: '结算汇率', defaultVisible: false, align: 'right', width: 90 },
  { id: 93, key: 'settlementAmount', name: '结算金额', defaultVisible: false, align: 'right', width: 110 },
  { id: 94, key: 'isOrderLocked', name: '订单锁定', defaultVisible: false, width: 90 },
  { id: 95, key: 'quantity', name: '数量', defaultVisible: false, align: 'right', width: 75 },
  { id: 96, key: 'verifierName', name: '核销人', defaultVisible: false, width: 100 },
  { id: 97, key: 'unitPrice', name: '单价', defaultVisible: false, align: 'right', width: 90 },
  { id: 98, key: 'expectedPaymentDate', name: '预计付款日期', defaultVisible: false, width: 110 },
  { id: 99, key: 'isSoc', name: '货主箱标记', defaultVisible: false, width: 90 },
  { id: 100, key: 'truckTypeQty', name: '车型车量', defaultVisible: false, width: 100 },
  { id: 101, key: 'licensePlate', name: '车牌号', defaultVisible: false, width: 100 },
  { id: 102, key: 'customsDeclarationDate', name: '报关日期', defaultVisible: false, width: 110 },
  { id: 103, key: 'tradingCountry', name: '贸易国', defaultVisible: false, width: 100 },
  { id: 104, key: 'customsTotalPackages', name: '报关总件数', defaultVisible: false, align: 'right', width: 95 },
  { id: 105, key: 'customsItemCount', name: '报关项号数', defaultVisible: false, align: 'right', width: 95 },
  { id: 106, key: 'netWeightKg', name: '净重', defaultVisible: false, align: 'right', width: 95 },
  { id: 107, key: 'inboundCheckListNo', name: '进境核注清单', defaultVisible: false, width: 130 },
  { id: 108, key: 'outboundCheckListNo', name: '出境核注清单', defaultVisible: false, width: 130 },
  { id: 109, key: 'inboundCustomsNo', name: '进境报关单', defaultVisible: false, width: 130 },
  { id: 110, key: 'outboundCustomsNo', name: '出境报关单', defaultVisible: false, width: 130 },
  { id: 111, key: 'customsPortCode', name: '出境关别', defaultVisible: false, width: 100 },
  { id: 112, key: 'customsBrokerName', name: '报关行', defaultVisible: false, width: 130 },
  { id: 113, key: 'customsDocNo', name: '报关单号', defaultVisible: false, width: 130 },
  { id: 114, key: 'netUnitPrice', name: '不含税单价', defaultVisible: false, align: 'right', width: 95 },
  { id: 115, key: 'totalPackages', name: '实际总件数', defaultVisible: false, align: 'right', width: 95 },
  { id: 116, key: 'invoiceExchangeRate', name: '开票汇率', defaultVisible: false, align: 'right', width: 90 },
  { id: 117, key: 'actualProfitLoss', name: '实际损益', defaultVisible: false, align: 'right', width: 100 },
  { id: 118, key: 'entrustedGrossWeightTon', name: '委托总毛重（TON）', defaultVisible: false, align: 'right', width: 120 },
  { id: 119, key: 'grossWeightKg', name: '实际总毛重(KGS)', defaultVisible: true, align: 'right', width: 115 },
  { id: 120, key: 'actualVerifiedAmount', name: '实际核销金额', defaultVisible: false, align: 'right', width: 110 },
  { id: 121, key: 'actualGrossWeightTon', name: '实际总毛重（TON）', defaultVisible: false, align: 'right', width: 120 },
  { id: 122, key: 'volumeCbm', name: '实际总体积', defaultVisible: true, align: 'right', width: 100 },
  { id: 123, key: 'revenueTon', name: '计费吨(RT)', defaultVisible: false, align: 'right', width: 95 },
  { id: 124, key: 'serviceType', name: '服务类型', defaultVisible: false, width: 100 },
  { id: 125, key: 'isImportedToErp', name: '是否已导入财务系统', defaultVisible: false, width: 130 },
  { id: 126, key: 'vatAmount', name: 'VAT', defaultVisible: false, align: 'right', width: 90 },
  { id: 127, key: 'invoiceCurrency', name: '开票币种', defaultVisible: false, align: 'center', width: 80 },
  { id: 128, key: 'orgName', name: '所属公司', defaultVisible: false, width: 130 },
  { id: 129, key: 'customerType', name: '客户类型', defaultVisible: false, width: 95 },
  { id: 130, key: 'bookingAgentName', name: '订舱代理', defaultVisible: false, width: 130 },
  { id: 131, key: 'matchedServiceType', name: '对应服务类型', defaultVisible: false, width: 110 },
  { id: 132, key: 'feeCreatorName', name: '费用创建人员', defaultVisible: false, width: 110 },
  { id: 133, key: 'documentationStaffName', name: '单证人员', defaultVisible: false, width: 100 },
  { id: 134, key: 'paymentTermsDays', name: '账期', defaultVisible: false, width: 80 },
  { id: 135, key: 'overdueDays', name: '超账期时间（天）', defaultVisible: false, align: 'right', width: 120 },
  { id: 136, key: 'entryExitPort', name: '出入境口岸', defaultVisible: false, width: 110 },
  { id: 137, key: 'commercialStaffName', name: '商务人员', defaultVisible: false, width: 100 },
  { id: 138, key: 'feeTag', name: '费用标签', defaultVisible: false, width: 100 },
  { id: 139, key: 'relatedPersonnel2', name: '关联人员2', defaultVisible: false, width: 110 },
  { id: 140, key: 'businessCode1', name: '业务信息代码一', defaultVisible: false, width: 120 },
  { id: 141, key: 'invoicedTotalAmount', name: '已开票金额', defaultVisible: false, align: 'right', width: 110 },
  { id: 142, key: 'businessCode2', name: '业务信息代码二', defaultVisible: false, width: 120 },
  { id: 143, key: 'mblCount', name: 'MBL份数', defaultVisible: false, align: 'right', width: 85 },
  { id: 144, key: 'uninvoicedAmount', name: '未开票金额', defaultVisible: false, align: 'right', width: 110 },
  { id: 145, key: 'hblCount', name: 'HBL份数', defaultVisible: false, align: 'right', width: 85 },
  { id: 146, key: 'isVoucherExported', name: '已导出凭证', defaultVisible: false, width: 95 },
  { id: 147, key: 'shippingAgentName', name: '船代', defaultVisible: false, width: 120 },
  { id: 148, key: 'orderLockedAt', name: '订单锁定时间', defaultVisible: false, width: 140 },
  { id: 149, key: 'accountingMonth', name: '标记入账月份', defaultVisible: false, width: 110 },
  { id: 150, key: 'developmentMethod', name: '开发方式', defaultVisible: false, width: 95 },
  { id: 151, key: 'settlementMethod', name: '结算方式', defaultVisible: false, width: 95 },
  { id: 152, key: 'collaborationStatus', name: '协同状态', defaultVisible: false, width: 95 },
  { id: 153, key: 'collaborationCompany', name: '协同公司', defaultVisible: false, width: 130 },
];

export function getDefaultColumnPreferences(): { fieldKey: string; visible: boolean }[] {
  return ALL_153_FINANCE_FIELDS.map((f) => ({
    fieldKey: f.key,
    visible: f.defaultVisible,
  }));
}

export function getDefaultRowColors(): {
  unbilled: string;
  unverifiedUninvoiced: string;
  invoicedUnverified: string;
  verifiedUninvoiced: string;
  completed: string;
  invoicedPartiallyVerified: string;
  partiallyVerifiedUninvoiced: string;
} {
  return {
    unbilled: '#FFF7E6',
    unverifiedUninvoiced: '#FFFBE6',
    invoicedUnverified: '#E6F4FF',
    verifiedUninvoiced: '#F9F0FF',
    completed: '#F6FFED',
    invoicedPartiallyVerified: '#E6F4FF',
    partiallyVerifiedUninvoiced: '#F9F0FF',
  };
}

