// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/financefeeledgerpreference"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/organization"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/user"
)

// FinanceFeeLedgerPreferenceCreate is the builder for creating a FinanceFeeLedgerPreference entity.
type FinanceFeeLedgerPreferenceCreate struct {
	config
	mutation *FinanceFeeLedgerPreferenceMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *FinanceFeeLedgerPreferenceCreate) SetCreatedAt(v time.Time) *FinanceFeeLedgerPreferenceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FinanceFeeLedgerPreferenceCreate) SetNillableCreatedAt(v *time.Time) *FinanceFeeLedgerPreferenceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *FinanceFeeLedgerPreferenceCreate) SetUpdatedAt(v time.Time) *FinanceFeeLedgerPreferenceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *FinanceFeeLedgerPreferenceCreate) SetNillableUpdatedAt(v *time.Time) *FinanceFeeLedgerPreferenceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetOrganizationID sets the "organization_id" field.
func (_c *FinanceFeeLedgerPreferenceCreate) SetOrganizationID(v uuid.UUID) *FinanceFeeLedgerPreferenceCreate {
	_c.mutation.SetOrganizationID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *FinanceFeeLedgerPreferenceCreate) SetUserID(v uuid.UUID) *FinanceFeeLedgerPreferenceCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetColumns sets the "columns" field.
func (_c *FinanceFeeLedgerPreferenceCreate) SetColumns(v json.RawMessage) *FinanceFeeLedgerPreferenceCreate {
	_c.mutation.SetColumns(v)
	return _c
}

// SetPageSize sets the "page_size" field.
func (_c *FinanceFeeLedgerPreferenceCreate) SetPageSize(v int) *FinanceFeeLedgerPreferenceCreate {
	_c.mutation.SetPageSize(v)
	return _c
}

// SetSortField sets the "sort_field" field.
func (_c *FinanceFeeLedgerPreferenceCreate) SetSortField(v string) *FinanceFeeLedgerPreferenceCreate {
	_c.mutation.SetSortField(v)
	return _c
}

// SetNillableSortField sets the "sort_field" field if the given value is not nil.
func (_c *FinanceFeeLedgerPreferenceCreate) SetNillableSortField(v *string) *FinanceFeeLedgerPreferenceCreate {
	if v != nil {
		_c.SetSortField(*v)
	}
	return _c
}

// SetSortDirection sets the "sort_direction" field.
func (_c *FinanceFeeLedgerPreferenceCreate) SetSortDirection(v financefeeledgerpreference.SortDirection) *FinanceFeeLedgerPreferenceCreate {
	_c.mutation.SetSortDirection(v)
	return _c
}

// SetNillableSortDirection sets the "sort_direction" field if the given value is not nil.
func (_c *FinanceFeeLedgerPreferenceCreate) SetNillableSortDirection(v *financefeeledgerpreference.SortDirection) *FinanceFeeLedgerPreferenceCreate {
	if v != nil {
		_c.SetSortDirection(*v)
	}
	return _c
}

// SetRowColors sets the "row_colors" field.
func (_c *FinanceFeeLedgerPreferenceCreate) SetRowColors(v json.RawMessage) *FinanceFeeLedgerPreferenceCreate {
	_c.mutation.SetRowColors(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *FinanceFeeLedgerPreferenceCreate) SetVersion(v uint64) *FinanceFeeLedgerPreferenceCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *FinanceFeeLedgerPreferenceCreate) SetNillableVersion(v *uint64) *FinanceFeeLedgerPreferenceCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *FinanceFeeLedgerPreferenceCreate) SetID(v uuid.UUID) *FinanceFeeLedgerPreferenceCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *FinanceFeeLedgerPreferenceCreate) SetNillableID(v *uuid.UUID) *FinanceFeeLedgerPreferenceCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_c *FinanceFeeLedgerPreferenceCreate) SetOrganization(v *Organization) *FinanceFeeLedgerPreferenceCreate {
	return _c.SetOrganizationID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *FinanceFeeLedgerPreferenceCreate) SetUser(v *User) *FinanceFeeLedgerPreferenceCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the FinanceFeeLedgerPreferenceMutation object of the builder.
func (_c *FinanceFeeLedgerPreferenceCreate) Mutation() *FinanceFeeLedgerPreferenceMutation {
	return _c.mutation
}

// Save creates the FinanceFeeLedgerPreference in the database.
func (_c *FinanceFeeLedgerPreferenceCreate) Save(ctx context.Context) (*FinanceFeeLedgerPreference, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FinanceFeeLedgerPreferenceCreate) SaveX(ctx context.Context) *FinanceFeeLedgerPreference {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FinanceFeeLedgerPreferenceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FinanceFeeLedgerPreferenceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FinanceFeeLedgerPreferenceCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := financefeeledgerpreference.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := financefeeledgerpreference.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := financefeeledgerpreference.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := financefeeledgerpreference.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FinanceFeeLedgerPreferenceCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "FinanceFeeLedgerPreference.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "FinanceFeeLedgerPreference.updated_at"`)}
	}
	if _, ok := _c.mutation.OrganizationID(); !ok {
		return &ValidationError{Name: "organization_id", err: errors.New(`ent: missing required field "FinanceFeeLedgerPreference.organization_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "FinanceFeeLedgerPreference.user_id"`)}
	}
	if _, ok := _c.mutation.Columns(); !ok {
		return &ValidationError{Name: "columns", err: errors.New(`ent: missing required field "FinanceFeeLedgerPreference.columns"`)}
	}
	if _, ok := _c.mutation.PageSize(); !ok {
		return &ValidationError{Name: "page_size", err: errors.New(`ent: missing required field "FinanceFeeLedgerPreference.page_size"`)}
	}
	if v, ok := _c.mutation.SortField(); ok {
		if err := financefeeledgerpreference.SortFieldValidator(v); err != nil {
			return &ValidationError{Name: "sort_field", err: fmt.Errorf(`ent: validator failed for field "FinanceFeeLedgerPreference.sort_field": %w`, err)}
		}
	}
	if v, ok := _c.mutation.SortDirection(); ok {
		if err := financefeeledgerpreference.SortDirectionValidator(v); err != nil {
			return &ValidationError{Name: "sort_direction", err: fmt.Errorf(`ent: validator failed for field "FinanceFeeLedgerPreference.sort_direction": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RowColors(); !ok {
		return &ValidationError{Name: "row_colors", err: errors.New(`ent: missing required field "FinanceFeeLedgerPreference.row_colors"`)}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "FinanceFeeLedgerPreference.version"`)}
	}
	if len(_c.mutation.OrganizationIDs()) == 0 {
		return &ValidationError{Name: "organization", err: errors.New(`ent: missing required edge "FinanceFeeLedgerPreference.organization"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "FinanceFeeLedgerPreference.user"`)}
	}
	return nil
}

func (_c *FinanceFeeLedgerPreferenceCreate) sqlSave(ctx context.Context) (*FinanceFeeLedgerPreference, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FinanceFeeLedgerPreferenceCreate) createSpec() (*FinanceFeeLedgerPreference, *sqlgraph.CreateSpec) {
	var (
		_node = &FinanceFeeLedgerPreference{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(financefeeledgerpreference.Table, sqlgraph.NewFieldSpec(financefeeledgerpreference.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(financefeeledgerpreference.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(financefeeledgerpreference.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Columns(); ok {
		_spec.SetField(financefeeledgerpreference.FieldColumns, field.TypeJSON, value)
		_node.Columns = value
	}
	if value, ok := _c.mutation.PageSize(); ok {
		_spec.SetField(financefeeledgerpreference.FieldPageSize, field.TypeInt, value)
		_node.PageSize = value
	}
	if value, ok := _c.mutation.SortField(); ok {
		_spec.SetField(financefeeledgerpreference.FieldSortField, field.TypeString, value)
		_node.SortField = &value
	}
	if value, ok := _c.mutation.SortDirection(); ok {
		_spec.SetField(financefeeledgerpreference.FieldSortDirection, field.TypeEnum, value)
		_node.SortDirection = &value
	}
	if value, ok := _c.mutation.RowColors(); ok {
		_spec.SetField(financefeeledgerpreference.FieldRowColors, field.TypeJSON, value)
		_node.RowColors = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(financefeeledgerpreference.FieldVersion, field.TypeUint64, value)
		_node.Version = value
	}
	if nodes := _c.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   financefeeledgerpreference.OrganizationTable,
			Columns: []string{financefeeledgerpreference.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrganizationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   financefeeledgerpreference.UserTable,
			Columns: []string{financefeeledgerpreference.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FinanceFeeLedgerPreferenceCreateBulk is the builder for creating many FinanceFeeLedgerPreference entities in bulk.
type FinanceFeeLedgerPreferenceCreateBulk struct {
	config
	err      error
	builders []*FinanceFeeLedgerPreferenceCreate
}

// Save creates the FinanceFeeLedgerPreference entities in the database.
func (_c *FinanceFeeLedgerPreferenceCreateBulk) Save(ctx context.Context) ([]*FinanceFeeLedgerPreference, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FinanceFeeLedgerPreference, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FinanceFeeLedgerPreferenceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FinanceFeeLedgerPreferenceCreateBulk) SaveX(ctx context.Context) []*FinanceFeeLedgerPreference {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FinanceFeeLedgerPreferenceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FinanceFeeLedgerPreferenceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
