// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/financebillenterprisetag"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/predicate"
)

// FinanceBillEnterpriseTagUpdate is the builder for updating FinanceBillEnterpriseTag entities.
type FinanceBillEnterpriseTagUpdate struct {
	config
	hooks    []Hook
	mutation *FinanceBillEnterpriseTagMutation
}

// Where appends a list predicates to the FinanceBillEnterpriseTagUpdate builder.
func (_u *FinanceBillEnterpriseTagUpdate) Where(ps ...predicate.FinanceBillEnterpriseTag) *FinanceBillEnterpriseTagUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FinanceBillEnterpriseTagUpdate) SetUpdatedAt(v time.Time) *FinanceBillEnterpriseTagUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the FinanceBillEnterpriseTagMutation object of the builder.
func (_u *FinanceBillEnterpriseTagUpdate) Mutation() *FinanceBillEnterpriseTagMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FinanceBillEnterpriseTagUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FinanceBillEnterpriseTagUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FinanceBillEnterpriseTagUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FinanceBillEnterpriseTagUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FinanceBillEnterpriseTagUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := financebillenterprisetag.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FinanceBillEnterpriseTagUpdate) check() error {
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FinanceBillEnterpriseTag.organization"`)
	}
	if _u.mutation.FinanceBillCleared() && len(_u.mutation.FinanceBillIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FinanceBillEnterpriseTag.finance_bill"`)
	}
	if _u.mutation.TagResourceCleared() && len(_u.mutation.TagResourceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FinanceBillEnterpriseTag.tag_resource"`)
	}
	return nil
}

func (_u *FinanceBillEnterpriseTagUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(financebillenterprisetag.Table, financebillenterprisetag.Columns, sqlgraph.NewFieldSpec(financebillenterprisetag.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(financebillenterprisetag.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{financebillenterprisetag.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FinanceBillEnterpriseTagUpdateOne is the builder for updating a single FinanceBillEnterpriseTag entity.
type FinanceBillEnterpriseTagUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FinanceBillEnterpriseTagMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FinanceBillEnterpriseTagUpdateOne) SetUpdatedAt(v time.Time) *FinanceBillEnterpriseTagUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the FinanceBillEnterpriseTagMutation object of the builder.
func (_u *FinanceBillEnterpriseTagUpdateOne) Mutation() *FinanceBillEnterpriseTagMutation {
	return _u.mutation
}

// Where appends a list predicates to the FinanceBillEnterpriseTagUpdate builder.
func (_u *FinanceBillEnterpriseTagUpdateOne) Where(ps ...predicate.FinanceBillEnterpriseTag) *FinanceBillEnterpriseTagUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FinanceBillEnterpriseTagUpdateOne) Select(field string, fields ...string) *FinanceBillEnterpriseTagUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FinanceBillEnterpriseTag entity.
func (_u *FinanceBillEnterpriseTagUpdateOne) Save(ctx context.Context) (*FinanceBillEnterpriseTag, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FinanceBillEnterpriseTagUpdateOne) SaveX(ctx context.Context) *FinanceBillEnterpriseTag {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FinanceBillEnterpriseTagUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FinanceBillEnterpriseTagUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FinanceBillEnterpriseTagUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := financebillenterprisetag.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FinanceBillEnterpriseTagUpdateOne) check() error {
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FinanceBillEnterpriseTag.organization"`)
	}
	if _u.mutation.FinanceBillCleared() && len(_u.mutation.FinanceBillIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FinanceBillEnterpriseTag.finance_bill"`)
	}
	if _u.mutation.TagResourceCleared() && len(_u.mutation.TagResourceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FinanceBillEnterpriseTag.tag_resource"`)
	}
	return nil
}

func (_u *FinanceBillEnterpriseTagUpdateOne) sqlSave(ctx context.Context) (_node *FinanceBillEnterpriseTag, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(financebillenterprisetag.Table, financebillenterprisetag.Columns, sqlgraph.NewFieldSpec(financebillenterprisetag.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FinanceBillEnterpriseTag.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, financebillenterprisetag.FieldID)
		for _, f := range fields {
			if !financebillenterprisetag.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != financebillenterprisetag.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(financebillenterprisetag.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &FinanceBillEnterpriseTag{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{financebillenterprisetag.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
