// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/financecommission"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/financeverification"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/financeverificationallocation"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/predicate"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/user"
)

// FinanceVerificationUpdate is the builder for updating FinanceVerification entities.
type FinanceVerificationUpdate struct {
	config
	hooks    []Hook
	mutation *FinanceVerificationMutation
}

// Where appends a list predicates to the FinanceVerificationUpdate builder.
func (_u *FinanceVerificationUpdate) Where(ps ...predicate.FinanceVerification) *FinanceVerificationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FinanceVerificationUpdate) SetUpdatedAt(v time.Time) *FinanceVerificationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *FinanceVerificationUpdate) SetStatus(v financeverification.Status) *FinanceVerificationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *FinanceVerificationUpdate) SetNillableStatus(v *financeverification.Status) *FinanceVerificationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetNote sets the "note" field.
func (_u *FinanceVerificationUpdate) SetNote(v string) *FinanceVerificationUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *FinanceVerificationUpdate) SetNillableNote(v *string) *FinanceVerificationUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *FinanceVerificationUpdate) ClearNote() *FinanceVerificationUpdate {
	_u.mutation.ClearNote()
	return _u
}

// SetVersion sets the "version" field.
func (_u *FinanceVerificationUpdate) SetVersion(v uint64) *FinanceVerificationUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *FinanceVerificationUpdate) SetNillableVersion(v *uint64) *FinanceVerificationUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *FinanceVerificationUpdate) AddVersion(v int64) *FinanceVerificationUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetReversedAt sets the "reversed_at" field.
func (_u *FinanceVerificationUpdate) SetReversedAt(v time.Time) *FinanceVerificationUpdate {
	_u.mutation.SetReversedAt(v)
	return _u
}

// SetNillableReversedAt sets the "reversed_at" field if the given value is not nil.
func (_u *FinanceVerificationUpdate) SetNillableReversedAt(v *time.Time) *FinanceVerificationUpdate {
	if v != nil {
		_u.SetReversedAt(*v)
	}
	return _u
}

// ClearReversedAt clears the value of the "reversed_at" field.
func (_u *FinanceVerificationUpdate) ClearReversedAt() *FinanceVerificationUpdate {
	_u.mutation.ClearReversedAt()
	return _u
}

// SetReversedBy sets the "reversed_by" field.
func (_u *FinanceVerificationUpdate) SetReversedBy(v uuid.UUID) *FinanceVerificationUpdate {
	_u.mutation.SetReversedBy(v)
	return _u
}

// SetNillableReversedBy sets the "reversed_by" field if the given value is not nil.
func (_u *FinanceVerificationUpdate) SetNillableReversedBy(v *uuid.UUID) *FinanceVerificationUpdate {
	if v != nil {
		_u.SetReversedBy(*v)
	}
	return _u
}

// ClearReversedBy clears the value of the "reversed_by" field.
func (_u *FinanceVerificationUpdate) ClearReversedBy() *FinanceVerificationUpdate {
	_u.mutation.ClearReversedBy()
	return _u
}

// SetReversalReason sets the "reversal_reason" field.
func (_u *FinanceVerificationUpdate) SetReversalReason(v string) *FinanceVerificationUpdate {
	_u.mutation.SetReversalReason(v)
	return _u
}

// SetNillableReversalReason sets the "reversal_reason" field if the given value is not nil.
func (_u *FinanceVerificationUpdate) SetNillableReversalReason(v *string) *FinanceVerificationUpdate {
	if v != nil {
		_u.SetReversalReason(*v)
	}
	return _u
}

// ClearReversalReason clears the value of the "reversal_reason" field.
func (_u *FinanceVerificationUpdate) ClearReversalReason() *FinanceVerificationUpdate {
	_u.mutation.ClearReversalReason()
	return _u
}

// SetReversedByUserID sets the "reversed_by_user" edge to the User entity by ID.
func (_u *FinanceVerificationUpdate) SetReversedByUserID(id uuid.UUID) *FinanceVerificationUpdate {
	_u.mutation.SetReversedByUserID(id)
	return _u
}

// SetNillableReversedByUserID sets the "reversed_by_user" edge to the User entity by ID if the given value is not nil.
func (_u *FinanceVerificationUpdate) SetNillableReversedByUserID(id *uuid.UUID) *FinanceVerificationUpdate {
	if id != nil {
		_u = _u.SetReversedByUserID(*id)
	}
	return _u
}

// SetReversedByUser sets the "reversed_by_user" edge to the User entity.
func (_u *FinanceVerificationUpdate) SetReversedByUser(v *User) *FinanceVerificationUpdate {
	return _u.SetReversedByUserID(v.ID)
}

// AddAllocationIDs adds the "allocations" edge to the FinanceVerificationAllocation entity by IDs.
func (_u *FinanceVerificationUpdate) AddAllocationIDs(ids ...uuid.UUID) *FinanceVerificationUpdate {
	_u.mutation.AddAllocationIDs(ids...)
	return _u
}

// AddAllocations adds the "allocations" edges to the FinanceVerificationAllocation entity.
func (_u *FinanceVerificationUpdate) AddAllocations(v ...*FinanceVerificationAllocation) *FinanceVerificationUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAllocationIDs(ids...)
}

// AddCommissionIDs adds the "commissions" edge to the FinanceCommission entity by IDs.
func (_u *FinanceVerificationUpdate) AddCommissionIDs(ids ...uuid.UUID) *FinanceVerificationUpdate {
	_u.mutation.AddCommissionIDs(ids...)
	return _u
}

// AddCommissions adds the "commissions" edges to the FinanceCommission entity.
func (_u *FinanceVerificationUpdate) AddCommissions(v ...*FinanceCommission) *FinanceVerificationUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCommissionIDs(ids...)
}

// Mutation returns the FinanceVerificationMutation object of the builder.
func (_u *FinanceVerificationUpdate) Mutation() *FinanceVerificationMutation {
	return _u.mutation
}

// ClearReversedByUser clears the "reversed_by_user" edge to the User entity.
func (_u *FinanceVerificationUpdate) ClearReversedByUser() *FinanceVerificationUpdate {
	_u.mutation.ClearReversedByUser()
	return _u
}

// ClearAllocations clears all "allocations" edges to the FinanceVerificationAllocation entity.
func (_u *FinanceVerificationUpdate) ClearAllocations() *FinanceVerificationUpdate {
	_u.mutation.ClearAllocations()
	return _u
}

// RemoveAllocationIDs removes the "allocations" edge to FinanceVerificationAllocation entities by IDs.
func (_u *FinanceVerificationUpdate) RemoveAllocationIDs(ids ...uuid.UUID) *FinanceVerificationUpdate {
	_u.mutation.RemoveAllocationIDs(ids...)
	return _u
}

// RemoveAllocations removes "allocations" edges to FinanceVerificationAllocation entities.
func (_u *FinanceVerificationUpdate) RemoveAllocations(v ...*FinanceVerificationAllocation) *FinanceVerificationUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAllocationIDs(ids...)
}

// ClearCommissions clears all "commissions" edges to the FinanceCommission entity.
func (_u *FinanceVerificationUpdate) ClearCommissions() *FinanceVerificationUpdate {
	_u.mutation.ClearCommissions()
	return _u
}

// RemoveCommissionIDs removes the "commissions" edge to FinanceCommission entities by IDs.
func (_u *FinanceVerificationUpdate) RemoveCommissionIDs(ids ...uuid.UUID) *FinanceVerificationUpdate {
	_u.mutation.RemoveCommissionIDs(ids...)
	return _u
}

// RemoveCommissions removes "commissions" edges to FinanceCommission entities.
func (_u *FinanceVerificationUpdate) RemoveCommissions(v ...*FinanceCommission) *FinanceVerificationUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCommissionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FinanceVerificationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FinanceVerificationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FinanceVerificationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FinanceVerificationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FinanceVerificationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := financeverification.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FinanceVerificationUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := financeverification.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "FinanceVerification.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Note(); ok {
		if err := financeverification.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "FinanceVerification.note": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReversalReason(); ok {
		if err := financeverification.ReversalReasonValidator(v); err != nil {
			return &ValidationError{Name: "reversal_reason", err: fmt.Errorf(`ent: validator failed for field "FinanceVerification.reversal_reason": %w`, err)}
		}
	}
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FinanceVerification.organization"`)
	}
	if _u.mutation.SettlementPartyCleared() && len(_u.mutation.SettlementPartyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FinanceVerification.settlement_party"`)
	}
	return nil
}

func (_u *FinanceVerificationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(financeverification.Table, financeverification.Columns, sqlgraph.NewFieldSpec(financeverification.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(financeverification.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(financeverification.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.ExchangeRateSettingIDCleared() {
		_spec.ClearField(financeverification.FieldExchangeRateSettingID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(financeverification.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(financeverification.FieldNote, field.TypeString)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(financeverification.FieldVersion, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(financeverification.FieldVersion, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.ReversedAt(); ok {
		_spec.SetField(financeverification.FieldReversedAt, field.TypeTime, value)
	}
	if _u.mutation.ReversedAtCleared() {
		_spec.ClearField(financeverification.FieldReversedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReversalReason(); ok {
		_spec.SetField(financeverification.FieldReversalReason, field.TypeString, value)
	}
	if _u.mutation.ReversalReasonCleared() {
		_spec.ClearField(financeverification.FieldReversalReason, field.TypeString)
	}
	if _u.mutation.ReversedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   financeverification.ReversedByUserTable,
			Columns: []string{financeverification.ReversedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReversedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   financeverification.ReversedByUserTable,
			Columns: []string{financeverification.ReversedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AllocationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   financeverification.AllocationsTable,
			Columns: []string{financeverification.AllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(financeverificationallocation.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAllocationsIDs(); len(nodes) > 0 && !_u.mutation.AllocationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   financeverification.AllocationsTable,
			Columns: []string{financeverification.AllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(financeverificationallocation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AllocationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   financeverification.AllocationsTable,
			Columns: []string{financeverification.AllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(financeverificationallocation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CommissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   financeverification.CommissionsTable,
			Columns: []string{financeverification.CommissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(financecommission.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCommissionsIDs(); len(nodes) > 0 && !_u.mutation.CommissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   financeverification.CommissionsTable,
			Columns: []string{financeverification.CommissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(financecommission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CommissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   financeverification.CommissionsTable,
			Columns: []string{financeverification.CommissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(financecommission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{financeverification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FinanceVerificationUpdateOne is the builder for updating a single FinanceVerification entity.
type FinanceVerificationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FinanceVerificationMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FinanceVerificationUpdateOne) SetUpdatedAt(v time.Time) *FinanceVerificationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *FinanceVerificationUpdateOne) SetStatus(v financeverification.Status) *FinanceVerificationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *FinanceVerificationUpdateOne) SetNillableStatus(v *financeverification.Status) *FinanceVerificationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetNote sets the "note" field.
func (_u *FinanceVerificationUpdateOne) SetNote(v string) *FinanceVerificationUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *FinanceVerificationUpdateOne) SetNillableNote(v *string) *FinanceVerificationUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *FinanceVerificationUpdateOne) ClearNote() *FinanceVerificationUpdateOne {
	_u.mutation.ClearNote()
	return _u
}

// SetVersion sets the "version" field.
func (_u *FinanceVerificationUpdateOne) SetVersion(v uint64) *FinanceVerificationUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *FinanceVerificationUpdateOne) SetNillableVersion(v *uint64) *FinanceVerificationUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *FinanceVerificationUpdateOne) AddVersion(v int64) *FinanceVerificationUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetReversedAt sets the "reversed_at" field.
func (_u *FinanceVerificationUpdateOne) SetReversedAt(v time.Time) *FinanceVerificationUpdateOne {
	_u.mutation.SetReversedAt(v)
	return _u
}

// SetNillableReversedAt sets the "reversed_at" field if the given value is not nil.
func (_u *FinanceVerificationUpdateOne) SetNillableReversedAt(v *time.Time) *FinanceVerificationUpdateOne {
	if v != nil {
		_u.SetReversedAt(*v)
	}
	return _u
}

// ClearReversedAt clears the value of the "reversed_at" field.
func (_u *FinanceVerificationUpdateOne) ClearReversedAt() *FinanceVerificationUpdateOne {
	_u.mutation.ClearReversedAt()
	return _u
}

// SetReversedBy sets the "reversed_by" field.
func (_u *FinanceVerificationUpdateOne) SetReversedBy(v uuid.UUID) *FinanceVerificationUpdateOne {
	_u.mutation.SetReversedBy(v)
	return _u
}

// SetNillableReversedBy sets the "reversed_by" field if the given value is not nil.
func (_u *FinanceVerificationUpdateOne) SetNillableReversedBy(v *uuid.UUID) *FinanceVerificationUpdateOne {
	if v != nil {
		_u.SetReversedBy(*v)
	}
	return _u
}

// ClearReversedBy clears the value of the "reversed_by" field.
func (_u *FinanceVerificationUpdateOne) ClearReversedBy() *FinanceVerificationUpdateOne {
	_u.mutation.ClearReversedBy()
	return _u
}

// SetReversalReason sets the "reversal_reason" field.
func (_u *FinanceVerificationUpdateOne) SetReversalReason(v string) *FinanceVerificationUpdateOne {
	_u.mutation.SetReversalReason(v)
	return _u
}

// SetNillableReversalReason sets the "reversal_reason" field if the given value is not nil.
func (_u *FinanceVerificationUpdateOne) SetNillableReversalReason(v *string) *FinanceVerificationUpdateOne {
	if v != nil {
		_u.SetReversalReason(*v)
	}
	return _u
}

// ClearReversalReason clears the value of the "reversal_reason" field.
func (_u *FinanceVerificationUpdateOne) ClearReversalReason() *FinanceVerificationUpdateOne {
	_u.mutation.ClearReversalReason()
	return _u
}

// SetReversedByUserID sets the "reversed_by_user" edge to the User entity by ID.
func (_u *FinanceVerificationUpdateOne) SetReversedByUserID(id uuid.UUID) *FinanceVerificationUpdateOne {
	_u.mutation.SetReversedByUserID(id)
	return _u
}

// SetNillableReversedByUserID sets the "reversed_by_user" edge to the User entity by ID if the given value is not nil.
func (_u *FinanceVerificationUpdateOne) SetNillableReversedByUserID(id *uuid.UUID) *FinanceVerificationUpdateOne {
	if id != nil {
		_u = _u.SetReversedByUserID(*id)
	}
	return _u
}

// SetReversedByUser sets the "reversed_by_user" edge to the User entity.
func (_u *FinanceVerificationUpdateOne) SetReversedByUser(v *User) *FinanceVerificationUpdateOne {
	return _u.SetReversedByUserID(v.ID)
}

// AddAllocationIDs adds the "allocations" edge to the FinanceVerificationAllocation entity by IDs.
func (_u *FinanceVerificationUpdateOne) AddAllocationIDs(ids ...uuid.UUID) *FinanceVerificationUpdateOne {
	_u.mutation.AddAllocationIDs(ids...)
	return _u
}

// AddAllocations adds the "allocations" edges to the FinanceVerificationAllocation entity.
func (_u *FinanceVerificationUpdateOne) AddAllocations(v ...*FinanceVerificationAllocation) *FinanceVerificationUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAllocationIDs(ids...)
}

// AddCommissionIDs adds the "commissions" edge to the FinanceCommission entity by IDs.
func (_u *FinanceVerificationUpdateOne) AddCommissionIDs(ids ...uuid.UUID) *FinanceVerificationUpdateOne {
	_u.mutation.AddCommissionIDs(ids...)
	return _u
}

// AddCommissions adds the "commissions" edges to the FinanceCommission entity.
func (_u *FinanceVerificationUpdateOne) AddCommissions(v ...*FinanceCommission) *FinanceVerificationUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCommissionIDs(ids...)
}

// Mutation returns the FinanceVerificationMutation object of the builder.
func (_u *FinanceVerificationUpdateOne) Mutation() *FinanceVerificationMutation {
	return _u.mutation
}

// ClearReversedByUser clears the "reversed_by_user" edge to the User entity.
func (_u *FinanceVerificationUpdateOne) ClearReversedByUser() *FinanceVerificationUpdateOne {
	_u.mutation.ClearReversedByUser()
	return _u
}

// ClearAllocations clears all "allocations" edges to the FinanceVerificationAllocation entity.
func (_u *FinanceVerificationUpdateOne) ClearAllocations() *FinanceVerificationUpdateOne {
	_u.mutation.ClearAllocations()
	return _u
}

// RemoveAllocationIDs removes the "allocations" edge to FinanceVerificationAllocation entities by IDs.
func (_u *FinanceVerificationUpdateOne) RemoveAllocationIDs(ids ...uuid.UUID) *FinanceVerificationUpdateOne {
	_u.mutation.RemoveAllocationIDs(ids...)
	return _u
}

// RemoveAllocations removes "allocations" edges to FinanceVerificationAllocation entities.
func (_u *FinanceVerificationUpdateOne) RemoveAllocations(v ...*FinanceVerificationAllocation) *FinanceVerificationUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAllocationIDs(ids...)
}

// ClearCommissions clears all "commissions" edges to the FinanceCommission entity.
func (_u *FinanceVerificationUpdateOne) ClearCommissions() *FinanceVerificationUpdateOne {
	_u.mutation.ClearCommissions()
	return _u
}

// RemoveCommissionIDs removes the "commissions" edge to FinanceCommission entities by IDs.
func (_u *FinanceVerificationUpdateOne) RemoveCommissionIDs(ids ...uuid.UUID) *FinanceVerificationUpdateOne {
	_u.mutation.RemoveCommissionIDs(ids...)
	return _u
}

// RemoveCommissions removes "commissions" edges to FinanceCommission entities.
func (_u *FinanceVerificationUpdateOne) RemoveCommissions(v ...*FinanceCommission) *FinanceVerificationUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCommissionIDs(ids...)
}

// Where appends a list predicates to the FinanceVerificationUpdate builder.
func (_u *FinanceVerificationUpdateOne) Where(ps ...predicate.FinanceVerification) *FinanceVerificationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FinanceVerificationUpdateOne) Select(field string, fields ...string) *FinanceVerificationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FinanceVerification entity.
func (_u *FinanceVerificationUpdateOne) Save(ctx context.Context) (*FinanceVerification, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FinanceVerificationUpdateOne) SaveX(ctx context.Context) *FinanceVerification {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FinanceVerificationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FinanceVerificationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FinanceVerificationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := financeverification.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FinanceVerificationUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := financeverification.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "FinanceVerification.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Note(); ok {
		if err := financeverification.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "FinanceVerification.note": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReversalReason(); ok {
		if err := financeverification.ReversalReasonValidator(v); err != nil {
			return &ValidationError{Name: "reversal_reason", err: fmt.Errorf(`ent: validator failed for field "FinanceVerification.reversal_reason": %w`, err)}
		}
	}
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FinanceVerification.organization"`)
	}
	if _u.mutation.SettlementPartyCleared() && len(_u.mutation.SettlementPartyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FinanceVerification.settlement_party"`)
	}
	return nil
}

func (_u *FinanceVerificationUpdateOne) sqlSave(ctx context.Context) (_node *FinanceVerification, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(financeverification.Table, financeverification.Columns, sqlgraph.NewFieldSpec(financeverification.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FinanceVerification.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, financeverification.FieldID)
		for _, f := range fields {
			if !financeverification.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != financeverification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(financeverification.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(financeverification.FieldStatus, field.TypeEnum, value)
	}
	if _u.mutation.ExchangeRateSettingIDCleared() {
		_spec.ClearField(financeverification.FieldExchangeRateSettingID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(financeverification.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(financeverification.FieldNote, field.TypeString)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(financeverification.FieldVersion, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(financeverification.FieldVersion, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.ReversedAt(); ok {
		_spec.SetField(financeverification.FieldReversedAt, field.TypeTime, value)
	}
	if _u.mutation.ReversedAtCleared() {
		_spec.ClearField(financeverification.FieldReversedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReversalReason(); ok {
		_spec.SetField(financeverification.FieldReversalReason, field.TypeString, value)
	}
	if _u.mutation.ReversalReasonCleared() {
		_spec.ClearField(financeverification.FieldReversalReason, field.TypeString)
	}
	if _u.mutation.ReversedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   financeverification.ReversedByUserTable,
			Columns: []string{financeverification.ReversedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReversedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   financeverification.ReversedByUserTable,
			Columns: []string{financeverification.ReversedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AllocationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   financeverification.AllocationsTable,
			Columns: []string{financeverification.AllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(financeverificationallocation.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAllocationsIDs(); len(nodes) > 0 && !_u.mutation.AllocationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   financeverification.AllocationsTable,
			Columns: []string{financeverification.AllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(financeverificationallocation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AllocationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   financeverification.AllocationsTable,
			Columns: []string{financeverification.AllocationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(financeverificationallocation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CommissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   financeverification.CommissionsTable,
			Columns: []string{financeverification.CommissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(financecommission.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCommissionsIDs(); len(nodes) > 0 && !_u.mutation.CommissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   financeverification.CommissionsTable,
			Columns: []string{financeverification.CommissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(financecommission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CommissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   financeverification.CommissionsTable,
			Columns: []string{financeverification.CommissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(financecommission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &FinanceVerification{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{financeverification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
