// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/financecommission"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/financecommissionadjustment"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/order"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/organization"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/user"
)

// FinanceCommissionAdjustmentCreate is the builder for creating a FinanceCommissionAdjustment entity.
type FinanceCommissionAdjustmentCreate struct {
	config
	mutation *FinanceCommissionAdjustmentMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *FinanceCommissionAdjustmentCreate) SetCreatedAt(v time.Time) *FinanceCommissionAdjustmentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FinanceCommissionAdjustmentCreate) SetNillableCreatedAt(v *time.Time) *FinanceCommissionAdjustmentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *FinanceCommissionAdjustmentCreate) SetUpdatedAt(v time.Time) *FinanceCommissionAdjustmentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *FinanceCommissionAdjustmentCreate) SetNillableUpdatedAt(v *time.Time) *FinanceCommissionAdjustmentCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetOrganizationID sets the "organization_id" field.
func (_c *FinanceCommissionAdjustmentCreate) SetOrganizationID(v uuid.UUID) *FinanceCommissionAdjustmentCreate {
	_c.mutation.SetOrganizationID(v)
	return _c
}

// SetCommissionID sets the "commission_id" field.
func (_c *FinanceCommissionAdjustmentCreate) SetCommissionID(v uuid.UUID) *FinanceCommissionAdjustmentCreate {
	_c.mutation.SetCommissionID(v)
	return _c
}

// SetOrderID sets the "order_id" field.
func (_c *FinanceCommissionAdjustmentCreate) SetOrderID(v uuid.UUID) *FinanceCommissionAdjustmentCreate {
	_c.mutation.SetOrderID(v)
	return _c
}

// SetAdjustmentNo sets the "adjustment_no" field.
func (_c *FinanceCommissionAdjustmentCreate) SetAdjustmentNo(v string) *FinanceCommissionAdjustmentCreate {
	_c.mutation.SetAdjustmentNo(v)
	return _c
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_c *FinanceCommissionAdjustmentCreate) SetIdempotencyKey(v string) *FinanceCommissionAdjustmentCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetCommissionNo sets the "commission_no" field.
func (_c *FinanceCommissionAdjustmentCreate) SetCommissionNo(v string) *FinanceCommissionAdjustmentCreate {
	_c.mutation.SetCommissionNo(v)
	return _c
}

// SetOrderNo sets the "order_no" field.
func (_c *FinanceCommissionAdjustmentCreate) SetOrderNo(v string) *FinanceCommissionAdjustmentCreate {
	_c.mutation.SetOrderNo(v)
	return _c
}

// SetEmployeeID sets the "employee_id" field.
func (_c *FinanceCommissionAdjustmentCreate) SetEmployeeID(v uuid.UUID) *FinanceCommissionAdjustmentCreate {
	_c.mutation.SetEmployeeID(v)
	return _c
}

// SetEmployeeName sets the "employee_name" field.
func (_c *FinanceCommissionAdjustmentCreate) SetEmployeeName(v string) *FinanceCommissionAdjustmentCreate {
	_c.mutation.SetEmployeeName(v)
	return _c
}

// SetDirection sets the "direction" field.
func (_c *FinanceCommissionAdjustmentCreate) SetDirection(v financecommissionadjustment.Direction) *FinanceCommissionAdjustmentCreate {
	_c.mutation.SetDirection(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *FinanceCommissionAdjustmentCreate) SetStatus(v financecommissionadjustment.Status) *FinanceCommissionAdjustmentCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *FinanceCommissionAdjustmentCreate) SetNillableStatus(v *financecommissionadjustment.Status) *FinanceCommissionAdjustmentCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetBaseCurrency sets the "base_currency" field.
func (_c *FinanceCommissionAdjustmentCreate) SetBaseCurrency(v string) *FinanceCommissionAdjustmentCreate {
	_c.mutation.SetBaseCurrency(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *FinanceCommissionAdjustmentCreate) SetAmount(v string) *FinanceCommissionAdjustmentCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetReason sets the "reason" field.
func (_c *FinanceCommissionAdjustmentCreate) SetReason(v string) *FinanceCommissionAdjustmentCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNote sets the "note" field.
func (_c *FinanceCommissionAdjustmentCreate) SetNote(v string) *FinanceCommissionAdjustmentCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *FinanceCommissionAdjustmentCreate) SetNillableNote(v *string) *FinanceCommissionAdjustmentCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetVersion sets the "version" field.
func (_c *FinanceCommissionAdjustmentCreate) SetVersion(v uint64) *FinanceCommissionAdjustmentCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *FinanceCommissionAdjustmentCreate) SetNillableVersion(v *uint64) *FinanceCommissionAdjustmentCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetConfirmedAt sets the "confirmed_at" field.
func (_c *FinanceCommissionAdjustmentCreate) SetConfirmedAt(v time.Time) *FinanceCommissionAdjustmentCreate {
	_c.mutation.SetConfirmedAt(v)
	return _c
}

// SetNillableConfirmedAt sets the "confirmed_at" field if the given value is not nil.
func (_c *FinanceCommissionAdjustmentCreate) SetNillableConfirmedAt(v *time.Time) *FinanceCommissionAdjustmentCreate {
	if v != nil {
		_c.SetConfirmedAt(*v)
	}
	return _c
}

// SetConfirmedBy sets the "confirmed_by" field.
func (_c *FinanceCommissionAdjustmentCreate) SetConfirmedBy(v uuid.UUID) *FinanceCommissionAdjustmentCreate {
	_c.mutation.SetConfirmedBy(v)
	return _c
}

// SetNillableConfirmedBy sets the "confirmed_by" field if the given value is not nil.
func (_c *FinanceCommissionAdjustmentCreate) SetNillableConfirmedBy(v *uuid.UUID) *FinanceCommissionAdjustmentCreate {
	if v != nil {
		_c.SetConfirmedBy(*v)
	}
	return _c
}

// SetPaidAt sets the "paid_at" field.
func (_c *FinanceCommissionAdjustmentCreate) SetPaidAt(v time.Time) *FinanceCommissionAdjustmentCreate {
	_c.mutation.SetPaidAt(v)
	return _c
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_c *FinanceCommissionAdjustmentCreate) SetNillablePaidAt(v *time.Time) *FinanceCommissionAdjustmentCreate {
	if v != nil {
		_c.SetPaidAt(*v)
	}
	return _c
}

// SetPaidBy sets the "paid_by" field.
func (_c *FinanceCommissionAdjustmentCreate) SetPaidBy(v uuid.UUID) *FinanceCommissionAdjustmentCreate {
	_c.mutation.SetPaidBy(v)
	return _c
}

// SetNillablePaidBy sets the "paid_by" field if the given value is not nil.
func (_c *FinanceCommissionAdjustmentCreate) SetNillablePaidBy(v *uuid.UUID) *FinanceCommissionAdjustmentCreate {
	if v != nil {
		_c.SetPaidBy(*v)
	}
	return _c
}

// SetCancelledAt sets the "cancelled_at" field.
func (_c *FinanceCommissionAdjustmentCreate) SetCancelledAt(v time.Time) *FinanceCommissionAdjustmentCreate {
	_c.mutation.SetCancelledAt(v)
	return _c
}

// SetNillableCancelledAt sets the "cancelled_at" field if the given value is not nil.
func (_c *FinanceCommissionAdjustmentCreate) SetNillableCancelledAt(v *time.Time) *FinanceCommissionAdjustmentCreate {
	if v != nil {
		_c.SetCancelledAt(*v)
	}
	return _c
}

// SetCancelledBy sets the "cancelled_by" field.
func (_c *FinanceCommissionAdjustmentCreate) SetCancelledBy(v uuid.UUID) *FinanceCommissionAdjustmentCreate {
	_c.mutation.SetCancelledBy(v)
	return _c
}

// SetNillableCancelledBy sets the "cancelled_by" field if the given value is not nil.
func (_c *FinanceCommissionAdjustmentCreate) SetNillableCancelledBy(v *uuid.UUID) *FinanceCommissionAdjustmentCreate {
	if v != nil {
		_c.SetCancelledBy(*v)
	}
	return _c
}

// SetCancellationReason sets the "cancellation_reason" field.
func (_c *FinanceCommissionAdjustmentCreate) SetCancellationReason(v string) *FinanceCommissionAdjustmentCreate {
	_c.mutation.SetCancellationReason(v)
	return _c
}

// SetNillableCancellationReason sets the "cancellation_reason" field if the given value is not nil.
func (_c *FinanceCommissionAdjustmentCreate) SetNillableCancellationReason(v *string) *FinanceCommissionAdjustmentCreate {
	if v != nil {
		_c.SetCancellationReason(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *FinanceCommissionAdjustmentCreate) SetID(v uuid.UUID) *FinanceCommissionAdjustmentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *FinanceCommissionAdjustmentCreate) SetNillableID(v *uuid.UUID) *FinanceCommissionAdjustmentCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_c *FinanceCommissionAdjustmentCreate) SetOrganization(v *Organization) *FinanceCommissionAdjustmentCreate {
	return _c.SetOrganizationID(v.ID)
}

// SetCommission sets the "commission" edge to the FinanceCommission entity.
func (_c *FinanceCommissionAdjustmentCreate) SetCommission(v *FinanceCommission) *FinanceCommissionAdjustmentCreate {
	return _c.SetCommissionID(v.ID)
}

// SetOrder sets the "order" edge to the Order entity.
func (_c *FinanceCommissionAdjustmentCreate) SetOrder(v *Order) *FinanceCommissionAdjustmentCreate {
	return _c.SetOrderID(v.ID)
}

// SetEmployee sets the "employee" edge to the User entity.
func (_c *FinanceCommissionAdjustmentCreate) SetEmployee(v *User) *FinanceCommissionAdjustmentCreate {
	return _c.SetEmployeeID(v.ID)
}

// SetConfirmedByUserID sets the "confirmed_by_user" edge to the User entity by ID.
func (_c *FinanceCommissionAdjustmentCreate) SetConfirmedByUserID(id uuid.UUID) *FinanceCommissionAdjustmentCreate {
	_c.mutation.SetConfirmedByUserID(id)
	return _c
}

// SetNillableConfirmedByUserID sets the "confirmed_by_user" edge to the User entity by ID if the given value is not nil.
func (_c *FinanceCommissionAdjustmentCreate) SetNillableConfirmedByUserID(id *uuid.UUID) *FinanceCommissionAdjustmentCreate {
	if id != nil {
		_c = _c.SetConfirmedByUserID(*id)
	}
	return _c
}

// SetConfirmedByUser sets the "confirmed_by_user" edge to the User entity.
func (_c *FinanceCommissionAdjustmentCreate) SetConfirmedByUser(v *User) *FinanceCommissionAdjustmentCreate {
	return _c.SetConfirmedByUserID(v.ID)
}

// SetPaidByUserID sets the "paid_by_user" edge to the User entity by ID.
func (_c *FinanceCommissionAdjustmentCreate) SetPaidByUserID(id uuid.UUID) *FinanceCommissionAdjustmentCreate {
	_c.mutation.SetPaidByUserID(id)
	return _c
}

// SetNillablePaidByUserID sets the "paid_by_user" edge to the User entity by ID if the given value is not nil.
func (_c *FinanceCommissionAdjustmentCreate) SetNillablePaidByUserID(id *uuid.UUID) *FinanceCommissionAdjustmentCreate {
	if id != nil {
		_c = _c.SetPaidByUserID(*id)
	}
	return _c
}

// SetPaidByUser sets the "paid_by_user" edge to the User entity.
func (_c *FinanceCommissionAdjustmentCreate) SetPaidByUser(v *User) *FinanceCommissionAdjustmentCreate {
	return _c.SetPaidByUserID(v.ID)
}

// SetCancelledByUserID sets the "cancelled_by_user" edge to the User entity by ID.
func (_c *FinanceCommissionAdjustmentCreate) SetCancelledByUserID(id uuid.UUID) *FinanceCommissionAdjustmentCreate {
	_c.mutation.SetCancelledByUserID(id)
	return _c
}

// SetNillableCancelledByUserID sets the "cancelled_by_user" edge to the User entity by ID if the given value is not nil.
func (_c *FinanceCommissionAdjustmentCreate) SetNillableCancelledByUserID(id *uuid.UUID) *FinanceCommissionAdjustmentCreate {
	if id != nil {
		_c = _c.SetCancelledByUserID(*id)
	}
	return _c
}

// SetCancelledByUser sets the "cancelled_by_user" edge to the User entity.
func (_c *FinanceCommissionAdjustmentCreate) SetCancelledByUser(v *User) *FinanceCommissionAdjustmentCreate {
	return _c.SetCancelledByUserID(v.ID)
}

// Mutation returns the FinanceCommissionAdjustmentMutation object of the builder.
func (_c *FinanceCommissionAdjustmentCreate) Mutation() *FinanceCommissionAdjustmentMutation {
	return _c.mutation
}

// Save creates the FinanceCommissionAdjustment in the database.
func (_c *FinanceCommissionAdjustmentCreate) Save(ctx context.Context) (*FinanceCommissionAdjustment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FinanceCommissionAdjustmentCreate) SaveX(ctx context.Context) *FinanceCommissionAdjustment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FinanceCommissionAdjustmentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FinanceCommissionAdjustmentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FinanceCommissionAdjustmentCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := financecommissionadjustment.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := financecommissionadjustment.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := financecommissionadjustment.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := financecommissionadjustment.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := financecommissionadjustment.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FinanceCommissionAdjustmentCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "FinanceCommissionAdjustment.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "FinanceCommissionAdjustment.updated_at"`)}
	}
	if _, ok := _c.mutation.OrganizationID(); !ok {
		return &ValidationError{Name: "organization_id", err: errors.New(`ent: missing required field "FinanceCommissionAdjustment.organization_id"`)}
	}
	if _, ok := _c.mutation.CommissionID(); !ok {
		return &ValidationError{Name: "commission_id", err: errors.New(`ent: missing required field "FinanceCommissionAdjustment.commission_id"`)}
	}
	if _, ok := _c.mutation.OrderID(); !ok {
		return &ValidationError{Name: "order_id", err: errors.New(`ent: missing required field "FinanceCommissionAdjustment.order_id"`)}
	}
	if _, ok := _c.mutation.AdjustmentNo(); !ok {
		return &ValidationError{Name: "adjustment_no", err: errors.New(`ent: missing required field "FinanceCommissionAdjustment.adjustment_no"`)}
	}
	if v, ok := _c.mutation.AdjustmentNo(); ok {
		if err := financecommissionadjustment.AdjustmentNoValidator(v); err != nil {
			return &ValidationError{Name: "adjustment_no", err: fmt.Errorf(`ent: validator failed for field "FinanceCommissionAdjustment.adjustment_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IdempotencyKey(); !ok {
		return &ValidationError{Name: "idempotency_key", err: errors.New(`ent: missing required field "FinanceCommissionAdjustment.idempotency_key"`)}
	}
	if v, ok := _c.mutation.IdempotencyKey(); ok {
		if err := financecommissionadjustment.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "FinanceCommissionAdjustment.idempotency_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CommissionNo(); !ok {
		return &ValidationError{Name: "commission_no", err: errors.New(`ent: missing required field "FinanceCommissionAdjustment.commission_no"`)}
	}
	if v, ok := _c.mutation.CommissionNo(); ok {
		if err := financecommissionadjustment.CommissionNoValidator(v); err != nil {
			return &ValidationError{Name: "commission_no", err: fmt.Errorf(`ent: validator failed for field "FinanceCommissionAdjustment.commission_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.OrderNo(); !ok {
		return &ValidationError{Name: "order_no", err: errors.New(`ent: missing required field "FinanceCommissionAdjustment.order_no"`)}
	}
	if v, ok := _c.mutation.OrderNo(); ok {
		if err := financecommissionadjustment.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "FinanceCommissionAdjustment.order_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EmployeeID(); !ok {
		return &ValidationError{Name: "employee_id", err: errors.New(`ent: missing required field "FinanceCommissionAdjustment.employee_id"`)}
	}
	if _, ok := _c.mutation.EmployeeName(); !ok {
		return &ValidationError{Name: "employee_name", err: errors.New(`ent: missing required field "FinanceCommissionAdjustment.employee_name"`)}
	}
	if v, ok := _c.mutation.EmployeeName(); ok {
		if err := financecommissionadjustment.EmployeeNameValidator(v); err != nil {
			return &ValidationError{Name: "employee_name", err: fmt.Errorf(`ent: validator failed for field "FinanceCommissionAdjustment.employee_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Direction(); !ok {
		return &ValidationError{Name: "direction", err: errors.New(`ent: missing required field "FinanceCommissionAdjustment.direction"`)}
	}
	if v, ok := _c.mutation.Direction(); ok {
		if err := financecommissionadjustment.DirectionValidator(v); err != nil {
			return &ValidationError{Name: "direction", err: fmt.Errorf(`ent: validator failed for field "FinanceCommissionAdjustment.direction": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "FinanceCommissionAdjustment.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := financecommissionadjustment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "FinanceCommissionAdjustment.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BaseCurrency(); !ok {
		return &ValidationError{Name: "base_currency", err: errors.New(`ent: missing required field "FinanceCommissionAdjustment.base_currency"`)}
	}
	if v, ok := _c.mutation.BaseCurrency(); ok {
		if err := financecommissionadjustment.BaseCurrencyValidator(v); err != nil {
			return &ValidationError{Name: "base_currency", err: fmt.Errorf(`ent: validator failed for field "FinanceCommissionAdjustment.base_currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "FinanceCommissionAdjustment.amount"`)}
	}
	if _, ok := _c.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "FinanceCommissionAdjustment.reason"`)}
	}
	if v, ok := _c.mutation.Reason(); ok {
		if err := financecommissionadjustment.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "FinanceCommissionAdjustment.reason": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Note(); ok {
		if err := financecommissionadjustment.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "FinanceCommissionAdjustment.note": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "FinanceCommissionAdjustment.version"`)}
	}
	if v, ok := _c.mutation.CancellationReason(); ok {
		if err := financecommissionadjustment.CancellationReasonValidator(v); err != nil {
			return &ValidationError{Name: "cancellation_reason", err: fmt.Errorf(`ent: validator failed for field "FinanceCommissionAdjustment.cancellation_reason": %w`, err)}
		}
	}
	if len(_c.mutation.OrganizationIDs()) == 0 {
		return &ValidationError{Name: "organization", err: errors.New(`ent: missing required edge "FinanceCommissionAdjustment.organization"`)}
	}
	if len(_c.mutation.CommissionIDs()) == 0 {
		return &ValidationError{Name: "commission", err: errors.New(`ent: missing required edge "FinanceCommissionAdjustment.commission"`)}
	}
	if len(_c.mutation.OrderIDs()) == 0 {
		return &ValidationError{Name: "order", err: errors.New(`ent: missing required edge "FinanceCommissionAdjustment.order"`)}
	}
	if len(_c.mutation.EmployeeIDs()) == 0 {
		return &ValidationError{Name: "employee", err: errors.New(`ent: missing required edge "FinanceCommissionAdjustment.employee"`)}
	}
	return nil
}

func (_c *FinanceCommissionAdjustmentCreate) sqlSave(ctx context.Context) (*FinanceCommissionAdjustment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FinanceCommissionAdjustmentCreate) createSpec() (*FinanceCommissionAdjustment, *sqlgraph.CreateSpec) {
	var (
		_node = &FinanceCommissionAdjustment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(financecommissionadjustment.Table, sqlgraph.NewFieldSpec(financecommissionadjustment.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(financecommissionadjustment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(financecommissionadjustment.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.AdjustmentNo(); ok {
		_spec.SetField(financecommissionadjustment.FieldAdjustmentNo, field.TypeString, value)
		_node.AdjustmentNo = value
	}
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(financecommissionadjustment.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = value
	}
	if value, ok := _c.mutation.CommissionNo(); ok {
		_spec.SetField(financecommissionadjustment.FieldCommissionNo, field.TypeString, value)
		_node.CommissionNo = value
	}
	if value, ok := _c.mutation.OrderNo(); ok {
		_spec.SetField(financecommissionadjustment.FieldOrderNo, field.TypeString, value)
		_node.OrderNo = value
	}
	if value, ok := _c.mutation.EmployeeName(); ok {
		_spec.SetField(financecommissionadjustment.FieldEmployeeName, field.TypeString, value)
		_node.EmployeeName = value
	}
	if value, ok := _c.mutation.Direction(); ok {
		_spec.SetField(financecommissionadjustment.FieldDirection, field.TypeEnum, value)
		_node.Direction = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(financecommissionadjustment.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.BaseCurrency(); ok {
		_spec.SetField(financecommissionadjustment.FieldBaseCurrency, field.TypeString, value)
		_node.BaseCurrency = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(financecommissionadjustment.FieldAmount, field.TypeString, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(financecommissionadjustment.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(financecommissionadjustment.FieldNote, field.TypeString, value)
		_node.Note = &value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(financecommissionadjustment.FieldVersion, field.TypeUint64, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.ConfirmedAt(); ok {
		_spec.SetField(financecommissionadjustment.FieldConfirmedAt, field.TypeTime, value)
		_node.ConfirmedAt = &value
	}
	if value, ok := _c.mutation.PaidAt(); ok {
		_spec.SetField(financecommissionadjustment.FieldPaidAt, field.TypeTime, value)
		_node.PaidAt = &value
	}
	if value, ok := _c.mutation.CancelledAt(); ok {
		_spec.SetField(financecommissionadjustment.FieldCancelledAt, field.TypeTime, value)
		_node.CancelledAt = &value
	}
	if value, ok := _c.mutation.CancellationReason(); ok {
		_spec.SetField(financecommissionadjustment.FieldCancellationReason, field.TypeString, value)
		_node.CancellationReason = &value
	}
	if nodes := _c.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   financecommissionadjustment.OrganizationTable,
			Columns: []string{financecommissionadjustment.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrganizationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CommissionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   financecommissionadjustment.CommissionTable,
			Columns: []string{financecommissionadjustment.CommissionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(financecommission.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CommissionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   financecommissionadjustment.OrderTable,
			Columns: []string{financecommissionadjustment.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrderID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EmployeeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   financecommissionadjustment.EmployeeTable,
			Columns: []string{financecommissionadjustment.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EmployeeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ConfirmedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   financecommissionadjustment.ConfirmedByUserTable,
			Columns: []string{financecommissionadjustment.ConfirmedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ConfirmedBy = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PaidByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   financecommissionadjustment.PaidByUserTable,
			Columns: []string{financecommissionadjustment.PaidByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PaidBy = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CancelledByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   financecommissionadjustment.CancelledByUserTable,
			Columns: []string{financecommissionadjustment.CancelledByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CancelledBy = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FinanceCommissionAdjustmentCreateBulk is the builder for creating many FinanceCommissionAdjustment entities in bulk.
type FinanceCommissionAdjustmentCreateBulk struct {
	config
	err      error
	builders []*FinanceCommissionAdjustmentCreate
}

// Save creates the FinanceCommissionAdjustment entities in the database.
func (_c *FinanceCommissionAdjustmentCreateBulk) Save(ctx context.Context) ([]*FinanceCommissionAdjustment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FinanceCommissionAdjustment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FinanceCommissionAdjustmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FinanceCommissionAdjustmentCreateBulk) SaveX(ctx context.Context) []*FinanceCommissionAdjustment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FinanceCommissionAdjustmentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FinanceCommissionAdjustmentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
