// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/numberrule"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/numbersequence"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/organization"
)

// NumberRuleCreate is the builder for creating a NumberRule entity.
type NumberRuleCreate struct {
	config
	mutation *NumberRuleMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *NumberRuleCreate) SetCreatedAt(v time.Time) *NumberRuleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *NumberRuleCreate) SetNillableCreatedAt(v *time.Time) *NumberRuleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *NumberRuleCreate) SetUpdatedAt(v time.Time) *NumberRuleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *NumberRuleCreate) SetNillableUpdatedAt(v *time.Time) *NumberRuleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetOrganizationID sets the "organization_id" field.
func (_c *NumberRuleCreate) SetOrganizationID(v uuid.UUID) *NumberRuleCreate {
	_c.mutation.SetOrganizationID(v)
	return _c
}

// SetDocumentType sets the "document_type" field.
func (_c *NumberRuleCreate) SetDocumentType(v numberrule.DocumentType) *NumberRuleCreate {
	_c.mutation.SetDocumentType(v)
	return _c
}

// SetPrefix sets the "prefix" field.
func (_c *NumberRuleCreate) SetPrefix(v string) *NumberRuleCreate {
	_c.mutation.SetPrefix(v)
	return _c
}

// SetDateFormat sets the "date_format" field.
func (_c *NumberRuleCreate) SetDateFormat(v numberrule.DateFormat) *NumberRuleCreate {
	_c.mutation.SetDateFormat(v)
	return _c
}

// SetNillableDateFormat sets the "date_format" field if the given value is not nil.
func (_c *NumberRuleCreate) SetNillableDateFormat(v *numberrule.DateFormat) *NumberRuleCreate {
	if v != nil {
		_c.SetDateFormat(*v)
	}
	return _c
}

// SetSequenceLength sets the "sequence_length" field.
func (_c *NumberRuleCreate) SetSequenceLength(v int) *NumberRuleCreate {
	_c.mutation.SetSequenceLength(v)
	return _c
}

// SetNillableSequenceLength sets the "sequence_length" field if the given value is not nil.
func (_c *NumberRuleCreate) SetNillableSequenceLength(v *int) *NumberRuleCreate {
	if v != nil {
		_c.SetSequenceLength(*v)
	}
	return _c
}

// SetResetPolicy sets the "reset_policy" field.
func (_c *NumberRuleCreate) SetResetPolicy(v numberrule.ResetPolicy) *NumberRuleCreate {
	_c.mutation.SetResetPolicy(v)
	return _c
}

// SetNillableResetPolicy sets the "reset_policy" field if the given value is not nil.
func (_c *NumberRuleCreate) SetNillableResetPolicy(v *numberrule.ResetPolicy) *NumberRuleCreate {
	if v != nil {
		_c.SetResetPolicy(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *NumberRuleCreate) SetEnabled(v bool) *NumberRuleCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *NumberRuleCreate) SetNillableEnabled(v *bool) *NumberRuleCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *NumberRuleCreate) SetID(v uuid.UUID) *NumberRuleCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *NumberRuleCreate) SetNillableID(v *uuid.UUID) *NumberRuleCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetOrganization sets the "organization" edge to the Organization entity.
func (_c *NumberRuleCreate) SetOrganization(v *Organization) *NumberRuleCreate {
	return _c.SetOrganizationID(v.ID)
}

// AddSequenceIDs adds the "sequences" edge to the NumberSequence entity by IDs.
func (_c *NumberRuleCreate) AddSequenceIDs(ids ...uuid.UUID) *NumberRuleCreate {
	_c.mutation.AddSequenceIDs(ids...)
	return _c
}

// AddSequences adds the "sequences" edges to the NumberSequence entity.
func (_c *NumberRuleCreate) AddSequences(v ...*NumberSequence) *NumberRuleCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSequenceIDs(ids...)
}

// Mutation returns the NumberRuleMutation object of the builder.
func (_c *NumberRuleCreate) Mutation() *NumberRuleMutation {
	return _c.mutation
}

// Save creates the NumberRule in the database.
func (_c *NumberRuleCreate) Save(ctx context.Context) (*NumberRule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NumberRuleCreate) SaveX(ctx context.Context) *NumberRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NumberRuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NumberRuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NumberRuleCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := numberrule.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := numberrule.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DateFormat(); !ok {
		v := numberrule.DefaultDateFormat
		_c.mutation.SetDateFormat(v)
	}
	if _, ok := _c.mutation.SequenceLength(); !ok {
		v := numberrule.DefaultSequenceLength
		_c.mutation.SetSequenceLength(v)
	}
	if _, ok := _c.mutation.ResetPolicy(); !ok {
		v := numberrule.DefaultResetPolicy
		_c.mutation.SetResetPolicy(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := numberrule.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := numberrule.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NumberRuleCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "NumberRule.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "NumberRule.updated_at"`)}
	}
	if _, ok := _c.mutation.OrganizationID(); !ok {
		return &ValidationError{Name: "organization_id", err: errors.New(`ent: missing required field "NumberRule.organization_id"`)}
	}
	if _, ok := _c.mutation.DocumentType(); !ok {
		return &ValidationError{Name: "document_type", err: errors.New(`ent: missing required field "NumberRule.document_type"`)}
	}
	if v, ok := _c.mutation.DocumentType(); ok {
		if err := numberrule.DocumentTypeValidator(v); err != nil {
			return &ValidationError{Name: "document_type", err: fmt.Errorf(`ent: validator failed for field "NumberRule.document_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Prefix(); !ok {
		return &ValidationError{Name: "prefix", err: errors.New(`ent: missing required field "NumberRule.prefix"`)}
	}
	if v, ok := _c.mutation.Prefix(); ok {
		if err := numberrule.PrefixValidator(v); err != nil {
			return &ValidationError{Name: "prefix", err: fmt.Errorf(`ent: validator failed for field "NumberRule.prefix": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DateFormat(); !ok {
		return &ValidationError{Name: "date_format", err: errors.New(`ent: missing required field "NumberRule.date_format"`)}
	}
	if v, ok := _c.mutation.DateFormat(); ok {
		if err := numberrule.DateFormatValidator(v); err != nil {
			return &ValidationError{Name: "date_format", err: fmt.Errorf(`ent: validator failed for field "NumberRule.date_format": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SequenceLength(); !ok {
		return &ValidationError{Name: "sequence_length", err: errors.New(`ent: missing required field "NumberRule.sequence_length"`)}
	}
	if v, ok := _c.mutation.SequenceLength(); ok {
		if err := numberrule.SequenceLengthValidator(v); err != nil {
			return &ValidationError{Name: "sequence_length", err: fmt.Errorf(`ent: validator failed for field "NumberRule.sequence_length": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ResetPolicy(); !ok {
		return &ValidationError{Name: "reset_policy", err: errors.New(`ent: missing required field "NumberRule.reset_policy"`)}
	}
	if v, ok := _c.mutation.ResetPolicy(); ok {
		if err := numberrule.ResetPolicyValidator(v); err != nil {
			return &ValidationError{Name: "reset_policy", err: fmt.Errorf(`ent: validator failed for field "NumberRule.reset_policy": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "NumberRule.enabled"`)}
	}
	if len(_c.mutation.OrganizationIDs()) == 0 {
		return &ValidationError{Name: "organization", err: errors.New(`ent: missing required edge "NumberRule.organization"`)}
	}
	return nil
}

func (_c *NumberRuleCreate) sqlSave(ctx context.Context) (*NumberRule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NumberRuleCreate) createSpec() (*NumberRule, *sqlgraph.CreateSpec) {
	var (
		_node = &NumberRule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(numberrule.Table, sqlgraph.NewFieldSpec(numberrule.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(numberrule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(numberrule.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DocumentType(); ok {
		_spec.SetField(numberrule.FieldDocumentType, field.TypeEnum, value)
		_node.DocumentType = value
	}
	if value, ok := _c.mutation.Prefix(); ok {
		_spec.SetField(numberrule.FieldPrefix, field.TypeString, value)
		_node.Prefix = value
	}
	if value, ok := _c.mutation.DateFormat(); ok {
		_spec.SetField(numberrule.FieldDateFormat, field.TypeEnum, value)
		_node.DateFormat = value
	}
	if value, ok := _c.mutation.SequenceLength(); ok {
		_spec.SetField(numberrule.FieldSequenceLength, field.TypeInt, value)
		_node.SequenceLength = value
	}
	if value, ok := _c.mutation.ResetPolicy(); ok {
		_spec.SetField(numberrule.FieldResetPolicy, field.TypeEnum, value)
		_node.ResetPolicy = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(numberrule.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if nodes := _c.mutation.OrganizationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   numberrule.OrganizationTable,
			Columns: []string{numberrule.OrganizationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrganizationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SequencesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   numberrule.SequencesTable,
			Columns: []string{numberrule.SequencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(numbersequence.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// NumberRuleCreateBulk is the builder for creating many NumberRule entities in bulk.
type NumberRuleCreateBulk struct {
	config
	err      error
	builders []*NumberRuleCreate
}

// Save creates the NumberRule entities in the database.
func (_c *NumberRuleCreateBulk) Save(ctx context.Context) ([]*NumberRule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NumberRule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NumberRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NumberRuleCreateBulk) SaveX(ctx context.Context) []*NumberRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NumberRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NumberRuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
