// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/order"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/orderreleasepod"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/ordershippingdocument"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/predicate"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/seahousebill"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/seamasterbill"
)

// OrderReleasePodUpdate is the builder for updating OrderReleasePod entities.
type OrderReleasePodUpdate struct {
	config
	hooks    []Hook
	mutation *OrderReleasePodMutation
}

// Where appends a list predicates to the OrderReleasePodUpdate builder.
func (_u *OrderReleasePodUpdate) Where(ps ...predicate.OrderReleasePod) *OrderReleasePodUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrderReleasePodUpdate) SetUpdatedAt(v time.Time) *OrderReleasePodUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *OrderReleasePodUpdate) SetOrderID(v uuid.UUID) *OrderReleasePodUpdate {
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *OrderReleasePodUpdate) SetNillableOrderID(v *uuid.UUID) *OrderReleasePodUpdate {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// SetShippingDocumentID sets the "shipping_document_id" field.
func (_u *OrderReleasePodUpdate) SetShippingDocumentID(v uuid.UUID) *OrderReleasePodUpdate {
	_u.mutation.SetShippingDocumentID(v)
	return _u
}

// SetNillableShippingDocumentID sets the "shipping_document_id" field if the given value is not nil.
func (_u *OrderReleasePodUpdate) SetNillableShippingDocumentID(v *uuid.UUID) *OrderReleasePodUpdate {
	if v != nil {
		_u.SetShippingDocumentID(*v)
	}
	return _u
}

// ClearShippingDocumentID clears the value of the "shipping_document_id" field.
func (_u *OrderReleasePodUpdate) ClearShippingDocumentID() *OrderReleasePodUpdate {
	_u.mutation.ClearShippingDocumentID()
	return _u
}

// SetSeaMasterBillID sets the "sea_master_bill_id" field.
func (_u *OrderReleasePodUpdate) SetSeaMasterBillID(v uuid.UUID) *OrderReleasePodUpdate {
	_u.mutation.SetSeaMasterBillID(v)
	return _u
}

// SetNillableSeaMasterBillID sets the "sea_master_bill_id" field if the given value is not nil.
func (_u *OrderReleasePodUpdate) SetNillableSeaMasterBillID(v *uuid.UUID) *OrderReleasePodUpdate {
	if v != nil {
		_u.SetSeaMasterBillID(*v)
	}
	return _u
}

// ClearSeaMasterBillID clears the value of the "sea_master_bill_id" field.
func (_u *OrderReleasePodUpdate) ClearSeaMasterBillID() *OrderReleasePodUpdate {
	_u.mutation.ClearSeaMasterBillID()
	return _u
}

// SetSeaHouseBillID sets the "sea_house_bill_id" field.
func (_u *OrderReleasePodUpdate) SetSeaHouseBillID(v uuid.UUID) *OrderReleasePodUpdate {
	_u.mutation.SetSeaHouseBillID(v)
	return _u
}

// SetNillableSeaHouseBillID sets the "sea_house_bill_id" field if the given value is not nil.
func (_u *OrderReleasePodUpdate) SetNillableSeaHouseBillID(v *uuid.UUID) *OrderReleasePodUpdate {
	if v != nil {
		_u.SetSeaHouseBillID(*v)
	}
	return _u
}

// ClearSeaHouseBillID clears the value of the "sea_house_bill_id" field.
func (_u *OrderReleasePodUpdate) ClearSeaHouseBillID() *OrderReleasePodUpdate {
	_u.mutation.ClearSeaHouseBillID()
	return _u
}

// SetReleaseNo sets the "release_no" field.
func (_u *OrderReleasePodUpdate) SetReleaseNo(v string) *OrderReleasePodUpdate {
	_u.mutation.SetReleaseNo(v)
	return _u
}

// SetNillableReleaseNo sets the "release_no" field if the given value is not nil.
func (_u *OrderReleasePodUpdate) SetNillableReleaseNo(v *string) *OrderReleasePodUpdate {
	if v != nil {
		_u.SetReleaseNo(*v)
	}
	return _u
}

// ClearReleaseNo clears the value of the "release_no" field.
func (_u *OrderReleasePodUpdate) ClearReleaseNo() *OrderReleasePodUpdate {
	_u.mutation.ClearReleaseNo()
	return _u
}

// SetPodNo sets the "pod_no" field.
func (_u *OrderReleasePodUpdate) SetPodNo(v string) *OrderReleasePodUpdate {
	_u.mutation.SetPodNo(v)
	return _u
}

// SetNillablePodNo sets the "pod_no" field if the given value is not nil.
func (_u *OrderReleasePodUpdate) SetNillablePodNo(v *string) *OrderReleasePodUpdate {
	if v != nil {
		_u.SetPodNo(*v)
	}
	return _u
}

// ClearPodNo clears the value of the "pod_no" field.
func (_u *OrderReleasePodUpdate) ClearPodNo() *OrderReleasePodUpdate {
	_u.mutation.ClearPodNo()
	return _u
}

// SetStatus sets the "status" field.
func (_u *OrderReleasePodUpdate) SetStatus(v orderreleasepod.Status) *OrderReleasePodUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OrderReleasePodUpdate) SetNillableStatus(v *orderreleasepod.Status) *OrderReleasePodUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSignedAt sets the "signed_at" field.
func (_u *OrderReleasePodUpdate) SetSignedAt(v time.Time) *OrderReleasePodUpdate {
	_u.mutation.SetSignedAt(v)
	return _u
}

// SetNillableSignedAt sets the "signed_at" field if the given value is not nil.
func (_u *OrderReleasePodUpdate) SetNillableSignedAt(v *time.Time) *OrderReleasePodUpdate {
	if v != nil {
		_u.SetSignedAt(*v)
	}
	return _u
}

// ClearSignedAt clears the value of the "signed_at" field.
func (_u *OrderReleasePodUpdate) ClearSignedAt() *OrderReleasePodUpdate {
	_u.mutation.ClearSignedAt()
	return _u
}

// SetSignedBy sets the "signed_by" field.
func (_u *OrderReleasePodUpdate) SetSignedBy(v uuid.UUID) *OrderReleasePodUpdate {
	_u.mutation.SetSignedBy(v)
	return _u
}

// SetNillableSignedBy sets the "signed_by" field if the given value is not nil.
func (_u *OrderReleasePodUpdate) SetNillableSignedBy(v *uuid.UUID) *OrderReleasePodUpdate {
	if v != nil {
		_u.SetSignedBy(*v)
	}
	return _u
}

// ClearSignedBy clears the value of the "signed_by" field.
func (_u *OrderReleasePodUpdate) ClearSignedBy() *OrderReleasePodUpdate {
	_u.mutation.ClearSignedBy()
	return _u
}

// SetNote sets the "note" field.
func (_u *OrderReleasePodUpdate) SetNote(v string) *OrderReleasePodUpdate {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *OrderReleasePodUpdate) SetNillableNote(v *string) *OrderReleasePodUpdate {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *OrderReleasePodUpdate) ClearNote() *OrderReleasePodUpdate {
	_u.mutation.ClearNote()
	return _u
}

// SetOrder sets the "order" edge to the Order entity.
func (_u *OrderReleasePodUpdate) SetOrder(v *Order) *OrderReleasePodUpdate {
	return _u.SetOrderID(v.ID)
}

// SetShippingDocument sets the "shipping_document" edge to the OrderShippingDocument entity.
func (_u *OrderReleasePodUpdate) SetShippingDocument(v *OrderShippingDocument) *OrderReleasePodUpdate {
	return _u.SetShippingDocumentID(v.ID)
}

// SetSeaMasterBill sets the "sea_master_bill" edge to the SeaMasterBill entity.
func (_u *OrderReleasePodUpdate) SetSeaMasterBill(v *SeaMasterBill) *OrderReleasePodUpdate {
	return _u.SetSeaMasterBillID(v.ID)
}

// SetSeaHouseBill sets the "sea_house_bill" edge to the SeaHouseBill entity.
func (_u *OrderReleasePodUpdate) SetSeaHouseBill(v *SeaHouseBill) *OrderReleasePodUpdate {
	return _u.SetSeaHouseBillID(v.ID)
}

// Mutation returns the OrderReleasePodMutation object of the builder.
func (_u *OrderReleasePodUpdate) Mutation() *OrderReleasePodMutation {
	return _u.mutation
}

// ClearOrder clears the "order" edge to the Order entity.
func (_u *OrderReleasePodUpdate) ClearOrder() *OrderReleasePodUpdate {
	_u.mutation.ClearOrder()
	return _u
}

// ClearShippingDocument clears the "shipping_document" edge to the OrderShippingDocument entity.
func (_u *OrderReleasePodUpdate) ClearShippingDocument() *OrderReleasePodUpdate {
	_u.mutation.ClearShippingDocument()
	return _u
}

// ClearSeaMasterBill clears the "sea_master_bill" edge to the SeaMasterBill entity.
func (_u *OrderReleasePodUpdate) ClearSeaMasterBill() *OrderReleasePodUpdate {
	_u.mutation.ClearSeaMasterBill()
	return _u
}

// ClearSeaHouseBill clears the "sea_house_bill" edge to the SeaHouseBill entity.
func (_u *OrderReleasePodUpdate) ClearSeaHouseBill() *OrderReleasePodUpdate {
	_u.mutation.ClearSeaHouseBill()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OrderReleasePodUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderReleasePodUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OrderReleasePodUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderReleasePodUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OrderReleasePodUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := orderreleasepod.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderReleasePodUpdate) check() error {
	if v, ok := _u.mutation.ReleaseNo(); ok {
		if err := orderreleasepod.ReleaseNoValidator(v); err != nil {
			return &ValidationError{Name: "release_no", err: fmt.Errorf(`ent: validator failed for field "OrderReleasePod.release_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PodNo(); ok {
		if err := orderreleasepod.PodNoValidator(v); err != nil {
			return &ValidationError{Name: "pod_no", err: fmt.Errorf(`ent: validator failed for field "OrderReleasePod.pod_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := orderreleasepod.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OrderReleasePod.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Note(); ok {
		if err := orderreleasepod.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "OrderReleasePod.note": %w`, err)}
		}
	}
	if _u.mutation.OrderCleared() && len(_u.mutation.OrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrderReleasePod.order"`)
	}
	return nil
}

func (_u *OrderReleasePodUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(orderreleasepod.Table, orderreleasepod.Columns, sqlgraph.NewFieldSpec(orderreleasepod.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(orderreleasepod.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ReleaseNo(); ok {
		_spec.SetField(orderreleasepod.FieldReleaseNo, field.TypeString, value)
	}
	if _u.mutation.ReleaseNoCleared() {
		_spec.ClearField(orderreleasepod.FieldReleaseNo, field.TypeString)
	}
	if value, ok := _u.mutation.PodNo(); ok {
		_spec.SetField(orderreleasepod.FieldPodNo, field.TypeString, value)
	}
	if _u.mutation.PodNoCleared() {
		_spec.ClearField(orderreleasepod.FieldPodNo, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(orderreleasepod.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SignedAt(); ok {
		_spec.SetField(orderreleasepod.FieldSignedAt, field.TypeTime, value)
	}
	if _u.mutation.SignedAtCleared() {
		_spec.ClearField(orderreleasepod.FieldSignedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SignedBy(); ok {
		_spec.SetField(orderreleasepod.FieldSignedBy, field.TypeUUID, value)
	}
	if _u.mutation.SignedByCleared() {
		_spec.ClearField(orderreleasepod.FieldSignedBy, field.TypeUUID)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(orderreleasepod.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(orderreleasepod.FieldNote, field.TypeString)
	}
	if _u.mutation.OrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderreleasepod.OrderTable,
			Columns: []string{orderreleasepod.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderreleasepod.OrderTable,
			Columns: []string{orderreleasepod.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ShippingDocumentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderreleasepod.ShippingDocumentTable,
			Columns: []string{orderreleasepod.ShippingDocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ordershippingdocument.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ShippingDocumentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderreleasepod.ShippingDocumentTable,
			Columns: []string{orderreleasepod.ShippingDocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ordershippingdocument.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SeaMasterBillCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderreleasepod.SeaMasterBillTable,
			Columns: []string{orderreleasepod.SeaMasterBillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seamasterbill.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SeaMasterBillIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderreleasepod.SeaMasterBillTable,
			Columns: []string{orderreleasepod.SeaMasterBillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seamasterbill.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SeaHouseBillCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderreleasepod.SeaHouseBillTable,
			Columns: []string{orderreleasepod.SeaHouseBillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seahousebill.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SeaHouseBillIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderreleasepod.SeaHouseBillTable,
			Columns: []string{orderreleasepod.SeaHouseBillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seahousebill.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orderreleasepod.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OrderReleasePodUpdateOne is the builder for updating a single OrderReleasePod entity.
type OrderReleasePodUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrderReleasePodMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrderReleasePodUpdateOne) SetUpdatedAt(v time.Time) *OrderReleasePodUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *OrderReleasePodUpdateOne) SetOrderID(v uuid.UUID) *OrderReleasePodUpdateOne {
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *OrderReleasePodUpdateOne) SetNillableOrderID(v *uuid.UUID) *OrderReleasePodUpdateOne {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// SetShippingDocumentID sets the "shipping_document_id" field.
func (_u *OrderReleasePodUpdateOne) SetShippingDocumentID(v uuid.UUID) *OrderReleasePodUpdateOne {
	_u.mutation.SetShippingDocumentID(v)
	return _u
}

// SetNillableShippingDocumentID sets the "shipping_document_id" field if the given value is not nil.
func (_u *OrderReleasePodUpdateOne) SetNillableShippingDocumentID(v *uuid.UUID) *OrderReleasePodUpdateOne {
	if v != nil {
		_u.SetShippingDocumentID(*v)
	}
	return _u
}

// ClearShippingDocumentID clears the value of the "shipping_document_id" field.
func (_u *OrderReleasePodUpdateOne) ClearShippingDocumentID() *OrderReleasePodUpdateOne {
	_u.mutation.ClearShippingDocumentID()
	return _u
}

// SetSeaMasterBillID sets the "sea_master_bill_id" field.
func (_u *OrderReleasePodUpdateOne) SetSeaMasterBillID(v uuid.UUID) *OrderReleasePodUpdateOne {
	_u.mutation.SetSeaMasterBillID(v)
	return _u
}

// SetNillableSeaMasterBillID sets the "sea_master_bill_id" field if the given value is not nil.
func (_u *OrderReleasePodUpdateOne) SetNillableSeaMasterBillID(v *uuid.UUID) *OrderReleasePodUpdateOne {
	if v != nil {
		_u.SetSeaMasterBillID(*v)
	}
	return _u
}

// ClearSeaMasterBillID clears the value of the "sea_master_bill_id" field.
func (_u *OrderReleasePodUpdateOne) ClearSeaMasterBillID() *OrderReleasePodUpdateOne {
	_u.mutation.ClearSeaMasterBillID()
	return _u
}

// SetSeaHouseBillID sets the "sea_house_bill_id" field.
func (_u *OrderReleasePodUpdateOne) SetSeaHouseBillID(v uuid.UUID) *OrderReleasePodUpdateOne {
	_u.mutation.SetSeaHouseBillID(v)
	return _u
}

// SetNillableSeaHouseBillID sets the "sea_house_bill_id" field if the given value is not nil.
func (_u *OrderReleasePodUpdateOne) SetNillableSeaHouseBillID(v *uuid.UUID) *OrderReleasePodUpdateOne {
	if v != nil {
		_u.SetSeaHouseBillID(*v)
	}
	return _u
}

// ClearSeaHouseBillID clears the value of the "sea_house_bill_id" field.
func (_u *OrderReleasePodUpdateOne) ClearSeaHouseBillID() *OrderReleasePodUpdateOne {
	_u.mutation.ClearSeaHouseBillID()
	return _u
}

// SetReleaseNo sets the "release_no" field.
func (_u *OrderReleasePodUpdateOne) SetReleaseNo(v string) *OrderReleasePodUpdateOne {
	_u.mutation.SetReleaseNo(v)
	return _u
}

// SetNillableReleaseNo sets the "release_no" field if the given value is not nil.
func (_u *OrderReleasePodUpdateOne) SetNillableReleaseNo(v *string) *OrderReleasePodUpdateOne {
	if v != nil {
		_u.SetReleaseNo(*v)
	}
	return _u
}

// ClearReleaseNo clears the value of the "release_no" field.
func (_u *OrderReleasePodUpdateOne) ClearReleaseNo() *OrderReleasePodUpdateOne {
	_u.mutation.ClearReleaseNo()
	return _u
}

// SetPodNo sets the "pod_no" field.
func (_u *OrderReleasePodUpdateOne) SetPodNo(v string) *OrderReleasePodUpdateOne {
	_u.mutation.SetPodNo(v)
	return _u
}

// SetNillablePodNo sets the "pod_no" field if the given value is not nil.
func (_u *OrderReleasePodUpdateOne) SetNillablePodNo(v *string) *OrderReleasePodUpdateOne {
	if v != nil {
		_u.SetPodNo(*v)
	}
	return _u
}

// ClearPodNo clears the value of the "pod_no" field.
func (_u *OrderReleasePodUpdateOne) ClearPodNo() *OrderReleasePodUpdateOne {
	_u.mutation.ClearPodNo()
	return _u
}

// SetStatus sets the "status" field.
func (_u *OrderReleasePodUpdateOne) SetStatus(v orderreleasepod.Status) *OrderReleasePodUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OrderReleasePodUpdateOne) SetNillableStatus(v *orderreleasepod.Status) *OrderReleasePodUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSignedAt sets the "signed_at" field.
func (_u *OrderReleasePodUpdateOne) SetSignedAt(v time.Time) *OrderReleasePodUpdateOne {
	_u.mutation.SetSignedAt(v)
	return _u
}

// SetNillableSignedAt sets the "signed_at" field if the given value is not nil.
func (_u *OrderReleasePodUpdateOne) SetNillableSignedAt(v *time.Time) *OrderReleasePodUpdateOne {
	if v != nil {
		_u.SetSignedAt(*v)
	}
	return _u
}

// ClearSignedAt clears the value of the "signed_at" field.
func (_u *OrderReleasePodUpdateOne) ClearSignedAt() *OrderReleasePodUpdateOne {
	_u.mutation.ClearSignedAt()
	return _u
}

// SetSignedBy sets the "signed_by" field.
func (_u *OrderReleasePodUpdateOne) SetSignedBy(v uuid.UUID) *OrderReleasePodUpdateOne {
	_u.mutation.SetSignedBy(v)
	return _u
}

// SetNillableSignedBy sets the "signed_by" field if the given value is not nil.
func (_u *OrderReleasePodUpdateOne) SetNillableSignedBy(v *uuid.UUID) *OrderReleasePodUpdateOne {
	if v != nil {
		_u.SetSignedBy(*v)
	}
	return _u
}

// ClearSignedBy clears the value of the "signed_by" field.
func (_u *OrderReleasePodUpdateOne) ClearSignedBy() *OrderReleasePodUpdateOne {
	_u.mutation.ClearSignedBy()
	return _u
}

// SetNote sets the "note" field.
func (_u *OrderReleasePodUpdateOne) SetNote(v string) *OrderReleasePodUpdateOne {
	_u.mutation.SetNote(v)
	return _u
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_u *OrderReleasePodUpdateOne) SetNillableNote(v *string) *OrderReleasePodUpdateOne {
	if v != nil {
		_u.SetNote(*v)
	}
	return _u
}

// ClearNote clears the value of the "note" field.
func (_u *OrderReleasePodUpdateOne) ClearNote() *OrderReleasePodUpdateOne {
	_u.mutation.ClearNote()
	return _u
}

// SetOrder sets the "order" edge to the Order entity.
func (_u *OrderReleasePodUpdateOne) SetOrder(v *Order) *OrderReleasePodUpdateOne {
	return _u.SetOrderID(v.ID)
}

// SetShippingDocument sets the "shipping_document" edge to the OrderShippingDocument entity.
func (_u *OrderReleasePodUpdateOne) SetShippingDocument(v *OrderShippingDocument) *OrderReleasePodUpdateOne {
	return _u.SetShippingDocumentID(v.ID)
}

// SetSeaMasterBill sets the "sea_master_bill" edge to the SeaMasterBill entity.
func (_u *OrderReleasePodUpdateOne) SetSeaMasterBill(v *SeaMasterBill) *OrderReleasePodUpdateOne {
	return _u.SetSeaMasterBillID(v.ID)
}

// SetSeaHouseBill sets the "sea_house_bill" edge to the SeaHouseBill entity.
func (_u *OrderReleasePodUpdateOne) SetSeaHouseBill(v *SeaHouseBill) *OrderReleasePodUpdateOne {
	return _u.SetSeaHouseBillID(v.ID)
}

// Mutation returns the OrderReleasePodMutation object of the builder.
func (_u *OrderReleasePodUpdateOne) Mutation() *OrderReleasePodMutation {
	return _u.mutation
}

// ClearOrder clears the "order" edge to the Order entity.
func (_u *OrderReleasePodUpdateOne) ClearOrder() *OrderReleasePodUpdateOne {
	_u.mutation.ClearOrder()
	return _u
}

// ClearShippingDocument clears the "shipping_document" edge to the OrderShippingDocument entity.
func (_u *OrderReleasePodUpdateOne) ClearShippingDocument() *OrderReleasePodUpdateOne {
	_u.mutation.ClearShippingDocument()
	return _u
}

// ClearSeaMasterBill clears the "sea_master_bill" edge to the SeaMasterBill entity.
func (_u *OrderReleasePodUpdateOne) ClearSeaMasterBill() *OrderReleasePodUpdateOne {
	_u.mutation.ClearSeaMasterBill()
	return _u
}

// ClearSeaHouseBill clears the "sea_house_bill" edge to the SeaHouseBill entity.
func (_u *OrderReleasePodUpdateOne) ClearSeaHouseBill() *OrderReleasePodUpdateOne {
	_u.mutation.ClearSeaHouseBill()
	return _u
}

// Where appends a list predicates to the OrderReleasePodUpdate builder.
func (_u *OrderReleasePodUpdateOne) Where(ps ...predicate.OrderReleasePod) *OrderReleasePodUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OrderReleasePodUpdateOne) Select(field string, fields ...string) *OrderReleasePodUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OrderReleasePod entity.
func (_u *OrderReleasePodUpdateOne) Save(ctx context.Context) (*OrderReleasePod, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderReleasePodUpdateOne) SaveX(ctx context.Context) *OrderReleasePod {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OrderReleasePodUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderReleasePodUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OrderReleasePodUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := orderreleasepod.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderReleasePodUpdateOne) check() error {
	if v, ok := _u.mutation.ReleaseNo(); ok {
		if err := orderreleasepod.ReleaseNoValidator(v); err != nil {
			return &ValidationError{Name: "release_no", err: fmt.Errorf(`ent: validator failed for field "OrderReleasePod.release_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PodNo(); ok {
		if err := orderreleasepod.PodNoValidator(v); err != nil {
			return &ValidationError{Name: "pod_no", err: fmt.Errorf(`ent: validator failed for field "OrderReleasePod.pod_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := orderreleasepod.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OrderReleasePod.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Note(); ok {
		if err := orderreleasepod.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "OrderReleasePod.note": %w`, err)}
		}
	}
	if _u.mutation.OrderCleared() && len(_u.mutation.OrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrderReleasePod.order"`)
	}
	return nil
}

func (_u *OrderReleasePodUpdateOne) sqlSave(ctx context.Context) (_node *OrderReleasePod, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(orderreleasepod.Table, orderreleasepod.Columns, sqlgraph.NewFieldSpec(orderreleasepod.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OrderReleasePod.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, orderreleasepod.FieldID)
		for _, f := range fields {
			if !orderreleasepod.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != orderreleasepod.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(orderreleasepod.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ReleaseNo(); ok {
		_spec.SetField(orderreleasepod.FieldReleaseNo, field.TypeString, value)
	}
	if _u.mutation.ReleaseNoCleared() {
		_spec.ClearField(orderreleasepod.FieldReleaseNo, field.TypeString)
	}
	if value, ok := _u.mutation.PodNo(); ok {
		_spec.SetField(orderreleasepod.FieldPodNo, field.TypeString, value)
	}
	if _u.mutation.PodNoCleared() {
		_spec.ClearField(orderreleasepod.FieldPodNo, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(orderreleasepod.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SignedAt(); ok {
		_spec.SetField(orderreleasepod.FieldSignedAt, field.TypeTime, value)
	}
	if _u.mutation.SignedAtCleared() {
		_spec.ClearField(orderreleasepod.FieldSignedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SignedBy(); ok {
		_spec.SetField(orderreleasepod.FieldSignedBy, field.TypeUUID, value)
	}
	if _u.mutation.SignedByCleared() {
		_spec.ClearField(orderreleasepod.FieldSignedBy, field.TypeUUID)
	}
	if value, ok := _u.mutation.Note(); ok {
		_spec.SetField(orderreleasepod.FieldNote, field.TypeString, value)
	}
	if _u.mutation.NoteCleared() {
		_spec.ClearField(orderreleasepod.FieldNote, field.TypeString)
	}
	if _u.mutation.OrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderreleasepod.OrderTable,
			Columns: []string{orderreleasepod.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderreleasepod.OrderTable,
			Columns: []string{orderreleasepod.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ShippingDocumentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderreleasepod.ShippingDocumentTable,
			Columns: []string{orderreleasepod.ShippingDocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ordershippingdocument.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ShippingDocumentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderreleasepod.ShippingDocumentTable,
			Columns: []string{orderreleasepod.ShippingDocumentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ordershippingdocument.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SeaMasterBillCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderreleasepod.SeaMasterBillTable,
			Columns: []string{orderreleasepod.SeaMasterBillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seamasterbill.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SeaMasterBillIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderreleasepod.SeaMasterBillTable,
			Columns: []string{orderreleasepod.SeaMasterBillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seamasterbill.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SeaHouseBillCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderreleasepod.SeaHouseBillTable,
			Columns: []string{orderreleasepod.SeaHouseBillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seahousebill.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SeaHouseBillIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderreleasepod.SeaHouseBillTable,
			Columns: []string{orderreleasepod.SeaHouseBillColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seahousebill.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OrderReleasePod{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orderreleasepod.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
