// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/financecommissionadjustment"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/order"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/orderfee"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/orderfeesupplementrequest"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/organization"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/predicate"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/user"
)

// OrderFeeSupplementRequestQuery is the builder for querying OrderFeeSupplementRequest entities.
type OrderFeeSupplementRequestQuery struct {
	config
	ctx                       *QueryContext
	order                     []orderfeesupplementrequest.OrderOption
	inters                    []Interceptor
	predicates                []predicate.OrderFeeSupplementRequest
	withOrganization          *OrganizationQuery
	withOrder                 *OrderQuery
	withRequestedByUser       *UserQuery
	withDecidedByUser         *UserQuery
	withFees                  *OrderFeeQuery
	withCommissionAdjustments *FinanceCommissionAdjustmentQuery
	modifiers                 []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OrderFeeSupplementRequestQuery builder.
func (_q *OrderFeeSupplementRequestQuery) Where(ps ...predicate.OrderFeeSupplementRequest) *OrderFeeSupplementRequestQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *OrderFeeSupplementRequestQuery) Limit(limit int) *OrderFeeSupplementRequestQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *OrderFeeSupplementRequestQuery) Offset(offset int) *OrderFeeSupplementRequestQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *OrderFeeSupplementRequestQuery) Unique(unique bool) *OrderFeeSupplementRequestQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *OrderFeeSupplementRequestQuery) Order(o ...orderfeesupplementrequest.OrderOption) *OrderFeeSupplementRequestQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryOrganization chains the current query on the "organization" edge.
func (_q *OrderFeeSupplementRequestQuery) QueryOrganization() *OrganizationQuery {
	query := (&OrganizationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(orderfeesupplementrequest.Table, orderfeesupplementrequest.FieldID, selector),
			sqlgraph.To(organization.Table, organization.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, orderfeesupplementrequest.OrganizationTable, orderfeesupplementrequest.OrganizationColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOrder chains the current query on the "order" edge.
func (_q *OrderFeeSupplementRequestQuery) QueryOrder() *OrderQuery {
	query := (&OrderClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(orderfeesupplementrequest.Table, orderfeesupplementrequest.FieldID, selector),
			sqlgraph.To(order.Table, order.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, orderfeesupplementrequest.OrderTable, orderfeesupplementrequest.OrderColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRequestedByUser chains the current query on the "requested_by_user" edge.
func (_q *OrderFeeSupplementRequestQuery) QueryRequestedByUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(orderfeesupplementrequest.Table, orderfeesupplementrequest.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, orderfeesupplementrequest.RequestedByUserTable, orderfeesupplementrequest.RequestedByUserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDecidedByUser chains the current query on the "decided_by_user" edge.
func (_q *OrderFeeSupplementRequestQuery) QueryDecidedByUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(orderfeesupplementrequest.Table, orderfeesupplementrequest.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, orderfeesupplementrequest.DecidedByUserTable, orderfeesupplementrequest.DecidedByUserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFees chains the current query on the "fees" edge.
func (_q *OrderFeeSupplementRequestQuery) QueryFees() *OrderFeeQuery {
	query := (&OrderFeeClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(orderfeesupplementrequest.Table, orderfeesupplementrequest.FieldID, selector),
			sqlgraph.To(orderfee.Table, orderfee.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, orderfeesupplementrequest.FeesTable, orderfeesupplementrequest.FeesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCommissionAdjustments chains the current query on the "commission_adjustments" edge.
func (_q *OrderFeeSupplementRequestQuery) QueryCommissionAdjustments() *FinanceCommissionAdjustmentQuery {
	query := (&FinanceCommissionAdjustmentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(orderfeesupplementrequest.Table, orderfeesupplementrequest.FieldID, selector),
			sqlgraph.To(financecommissionadjustment.Table, financecommissionadjustment.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, orderfeesupplementrequest.CommissionAdjustmentsTable, orderfeesupplementrequest.CommissionAdjustmentsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first OrderFeeSupplementRequest entity from the query.
// Returns a *NotFoundError when no OrderFeeSupplementRequest was found.
func (_q *OrderFeeSupplementRequestQuery) First(ctx context.Context) (*OrderFeeSupplementRequest, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{orderfeesupplementrequest.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *OrderFeeSupplementRequestQuery) FirstX(ctx context.Context) *OrderFeeSupplementRequest {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first OrderFeeSupplementRequest ID from the query.
// Returns a *NotFoundError when no OrderFeeSupplementRequest ID was found.
func (_q *OrderFeeSupplementRequestQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{orderfeesupplementrequest.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *OrderFeeSupplementRequestQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single OrderFeeSupplementRequest entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one OrderFeeSupplementRequest entity is found.
// Returns a *NotFoundError when no OrderFeeSupplementRequest entities are found.
func (_q *OrderFeeSupplementRequestQuery) Only(ctx context.Context) (*OrderFeeSupplementRequest, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{orderfeesupplementrequest.Label}
	default:
		return nil, &NotSingularError{orderfeesupplementrequest.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *OrderFeeSupplementRequestQuery) OnlyX(ctx context.Context) *OrderFeeSupplementRequest {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only OrderFeeSupplementRequest ID in the query.
// Returns a *NotSingularError when more than one OrderFeeSupplementRequest ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *OrderFeeSupplementRequestQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{orderfeesupplementrequest.Label}
	default:
		err = &NotSingularError{orderfeesupplementrequest.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *OrderFeeSupplementRequestQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of OrderFeeSupplementRequests.
func (_q *OrderFeeSupplementRequestQuery) All(ctx context.Context) ([]*OrderFeeSupplementRequest, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*OrderFeeSupplementRequest, *OrderFeeSupplementRequestQuery]()
	return withInterceptors[[]*OrderFeeSupplementRequest](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *OrderFeeSupplementRequestQuery) AllX(ctx context.Context) []*OrderFeeSupplementRequest {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of OrderFeeSupplementRequest IDs.
func (_q *OrderFeeSupplementRequestQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(orderfeesupplementrequest.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *OrderFeeSupplementRequestQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *OrderFeeSupplementRequestQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*OrderFeeSupplementRequestQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *OrderFeeSupplementRequestQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *OrderFeeSupplementRequestQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *OrderFeeSupplementRequestQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OrderFeeSupplementRequestQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *OrderFeeSupplementRequestQuery) Clone() *OrderFeeSupplementRequestQuery {
	if _q == nil {
		return nil
	}
	return &OrderFeeSupplementRequestQuery{
		config:                    _q.config,
		ctx:                       _q.ctx.Clone(),
		order:                     append([]orderfeesupplementrequest.OrderOption{}, _q.order...),
		inters:                    append([]Interceptor{}, _q.inters...),
		predicates:                append([]predicate.OrderFeeSupplementRequest{}, _q.predicates...),
		withOrganization:          _q.withOrganization.Clone(),
		withOrder:                 _q.withOrder.Clone(),
		withRequestedByUser:       _q.withRequestedByUser.Clone(),
		withDecidedByUser:         _q.withDecidedByUser.Clone(),
		withFees:                  _q.withFees.Clone(),
		withCommissionAdjustments: _q.withCommissionAdjustments.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithOrganization tells the query-builder to eager-load the nodes that are connected to
// the "organization" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OrderFeeSupplementRequestQuery) WithOrganization(opts ...func(*OrganizationQuery)) *OrderFeeSupplementRequestQuery {
	query := (&OrganizationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOrganization = query
	return _q
}

// WithOrder tells the query-builder to eager-load the nodes that are connected to
// the "order" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OrderFeeSupplementRequestQuery) WithOrder(opts ...func(*OrderQuery)) *OrderFeeSupplementRequestQuery {
	query := (&OrderClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOrder = query
	return _q
}

// WithRequestedByUser tells the query-builder to eager-load the nodes that are connected to
// the "requested_by_user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OrderFeeSupplementRequestQuery) WithRequestedByUser(opts ...func(*UserQuery)) *OrderFeeSupplementRequestQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRequestedByUser = query
	return _q
}

// WithDecidedByUser tells the query-builder to eager-load the nodes that are connected to
// the "decided_by_user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OrderFeeSupplementRequestQuery) WithDecidedByUser(opts ...func(*UserQuery)) *OrderFeeSupplementRequestQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDecidedByUser = query
	return _q
}

// WithFees tells the query-builder to eager-load the nodes that are connected to
// the "fees" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OrderFeeSupplementRequestQuery) WithFees(opts ...func(*OrderFeeQuery)) *OrderFeeSupplementRequestQuery {
	query := (&OrderFeeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withFees = query
	return _q
}

// WithCommissionAdjustments tells the query-builder to eager-load the nodes that are connected to
// the "commission_adjustments" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OrderFeeSupplementRequestQuery) WithCommissionAdjustments(opts ...func(*FinanceCommissionAdjustmentQuery)) *OrderFeeSupplementRequestQuery {
	query := (&FinanceCommissionAdjustmentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCommissionAdjustments = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.OrderFeeSupplementRequest.Query().
//		GroupBy(orderfeesupplementrequest.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *OrderFeeSupplementRequestQuery) GroupBy(field string, fields ...string) *OrderFeeSupplementRequestGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &OrderFeeSupplementRequestGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = orderfeesupplementrequest.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.OrderFeeSupplementRequest.Query().
//		Select(orderfeesupplementrequest.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *OrderFeeSupplementRequestQuery) Select(fields ...string) *OrderFeeSupplementRequestSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &OrderFeeSupplementRequestSelect{OrderFeeSupplementRequestQuery: _q}
	sbuild.label = orderfeesupplementrequest.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a OrderFeeSupplementRequestSelect configured with the given aggregations.
func (_q *OrderFeeSupplementRequestQuery) Aggregate(fns ...AggregateFunc) *OrderFeeSupplementRequestSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *OrderFeeSupplementRequestQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !orderfeesupplementrequest.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *OrderFeeSupplementRequestQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*OrderFeeSupplementRequest, error) {
	var (
		nodes       = []*OrderFeeSupplementRequest{}
		_spec       = _q.querySpec()
		loadedTypes = [6]bool{
			_q.withOrganization != nil,
			_q.withOrder != nil,
			_q.withRequestedByUser != nil,
			_q.withDecidedByUser != nil,
			_q.withFees != nil,
			_q.withCommissionAdjustments != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*OrderFeeSupplementRequest).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &OrderFeeSupplementRequest{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withOrganization; query != nil {
		if err := _q.loadOrganization(ctx, query, nodes, nil,
			func(n *OrderFeeSupplementRequest, e *Organization) { n.Edges.Organization = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withOrder; query != nil {
		if err := _q.loadOrder(ctx, query, nodes, nil,
			func(n *OrderFeeSupplementRequest, e *Order) { n.Edges.Order = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRequestedByUser; query != nil {
		if err := _q.loadRequestedByUser(ctx, query, nodes, nil,
			func(n *OrderFeeSupplementRequest, e *User) { n.Edges.RequestedByUser = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withDecidedByUser; query != nil {
		if err := _q.loadDecidedByUser(ctx, query, nodes, nil,
			func(n *OrderFeeSupplementRequest, e *User) { n.Edges.DecidedByUser = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withFees; query != nil {
		if err := _q.loadFees(ctx, query, nodes,
			func(n *OrderFeeSupplementRequest) { n.Edges.Fees = []*OrderFee{} },
			func(n *OrderFeeSupplementRequest, e *OrderFee) { n.Edges.Fees = append(n.Edges.Fees, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCommissionAdjustments; query != nil {
		if err := _q.loadCommissionAdjustments(ctx, query, nodes,
			func(n *OrderFeeSupplementRequest) { n.Edges.CommissionAdjustments = []*FinanceCommissionAdjustment{} },
			func(n *OrderFeeSupplementRequest, e *FinanceCommissionAdjustment) {
				n.Edges.CommissionAdjustments = append(n.Edges.CommissionAdjustments, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *OrderFeeSupplementRequestQuery) loadOrganization(ctx context.Context, query *OrganizationQuery, nodes []*OrderFeeSupplementRequest, init func(*OrderFeeSupplementRequest), assign func(*OrderFeeSupplementRequest, *Organization)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*OrderFeeSupplementRequest)
	for i := range nodes {
		fk := nodes[i].OrganizationID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(organization.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "organization_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *OrderFeeSupplementRequestQuery) loadOrder(ctx context.Context, query *OrderQuery, nodes []*OrderFeeSupplementRequest, init func(*OrderFeeSupplementRequest), assign func(*OrderFeeSupplementRequest, *Order)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*OrderFeeSupplementRequest)
	for i := range nodes {
		fk := nodes[i].OrderID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(order.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "order_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *OrderFeeSupplementRequestQuery) loadRequestedByUser(ctx context.Context, query *UserQuery, nodes []*OrderFeeSupplementRequest, init func(*OrderFeeSupplementRequest), assign func(*OrderFeeSupplementRequest, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*OrderFeeSupplementRequest)
	for i := range nodes {
		fk := nodes[i].RequestedBy
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "requested_by" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *OrderFeeSupplementRequestQuery) loadDecidedByUser(ctx context.Context, query *UserQuery, nodes []*OrderFeeSupplementRequest, init func(*OrderFeeSupplementRequest), assign func(*OrderFeeSupplementRequest, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*OrderFeeSupplementRequest)
	for i := range nodes {
		if nodes[i].DecidedBy == nil {
			continue
		}
		fk := *nodes[i].DecidedBy
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "decided_by" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *OrderFeeSupplementRequestQuery) loadFees(ctx context.Context, query *OrderFeeQuery, nodes []*OrderFeeSupplementRequest, init func(*OrderFeeSupplementRequest), assign func(*OrderFeeSupplementRequest, *OrderFee)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*OrderFeeSupplementRequest)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(orderfee.FieldSupplementRequestID)
	}
	query.Where(predicate.OrderFee(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(orderfeesupplementrequest.FeesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SupplementRequestID
		if fk == nil {
			return fmt.Errorf(`foreign-key "supplement_request_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "supplement_request_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *OrderFeeSupplementRequestQuery) loadCommissionAdjustments(ctx context.Context, query *FinanceCommissionAdjustmentQuery, nodes []*OrderFeeSupplementRequest, init func(*OrderFeeSupplementRequest), assign func(*OrderFeeSupplementRequest, *FinanceCommissionAdjustment)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*OrderFeeSupplementRequest)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(financecommissionadjustment.FieldSourceFeeSupplementRequestID)
	}
	query.Where(predicate.FinanceCommissionAdjustment(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(orderfeesupplementrequest.CommissionAdjustmentsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SourceFeeSupplementRequestID
		if fk == nil {
			return fmt.Errorf(`foreign-key "source_fee_supplement_request_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "source_fee_supplement_request_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *OrderFeeSupplementRequestQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *OrderFeeSupplementRequestQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(orderfeesupplementrequest.Table, orderfeesupplementrequest.Columns, sqlgraph.NewFieldSpec(orderfeesupplementrequest.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, orderfeesupplementrequest.FieldID)
		for i := range fields {
			if fields[i] != orderfeesupplementrequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withOrganization != nil {
			_spec.Node.AddColumnOnce(orderfeesupplementrequest.FieldOrganizationID)
		}
		if _q.withOrder != nil {
			_spec.Node.AddColumnOnce(orderfeesupplementrequest.FieldOrderID)
		}
		if _q.withRequestedByUser != nil {
			_spec.Node.AddColumnOnce(orderfeesupplementrequest.FieldRequestedBy)
		}
		if _q.withDecidedByUser != nil {
			_spec.Node.AddColumnOnce(orderfeesupplementrequest.FieldDecidedBy)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *OrderFeeSupplementRequestQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(orderfeesupplementrequest.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = orderfeesupplementrequest.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *OrderFeeSupplementRequestQuery) ForUpdate(opts ...sql.LockOption) *OrderFeeSupplementRequestQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *OrderFeeSupplementRequestQuery) ForShare(opts ...sql.LockOption) *OrderFeeSupplementRequestQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// OrderFeeSupplementRequestGroupBy is the group-by builder for OrderFeeSupplementRequest entities.
type OrderFeeSupplementRequestGroupBy struct {
	selector
	build *OrderFeeSupplementRequestQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *OrderFeeSupplementRequestGroupBy) Aggregate(fns ...AggregateFunc) *OrderFeeSupplementRequestGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *OrderFeeSupplementRequestGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OrderFeeSupplementRequestQuery, *OrderFeeSupplementRequestGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *OrderFeeSupplementRequestGroupBy) sqlScan(ctx context.Context, root *OrderFeeSupplementRequestQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// OrderFeeSupplementRequestSelect is the builder for selecting fields of OrderFeeSupplementRequest entities.
type OrderFeeSupplementRequestSelect struct {
	*OrderFeeSupplementRequestQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *OrderFeeSupplementRequestSelect) Aggregate(fns ...AggregateFunc) *OrderFeeSupplementRequestSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *OrderFeeSupplementRequestSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OrderFeeSupplementRequestQuery, *OrderFeeSupplementRequestSelect](ctx, _s.OrderFeeSupplementRequestQuery, _s, _s.inters, v)
}

func (_s *OrderFeeSupplementRequestSelect) sqlScan(ctx context.Context, root *OrderFeeSupplementRequestQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
