// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/financebillline"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/order"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/orderabnormalcase"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/orderattachment"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/ordercargocategory"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/ordercargoitem"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/ordercontainer"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/ordercontainerrequest"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/orderfee"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/ordermilestone"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/orderpersonnel"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/orderreleasepod"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/orderservicetype"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/ordershippingdocument"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/orderstatuslog"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/organization"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/partner"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/predicate"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/statustemplate"
)

// OrderQuery is the builder for querying Order entities.
type OrderQuery struct {
	config
	ctx                   *QueryContext
	order                 []order.OrderOption
	inters                []Interceptor
	predicates            []predicate.Order
	withOrganization      *OrganizationQuery
	withCustomer          *PartnerQuery
	withStatusTemplate    *StatusTemplateQuery
	withStatusLogs        *OrderStatusLogQuery
	withServiceTypes      *OrderServiceTypeQuery
	withCargoCategories   *OrderCargoCategoryQuery
	withMilestones        *OrderMilestoneQuery
	withAttachments       *OrderAttachmentQuery
	withPersonnel         *OrderPersonnelQuery
	withContainers        *OrderContainerQuery
	withContainerRequests *OrderContainerRequestQuery
	withCargoItems        *OrderCargoItemQuery
	withShippingDocuments *OrderShippingDocumentQuery
	withReleasePods       *OrderReleasePodQuery
	withAbnormalCases     *OrderAbnormalCaseQuery
	withFees              *OrderFeeQuery
	withFinanceBillLines  *FinanceBillLineQuery
	modifiers             []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the OrderQuery builder.
func (_q *OrderQuery) Where(ps ...predicate.Order) *OrderQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *OrderQuery) Limit(limit int) *OrderQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *OrderQuery) Offset(offset int) *OrderQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *OrderQuery) Unique(unique bool) *OrderQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *OrderQuery) Order(o ...order.OrderOption) *OrderQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryOrganization chains the current query on the "organization" edge.
func (_q *OrderQuery) QueryOrganization() *OrganizationQuery {
	query := (&OrganizationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(order.Table, order.FieldID, selector),
			sqlgraph.To(organization.Table, organization.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, order.OrganizationTable, order.OrganizationColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCustomer chains the current query on the "customer" edge.
func (_q *OrderQuery) QueryCustomer() *PartnerQuery {
	query := (&PartnerClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(order.Table, order.FieldID, selector),
			sqlgraph.To(partner.Table, partner.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, order.CustomerTable, order.CustomerColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryStatusTemplate chains the current query on the "status_template" edge.
func (_q *OrderQuery) QueryStatusTemplate() *StatusTemplateQuery {
	query := (&StatusTemplateClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(order.Table, order.FieldID, selector),
			sqlgraph.To(statustemplate.Table, statustemplate.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, order.StatusTemplateTable, order.StatusTemplateColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryStatusLogs chains the current query on the "status_logs" edge.
func (_q *OrderQuery) QueryStatusLogs() *OrderStatusLogQuery {
	query := (&OrderStatusLogClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(order.Table, order.FieldID, selector),
			sqlgraph.To(orderstatuslog.Table, orderstatuslog.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, order.StatusLogsTable, order.StatusLogsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryServiceTypes chains the current query on the "service_types" edge.
func (_q *OrderQuery) QueryServiceTypes() *OrderServiceTypeQuery {
	query := (&OrderServiceTypeClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(order.Table, order.FieldID, selector),
			sqlgraph.To(orderservicetype.Table, orderservicetype.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, order.ServiceTypesTable, order.ServiceTypesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCargoCategories chains the current query on the "cargo_categories" edge.
func (_q *OrderQuery) QueryCargoCategories() *OrderCargoCategoryQuery {
	query := (&OrderCargoCategoryClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(order.Table, order.FieldID, selector),
			sqlgraph.To(ordercargocategory.Table, ordercargocategory.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, order.CargoCategoriesTable, order.CargoCategoriesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMilestones chains the current query on the "milestones" edge.
func (_q *OrderQuery) QueryMilestones() *OrderMilestoneQuery {
	query := (&OrderMilestoneClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(order.Table, order.FieldID, selector),
			sqlgraph.To(ordermilestone.Table, ordermilestone.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, order.MilestonesTable, order.MilestonesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAttachments chains the current query on the "attachments" edge.
func (_q *OrderQuery) QueryAttachments() *OrderAttachmentQuery {
	query := (&OrderAttachmentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(order.Table, order.FieldID, selector),
			sqlgraph.To(orderattachment.Table, orderattachment.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, order.AttachmentsTable, order.AttachmentsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPersonnel chains the current query on the "personnel" edge.
func (_q *OrderQuery) QueryPersonnel() *OrderPersonnelQuery {
	query := (&OrderPersonnelClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(order.Table, order.FieldID, selector),
			sqlgraph.To(orderpersonnel.Table, orderpersonnel.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, order.PersonnelTable, order.PersonnelColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryContainers chains the current query on the "containers" edge.
func (_q *OrderQuery) QueryContainers() *OrderContainerQuery {
	query := (&OrderContainerClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(order.Table, order.FieldID, selector),
			sqlgraph.To(ordercontainer.Table, ordercontainer.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, order.ContainersTable, order.ContainersColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryContainerRequests chains the current query on the "container_requests" edge.
func (_q *OrderQuery) QueryContainerRequests() *OrderContainerRequestQuery {
	query := (&OrderContainerRequestClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(order.Table, order.FieldID, selector),
			sqlgraph.To(ordercontainerrequest.Table, ordercontainerrequest.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, order.ContainerRequestsTable, order.ContainerRequestsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCargoItems chains the current query on the "cargo_items" edge.
func (_q *OrderQuery) QueryCargoItems() *OrderCargoItemQuery {
	query := (&OrderCargoItemClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(order.Table, order.FieldID, selector),
			sqlgraph.To(ordercargoitem.Table, ordercargoitem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, order.CargoItemsTable, order.CargoItemsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryShippingDocuments chains the current query on the "shipping_documents" edge.
func (_q *OrderQuery) QueryShippingDocuments() *OrderShippingDocumentQuery {
	query := (&OrderShippingDocumentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(order.Table, order.FieldID, selector),
			sqlgraph.To(ordershippingdocument.Table, ordershippingdocument.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, order.ShippingDocumentsTable, order.ShippingDocumentsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryReleasePods chains the current query on the "release_pods" edge.
func (_q *OrderQuery) QueryReleasePods() *OrderReleasePodQuery {
	query := (&OrderReleasePodClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(order.Table, order.FieldID, selector),
			sqlgraph.To(orderreleasepod.Table, orderreleasepod.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, order.ReleasePodsTable, order.ReleasePodsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAbnormalCases chains the current query on the "abnormal_cases" edge.
func (_q *OrderQuery) QueryAbnormalCases() *OrderAbnormalCaseQuery {
	query := (&OrderAbnormalCaseClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(order.Table, order.FieldID, selector),
			sqlgraph.To(orderabnormalcase.Table, orderabnormalcase.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, order.AbnormalCasesTable, order.AbnormalCasesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFees chains the current query on the "fees" edge.
func (_q *OrderQuery) QueryFees() *OrderFeeQuery {
	query := (&OrderFeeClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(order.Table, order.FieldID, selector),
			sqlgraph.To(orderfee.Table, orderfee.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, order.FeesTable, order.FeesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFinanceBillLines chains the current query on the "finance_bill_lines" edge.
func (_q *OrderQuery) QueryFinanceBillLines() *FinanceBillLineQuery {
	query := (&FinanceBillLineClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(order.Table, order.FieldID, selector),
			sqlgraph.To(financebillline.Table, financebillline.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, order.FinanceBillLinesTable, order.FinanceBillLinesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Order entity from the query.
// Returns a *NotFoundError when no Order was found.
func (_q *OrderQuery) First(ctx context.Context) (*Order, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{order.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *OrderQuery) FirstX(ctx context.Context) *Order {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Order ID from the query.
// Returns a *NotFoundError when no Order ID was found.
func (_q *OrderQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{order.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *OrderQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Order entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Order entity is found.
// Returns a *NotFoundError when no Order entities are found.
func (_q *OrderQuery) Only(ctx context.Context) (*Order, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{order.Label}
	default:
		return nil, &NotSingularError{order.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *OrderQuery) OnlyX(ctx context.Context) *Order {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Order ID in the query.
// Returns a *NotSingularError when more than one Order ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *OrderQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{order.Label}
	default:
		err = &NotSingularError{order.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *OrderQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Orders.
func (_q *OrderQuery) All(ctx context.Context) ([]*Order, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Order, *OrderQuery]()
	return withInterceptors[[]*Order](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *OrderQuery) AllX(ctx context.Context) []*Order {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Order IDs.
func (_q *OrderQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(order.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *OrderQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *OrderQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*OrderQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *OrderQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *OrderQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *OrderQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the OrderQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *OrderQuery) Clone() *OrderQuery {
	if _q == nil {
		return nil
	}
	return &OrderQuery{
		config:                _q.config,
		ctx:                   _q.ctx.Clone(),
		order:                 append([]order.OrderOption{}, _q.order...),
		inters:                append([]Interceptor{}, _q.inters...),
		predicates:            append([]predicate.Order{}, _q.predicates...),
		withOrganization:      _q.withOrganization.Clone(),
		withCustomer:          _q.withCustomer.Clone(),
		withStatusTemplate:    _q.withStatusTemplate.Clone(),
		withStatusLogs:        _q.withStatusLogs.Clone(),
		withServiceTypes:      _q.withServiceTypes.Clone(),
		withCargoCategories:   _q.withCargoCategories.Clone(),
		withMilestones:        _q.withMilestones.Clone(),
		withAttachments:       _q.withAttachments.Clone(),
		withPersonnel:         _q.withPersonnel.Clone(),
		withContainers:        _q.withContainers.Clone(),
		withContainerRequests: _q.withContainerRequests.Clone(),
		withCargoItems:        _q.withCargoItems.Clone(),
		withShippingDocuments: _q.withShippingDocuments.Clone(),
		withReleasePods:       _q.withReleasePods.Clone(),
		withAbnormalCases:     _q.withAbnormalCases.Clone(),
		withFees:              _q.withFees.Clone(),
		withFinanceBillLines:  _q.withFinanceBillLines.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithOrganization tells the query-builder to eager-load the nodes that are connected to
// the "organization" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OrderQuery) WithOrganization(opts ...func(*OrganizationQuery)) *OrderQuery {
	query := (&OrganizationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOrganization = query
	return _q
}

// WithCustomer tells the query-builder to eager-load the nodes that are connected to
// the "customer" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OrderQuery) WithCustomer(opts ...func(*PartnerQuery)) *OrderQuery {
	query := (&PartnerClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCustomer = query
	return _q
}

// WithStatusTemplate tells the query-builder to eager-load the nodes that are connected to
// the "status_template" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OrderQuery) WithStatusTemplate(opts ...func(*StatusTemplateQuery)) *OrderQuery {
	query := (&StatusTemplateClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withStatusTemplate = query
	return _q
}

// WithStatusLogs tells the query-builder to eager-load the nodes that are connected to
// the "status_logs" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OrderQuery) WithStatusLogs(opts ...func(*OrderStatusLogQuery)) *OrderQuery {
	query := (&OrderStatusLogClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withStatusLogs = query
	return _q
}

// WithServiceTypes tells the query-builder to eager-load the nodes that are connected to
// the "service_types" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OrderQuery) WithServiceTypes(opts ...func(*OrderServiceTypeQuery)) *OrderQuery {
	query := (&OrderServiceTypeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withServiceTypes = query
	return _q
}

// WithCargoCategories tells the query-builder to eager-load the nodes that are connected to
// the "cargo_categories" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OrderQuery) WithCargoCategories(opts ...func(*OrderCargoCategoryQuery)) *OrderQuery {
	query := (&OrderCargoCategoryClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCargoCategories = query
	return _q
}

// WithMilestones tells the query-builder to eager-load the nodes that are connected to
// the "milestones" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OrderQuery) WithMilestones(opts ...func(*OrderMilestoneQuery)) *OrderQuery {
	query := (&OrderMilestoneClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMilestones = query
	return _q
}

// WithAttachments tells the query-builder to eager-load the nodes that are connected to
// the "attachments" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OrderQuery) WithAttachments(opts ...func(*OrderAttachmentQuery)) *OrderQuery {
	query := (&OrderAttachmentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAttachments = query
	return _q
}

// WithPersonnel tells the query-builder to eager-load the nodes that are connected to
// the "personnel" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OrderQuery) WithPersonnel(opts ...func(*OrderPersonnelQuery)) *OrderQuery {
	query := (&OrderPersonnelClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPersonnel = query
	return _q
}

// WithContainers tells the query-builder to eager-load the nodes that are connected to
// the "containers" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OrderQuery) WithContainers(opts ...func(*OrderContainerQuery)) *OrderQuery {
	query := (&OrderContainerClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withContainers = query
	return _q
}

// WithContainerRequests tells the query-builder to eager-load the nodes that are connected to
// the "container_requests" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OrderQuery) WithContainerRequests(opts ...func(*OrderContainerRequestQuery)) *OrderQuery {
	query := (&OrderContainerRequestClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withContainerRequests = query
	return _q
}

// WithCargoItems tells the query-builder to eager-load the nodes that are connected to
// the "cargo_items" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OrderQuery) WithCargoItems(opts ...func(*OrderCargoItemQuery)) *OrderQuery {
	query := (&OrderCargoItemClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCargoItems = query
	return _q
}

// WithShippingDocuments tells the query-builder to eager-load the nodes that are connected to
// the "shipping_documents" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OrderQuery) WithShippingDocuments(opts ...func(*OrderShippingDocumentQuery)) *OrderQuery {
	query := (&OrderShippingDocumentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withShippingDocuments = query
	return _q
}

// WithReleasePods tells the query-builder to eager-load the nodes that are connected to
// the "release_pods" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OrderQuery) WithReleasePods(opts ...func(*OrderReleasePodQuery)) *OrderQuery {
	query := (&OrderReleasePodClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withReleasePods = query
	return _q
}

// WithAbnormalCases tells the query-builder to eager-load the nodes that are connected to
// the "abnormal_cases" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OrderQuery) WithAbnormalCases(opts ...func(*OrderAbnormalCaseQuery)) *OrderQuery {
	query := (&OrderAbnormalCaseClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAbnormalCases = query
	return _q
}

// WithFees tells the query-builder to eager-load the nodes that are connected to
// the "fees" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OrderQuery) WithFees(opts ...func(*OrderFeeQuery)) *OrderQuery {
	query := (&OrderFeeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withFees = query
	return _q
}

// WithFinanceBillLines tells the query-builder to eager-load the nodes that are connected to
// the "finance_bill_lines" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *OrderQuery) WithFinanceBillLines(opts ...func(*FinanceBillLineQuery)) *OrderQuery {
	query := (&FinanceBillLineClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withFinanceBillLines = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Order.Query().
//		GroupBy(order.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *OrderQuery) GroupBy(field string, fields ...string) *OrderGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &OrderGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = order.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Order.Query().
//		Select(order.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *OrderQuery) Select(fields ...string) *OrderSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &OrderSelect{OrderQuery: _q}
	sbuild.label = order.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a OrderSelect configured with the given aggregations.
func (_q *OrderQuery) Aggregate(fns ...AggregateFunc) *OrderSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *OrderQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !order.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *OrderQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Order, error) {
	var (
		nodes       = []*Order{}
		_spec       = _q.querySpec()
		loadedTypes = [17]bool{
			_q.withOrganization != nil,
			_q.withCustomer != nil,
			_q.withStatusTemplate != nil,
			_q.withStatusLogs != nil,
			_q.withServiceTypes != nil,
			_q.withCargoCategories != nil,
			_q.withMilestones != nil,
			_q.withAttachments != nil,
			_q.withPersonnel != nil,
			_q.withContainers != nil,
			_q.withContainerRequests != nil,
			_q.withCargoItems != nil,
			_q.withShippingDocuments != nil,
			_q.withReleasePods != nil,
			_q.withAbnormalCases != nil,
			_q.withFees != nil,
			_q.withFinanceBillLines != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Order).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Order{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withOrganization; query != nil {
		if err := _q.loadOrganization(ctx, query, nodes, nil,
			func(n *Order, e *Organization) { n.Edges.Organization = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCustomer; query != nil {
		if err := _q.loadCustomer(ctx, query, nodes, nil,
			func(n *Order, e *Partner) { n.Edges.Customer = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withStatusTemplate; query != nil {
		if err := _q.loadStatusTemplate(ctx, query, nodes, nil,
			func(n *Order, e *StatusTemplate) { n.Edges.StatusTemplate = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withStatusLogs; query != nil {
		if err := _q.loadStatusLogs(ctx, query, nodes,
			func(n *Order) { n.Edges.StatusLogs = []*OrderStatusLog{} },
			func(n *Order, e *OrderStatusLog) { n.Edges.StatusLogs = append(n.Edges.StatusLogs, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withServiceTypes; query != nil {
		if err := _q.loadServiceTypes(ctx, query, nodes,
			func(n *Order) { n.Edges.ServiceTypes = []*OrderServiceType{} },
			func(n *Order, e *OrderServiceType) { n.Edges.ServiceTypes = append(n.Edges.ServiceTypes, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCargoCategories; query != nil {
		if err := _q.loadCargoCategories(ctx, query, nodes,
			func(n *Order) { n.Edges.CargoCategories = []*OrderCargoCategory{} },
			func(n *Order, e *OrderCargoCategory) { n.Edges.CargoCategories = append(n.Edges.CargoCategories, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withMilestones; query != nil {
		if err := _q.loadMilestones(ctx, query, nodes,
			func(n *Order) { n.Edges.Milestones = []*OrderMilestone{} },
			func(n *Order, e *OrderMilestone) { n.Edges.Milestones = append(n.Edges.Milestones, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAttachments; query != nil {
		if err := _q.loadAttachments(ctx, query, nodes,
			func(n *Order) { n.Edges.Attachments = []*OrderAttachment{} },
			func(n *Order, e *OrderAttachment) { n.Edges.Attachments = append(n.Edges.Attachments, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPersonnel; query != nil {
		if err := _q.loadPersonnel(ctx, query, nodes,
			func(n *Order) { n.Edges.Personnel = []*OrderPersonnel{} },
			func(n *Order, e *OrderPersonnel) { n.Edges.Personnel = append(n.Edges.Personnel, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withContainers; query != nil {
		if err := _q.loadContainers(ctx, query, nodes,
			func(n *Order) { n.Edges.Containers = []*OrderContainer{} },
			func(n *Order, e *OrderContainer) { n.Edges.Containers = append(n.Edges.Containers, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withContainerRequests; query != nil {
		if err := _q.loadContainerRequests(ctx, query, nodes,
			func(n *Order) { n.Edges.ContainerRequests = []*OrderContainerRequest{} },
			func(n *Order, e *OrderContainerRequest) {
				n.Edges.ContainerRequests = append(n.Edges.ContainerRequests, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withCargoItems; query != nil {
		if err := _q.loadCargoItems(ctx, query, nodes,
			func(n *Order) { n.Edges.CargoItems = []*OrderCargoItem{} },
			func(n *Order, e *OrderCargoItem) { n.Edges.CargoItems = append(n.Edges.CargoItems, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withShippingDocuments; query != nil {
		if err := _q.loadShippingDocuments(ctx, query, nodes,
			func(n *Order) { n.Edges.ShippingDocuments = []*OrderShippingDocument{} },
			func(n *Order, e *OrderShippingDocument) {
				n.Edges.ShippingDocuments = append(n.Edges.ShippingDocuments, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withReleasePods; query != nil {
		if err := _q.loadReleasePods(ctx, query, nodes,
			func(n *Order) { n.Edges.ReleasePods = []*OrderReleasePod{} },
			func(n *Order, e *OrderReleasePod) { n.Edges.ReleasePods = append(n.Edges.ReleasePods, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAbnormalCases; query != nil {
		if err := _q.loadAbnormalCases(ctx, query, nodes,
			func(n *Order) { n.Edges.AbnormalCases = []*OrderAbnormalCase{} },
			func(n *Order, e *OrderAbnormalCase) { n.Edges.AbnormalCases = append(n.Edges.AbnormalCases, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withFees; query != nil {
		if err := _q.loadFees(ctx, query, nodes,
			func(n *Order) { n.Edges.Fees = []*OrderFee{} },
			func(n *Order, e *OrderFee) { n.Edges.Fees = append(n.Edges.Fees, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withFinanceBillLines; query != nil {
		if err := _q.loadFinanceBillLines(ctx, query, nodes,
			func(n *Order) { n.Edges.FinanceBillLines = []*FinanceBillLine{} },
			func(n *Order, e *FinanceBillLine) { n.Edges.FinanceBillLines = append(n.Edges.FinanceBillLines, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *OrderQuery) loadOrganization(ctx context.Context, query *OrganizationQuery, nodes []*Order, init func(*Order), assign func(*Order, *Organization)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Order)
	for i := range nodes {
		fk := nodes[i].OrganizationID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(organization.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "organization_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *OrderQuery) loadCustomer(ctx context.Context, query *PartnerQuery, nodes []*Order, init func(*Order), assign func(*Order, *Partner)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Order)
	for i := range nodes {
		fk := nodes[i].CustomerID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(partner.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "customer_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *OrderQuery) loadStatusTemplate(ctx context.Context, query *StatusTemplateQuery, nodes []*Order, init func(*Order), assign func(*Order, *StatusTemplate)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Order)
	for i := range nodes {
		fk := nodes[i].StatusTemplateID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(statustemplate.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "status_template_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *OrderQuery) loadStatusLogs(ctx context.Context, query *OrderStatusLogQuery, nodes []*Order, init func(*Order), assign func(*Order, *OrderStatusLog)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Order)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(orderstatuslog.FieldOrderID)
	}
	query.Where(predicate.OrderStatusLog(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(order.StatusLogsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.OrderID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "order_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *OrderQuery) loadServiceTypes(ctx context.Context, query *OrderServiceTypeQuery, nodes []*Order, init func(*Order), assign func(*Order, *OrderServiceType)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Order)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(orderservicetype.FieldOrderID)
	}
	query.Where(predicate.OrderServiceType(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(order.ServiceTypesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.OrderID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "order_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *OrderQuery) loadCargoCategories(ctx context.Context, query *OrderCargoCategoryQuery, nodes []*Order, init func(*Order), assign func(*Order, *OrderCargoCategory)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Order)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(ordercargocategory.FieldOrderID)
	}
	query.Where(predicate.OrderCargoCategory(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(order.CargoCategoriesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.OrderID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "order_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *OrderQuery) loadMilestones(ctx context.Context, query *OrderMilestoneQuery, nodes []*Order, init func(*Order), assign func(*Order, *OrderMilestone)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Order)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(ordermilestone.FieldOrderID)
	}
	query.Where(predicate.OrderMilestone(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(order.MilestonesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.OrderID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "order_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *OrderQuery) loadAttachments(ctx context.Context, query *OrderAttachmentQuery, nodes []*Order, init func(*Order), assign func(*Order, *OrderAttachment)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Order)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(orderattachment.FieldOrderID)
	}
	query.Where(predicate.OrderAttachment(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(order.AttachmentsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.OrderID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "order_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *OrderQuery) loadPersonnel(ctx context.Context, query *OrderPersonnelQuery, nodes []*Order, init func(*Order), assign func(*Order, *OrderPersonnel)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Order)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(orderpersonnel.FieldOrderID)
	}
	query.Where(predicate.OrderPersonnel(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(order.PersonnelColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.OrderID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "order_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *OrderQuery) loadContainers(ctx context.Context, query *OrderContainerQuery, nodes []*Order, init func(*Order), assign func(*Order, *OrderContainer)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Order)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(ordercontainer.FieldOrderID)
	}
	query.Where(predicate.OrderContainer(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(order.ContainersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.OrderID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "order_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *OrderQuery) loadContainerRequests(ctx context.Context, query *OrderContainerRequestQuery, nodes []*Order, init func(*Order), assign func(*Order, *OrderContainerRequest)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Order)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(ordercontainerrequest.FieldOrderID)
	}
	query.Where(predicate.OrderContainerRequest(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(order.ContainerRequestsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.OrderID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "order_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *OrderQuery) loadCargoItems(ctx context.Context, query *OrderCargoItemQuery, nodes []*Order, init func(*Order), assign func(*Order, *OrderCargoItem)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Order)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(ordercargoitem.FieldOrderID)
	}
	query.Where(predicate.OrderCargoItem(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(order.CargoItemsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.OrderID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "order_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *OrderQuery) loadShippingDocuments(ctx context.Context, query *OrderShippingDocumentQuery, nodes []*Order, init func(*Order), assign func(*Order, *OrderShippingDocument)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Order)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(ordershippingdocument.FieldOrderID)
	}
	query.Where(predicate.OrderShippingDocument(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(order.ShippingDocumentsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.OrderID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "order_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *OrderQuery) loadReleasePods(ctx context.Context, query *OrderReleasePodQuery, nodes []*Order, init func(*Order), assign func(*Order, *OrderReleasePod)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Order)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(orderreleasepod.FieldOrderID)
	}
	query.Where(predicate.OrderReleasePod(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(order.ReleasePodsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.OrderID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "order_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *OrderQuery) loadAbnormalCases(ctx context.Context, query *OrderAbnormalCaseQuery, nodes []*Order, init func(*Order), assign func(*Order, *OrderAbnormalCase)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Order)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(orderabnormalcase.FieldOrderID)
	}
	query.Where(predicate.OrderAbnormalCase(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(order.AbnormalCasesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.OrderID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "order_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *OrderQuery) loadFees(ctx context.Context, query *OrderFeeQuery, nodes []*Order, init func(*Order), assign func(*Order, *OrderFee)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Order)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(orderfee.FieldOrderID)
	}
	query.Where(predicate.OrderFee(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(order.FeesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.OrderID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "order_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *OrderQuery) loadFinanceBillLines(ctx context.Context, query *FinanceBillLineQuery, nodes []*Order, init func(*Order), assign func(*Order, *FinanceBillLine)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Order)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(financebillline.FieldOrderID)
	}
	query.Where(predicate.FinanceBillLine(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(order.FinanceBillLinesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.OrderID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "order_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *OrderQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *OrderQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, order.FieldID)
		for i := range fields {
			if fields[i] != order.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withOrganization != nil {
			_spec.Node.AddColumnOnce(order.FieldOrganizationID)
		}
		if _q.withCustomer != nil {
			_spec.Node.AddColumnOnce(order.FieldCustomerID)
		}
		if _q.withStatusTemplate != nil {
			_spec.Node.AddColumnOnce(order.FieldStatusTemplateID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *OrderQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(order.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = order.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *OrderQuery) ForUpdate(opts ...sql.LockOption) *OrderQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *OrderQuery) ForShare(opts ...sql.LockOption) *OrderQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// OrderGroupBy is the group-by builder for Order entities.
type OrderGroupBy struct {
	selector
	build *OrderQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *OrderGroupBy) Aggregate(fns ...AggregateFunc) *OrderGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *OrderGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OrderQuery, *OrderGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *OrderGroupBy) sqlScan(ctx context.Context, root *OrderQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// OrderSelect is the builder for selecting fields of Order entities.
type OrderSelect struct {
	*OrderQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *OrderSelect) Aggregate(fns ...AggregateFunc) *OrderSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *OrderSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*OrderQuery, *OrderSelect](ctx, _s.OrderQuery, _s, _s.inters, v)
}

func (_s *OrderSelect) sqlScan(ctx context.Context, root *OrderQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
