// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/dingtalkapprovaldispatch"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/orderunlockapprovercandidate"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/orderunlockrequest"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/predicate"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/user"
)

// OrderUnlockRequestUpdate is the builder for updating OrderUnlockRequest entities.
type OrderUnlockRequestUpdate struct {
	config
	hooks    []Hook
	mutation *OrderUnlockRequestMutation
}

// Where appends a list predicates to the OrderUnlockRequestUpdate builder.
func (_u *OrderUnlockRequestUpdate) Where(ps ...predicate.OrderUnlockRequest) *OrderUnlockRequestUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetReason sets the "reason" field.
func (_u *OrderUnlockRequestUpdate) SetReason(v string) *OrderUnlockRequestUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *OrderUnlockRequestUpdate) SetNillableReason(v *string) *OrderUnlockRequestUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *OrderUnlockRequestUpdate) ClearReason() *OrderUnlockRequestUpdate {
	_u.mutation.ClearReason()
	return _u
}

// SetStatus sets the "status" field.
func (_u *OrderUnlockRequestUpdate) SetStatus(v orderunlockrequest.Status) *OrderUnlockRequestUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OrderUnlockRequestUpdate) SetNillableStatus(v *orderunlockrequest.Status) *OrderUnlockRequestUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDingtalkProcessInstanceID sets the "dingtalk_process_instance_id" field.
func (_u *OrderUnlockRequestUpdate) SetDingtalkProcessInstanceID(v string) *OrderUnlockRequestUpdate {
	_u.mutation.SetDingtalkProcessInstanceID(v)
	return _u
}

// SetNillableDingtalkProcessInstanceID sets the "dingtalk_process_instance_id" field if the given value is not nil.
func (_u *OrderUnlockRequestUpdate) SetNillableDingtalkProcessInstanceID(v *string) *OrderUnlockRequestUpdate {
	if v != nil {
		_u.SetDingtalkProcessInstanceID(*v)
	}
	return _u
}

// ClearDingtalkProcessInstanceID clears the value of the "dingtalk_process_instance_id" field.
func (_u *OrderUnlockRequestUpdate) ClearDingtalkProcessInstanceID() *OrderUnlockRequestUpdate {
	_u.mutation.ClearDingtalkProcessInstanceID()
	return _u
}

// SetDingtalkProcessCode sets the "dingtalk_process_code" field.
func (_u *OrderUnlockRequestUpdate) SetDingtalkProcessCode(v string) *OrderUnlockRequestUpdate {
	_u.mutation.SetDingtalkProcessCode(v)
	return _u
}

// SetNillableDingtalkProcessCode sets the "dingtalk_process_code" field if the given value is not nil.
func (_u *OrderUnlockRequestUpdate) SetNillableDingtalkProcessCode(v *string) *OrderUnlockRequestUpdate {
	if v != nil {
		_u.SetDingtalkProcessCode(*v)
	}
	return _u
}

// ClearDingtalkProcessCode clears the value of the "dingtalk_process_code" field.
func (_u *OrderUnlockRequestUpdate) ClearDingtalkProcessCode() *OrderUnlockRequestUpdate {
	_u.mutation.ClearDingtalkProcessCode()
	return _u
}

// SetDecidedBy sets the "decided_by" field.
func (_u *OrderUnlockRequestUpdate) SetDecidedBy(v uuid.UUID) *OrderUnlockRequestUpdate {
	_u.mutation.SetDecidedBy(v)
	return _u
}

// SetNillableDecidedBy sets the "decided_by" field if the given value is not nil.
func (_u *OrderUnlockRequestUpdate) SetNillableDecidedBy(v *uuid.UUID) *OrderUnlockRequestUpdate {
	if v != nil {
		_u.SetDecidedBy(*v)
	}
	return _u
}

// ClearDecidedBy clears the value of the "decided_by" field.
func (_u *OrderUnlockRequestUpdate) ClearDecidedBy() *OrderUnlockRequestUpdate {
	_u.mutation.ClearDecidedBy()
	return _u
}

// SetDecidedAt sets the "decided_at" field.
func (_u *OrderUnlockRequestUpdate) SetDecidedAt(v time.Time) *OrderUnlockRequestUpdate {
	_u.mutation.SetDecidedAt(v)
	return _u
}

// SetNillableDecidedAt sets the "decided_at" field if the given value is not nil.
func (_u *OrderUnlockRequestUpdate) SetNillableDecidedAt(v *time.Time) *OrderUnlockRequestUpdate {
	if v != nil {
		_u.SetDecidedAt(*v)
	}
	return _u
}

// ClearDecidedAt clears the value of the "decided_at" field.
func (_u *OrderUnlockRequestUpdate) ClearDecidedAt() *OrderUnlockRequestUpdate {
	_u.mutation.ClearDecidedAt()
	return _u
}

// SetDecisionSource sets the "decision_source" field.
func (_u *OrderUnlockRequestUpdate) SetDecisionSource(v string) *OrderUnlockRequestUpdate {
	_u.mutation.SetDecisionSource(v)
	return _u
}

// SetNillableDecisionSource sets the "decision_source" field if the given value is not nil.
func (_u *OrderUnlockRequestUpdate) SetNillableDecisionSource(v *string) *OrderUnlockRequestUpdate {
	if v != nil {
		_u.SetDecisionSource(*v)
	}
	return _u
}

// ClearDecisionSource clears the value of the "decision_source" field.
func (_u *OrderUnlockRequestUpdate) ClearDecisionSource() *OrderUnlockRequestUpdate {
	_u.mutation.ClearDecisionSource()
	return _u
}

// SetFailureCode sets the "failure_code" field.
func (_u *OrderUnlockRequestUpdate) SetFailureCode(v string) *OrderUnlockRequestUpdate {
	_u.mutation.SetFailureCode(v)
	return _u
}

// SetNillableFailureCode sets the "failure_code" field if the given value is not nil.
func (_u *OrderUnlockRequestUpdate) SetNillableFailureCode(v *string) *OrderUnlockRequestUpdate {
	if v != nil {
		_u.SetFailureCode(*v)
	}
	return _u
}

// ClearFailureCode clears the value of the "failure_code" field.
func (_u *OrderUnlockRequestUpdate) ClearFailureCode() *OrderUnlockRequestUpdate {
	_u.mutation.ClearFailureCode()
	return _u
}

// SetFailureMessage sets the "failure_message" field.
func (_u *OrderUnlockRequestUpdate) SetFailureMessage(v string) *OrderUnlockRequestUpdate {
	_u.mutation.SetFailureMessage(v)
	return _u
}

// SetNillableFailureMessage sets the "failure_message" field if the given value is not nil.
func (_u *OrderUnlockRequestUpdate) SetNillableFailureMessage(v *string) *OrderUnlockRequestUpdate {
	if v != nil {
		_u.SetFailureMessage(*v)
	}
	return _u
}

// ClearFailureMessage clears the value of the "failure_message" field.
func (_u *OrderUnlockRequestUpdate) ClearFailureMessage() *OrderUnlockRequestUpdate {
	_u.mutation.ClearFailureMessage()
	return _u
}

// SetSupersededByRequestID sets the "superseded_by_request_id" field.
func (_u *OrderUnlockRequestUpdate) SetSupersededByRequestID(v uuid.UUID) *OrderUnlockRequestUpdate {
	_u.mutation.SetSupersededByRequestID(v)
	return _u
}

// SetNillableSupersededByRequestID sets the "superseded_by_request_id" field if the given value is not nil.
func (_u *OrderUnlockRequestUpdate) SetNillableSupersededByRequestID(v *uuid.UUID) *OrderUnlockRequestUpdate {
	if v != nil {
		_u.SetSupersededByRequestID(*v)
	}
	return _u
}

// ClearSupersededByRequestID clears the value of the "superseded_by_request_id" field.
func (_u *OrderUnlockRequestUpdate) ClearSupersededByRequestID() *OrderUnlockRequestUpdate {
	_u.mutation.ClearSupersededByRequestID()
	return _u
}

// SetUnlockedAt sets the "unlocked_at" field.
func (_u *OrderUnlockRequestUpdate) SetUnlockedAt(v time.Time) *OrderUnlockRequestUpdate {
	_u.mutation.SetUnlockedAt(v)
	return _u
}

// SetNillableUnlockedAt sets the "unlocked_at" field if the given value is not nil.
func (_u *OrderUnlockRequestUpdate) SetNillableUnlockedAt(v *time.Time) *OrderUnlockRequestUpdate {
	if v != nil {
		_u.SetUnlockedAt(*v)
	}
	return _u
}

// ClearUnlockedAt clears the value of the "unlocked_at" field.
func (_u *OrderUnlockRequestUpdate) ClearUnlockedAt() *OrderUnlockRequestUpdate {
	_u.mutation.ClearUnlockedAt()
	return _u
}

// SetResultOrderVersion sets the "result_order_version" field.
func (_u *OrderUnlockRequestUpdate) SetResultOrderVersion(v uint64) *OrderUnlockRequestUpdate {
	_u.mutation.ResetResultOrderVersion()
	_u.mutation.SetResultOrderVersion(v)
	return _u
}

// SetNillableResultOrderVersion sets the "result_order_version" field if the given value is not nil.
func (_u *OrderUnlockRequestUpdate) SetNillableResultOrderVersion(v *uint64) *OrderUnlockRequestUpdate {
	if v != nil {
		_u.SetResultOrderVersion(*v)
	}
	return _u
}

// AddResultOrderVersion adds value to the "result_order_version" field.
func (_u *OrderUnlockRequestUpdate) AddResultOrderVersion(v int64) *OrderUnlockRequestUpdate {
	_u.mutation.AddResultOrderVersion(v)
	return _u
}

// ClearResultOrderVersion clears the value of the "result_order_version" field.
func (_u *OrderUnlockRequestUpdate) ClearResultOrderVersion() *OrderUnlockRequestUpdate {
	_u.mutation.ClearResultOrderVersion()
	return _u
}

// SetDecidedByUserID sets the "decided_by_user" edge to the User entity by ID.
func (_u *OrderUnlockRequestUpdate) SetDecidedByUserID(id uuid.UUID) *OrderUnlockRequestUpdate {
	_u.mutation.SetDecidedByUserID(id)
	return _u
}

// SetNillableDecidedByUserID sets the "decided_by_user" edge to the User entity by ID if the given value is not nil.
func (_u *OrderUnlockRequestUpdate) SetNillableDecidedByUserID(id *uuid.UUID) *OrderUnlockRequestUpdate {
	if id != nil {
		_u = _u.SetDecidedByUserID(*id)
	}
	return _u
}

// SetDecidedByUser sets the "decided_by_user" edge to the User entity.
func (_u *OrderUnlockRequestUpdate) SetDecidedByUser(v *User) *OrderUnlockRequestUpdate {
	return _u.SetDecidedByUserID(v.ID)
}

// SetSupersededByRequest sets the "superseded_by_request" edge to the OrderUnlockRequest entity.
func (_u *OrderUnlockRequestUpdate) SetSupersededByRequest(v *OrderUnlockRequest) *OrderUnlockRequestUpdate {
	return _u.SetSupersededByRequestID(v.ID)
}

// AddSupersededRequestIDs adds the "superseded_requests" edge to the OrderUnlockRequest entity by IDs.
func (_u *OrderUnlockRequestUpdate) AddSupersededRequestIDs(ids ...uuid.UUID) *OrderUnlockRequestUpdate {
	_u.mutation.AddSupersededRequestIDs(ids...)
	return _u
}

// AddSupersededRequests adds the "superseded_requests" edges to the OrderUnlockRequest entity.
func (_u *OrderUnlockRequestUpdate) AddSupersededRequests(v ...*OrderUnlockRequest) *OrderUnlockRequestUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSupersededRequestIDs(ids...)
}

// AddApproverCandidateIDs adds the "approver_candidates" edge to the OrderUnlockApproverCandidate entity by IDs.
func (_u *OrderUnlockRequestUpdate) AddApproverCandidateIDs(ids ...uuid.UUID) *OrderUnlockRequestUpdate {
	_u.mutation.AddApproverCandidateIDs(ids...)
	return _u
}

// AddApproverCandidates adds the "approver_candidates" edges to the OrderUnlockApproverCandidate entity.
func (_u *OrderUnlockRequestUpdate) AddApproverCandidates(v ...*OrderUnlockApproverCandidate) *OrderUnlockRequestUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddApproverCandidateIDs(ids...)
}

// SetDispatchID sets the "dispatch" edge to the DingTalkApprovalDispatch entity by ID.
func (_u *OrderUnlockRequestUpdate) SetDispatchID(id uuid.UUID) *OrderUnlockRequestUpdate {
	_u.mutation.SetDispatchID(id)
	return _u
}

// SetNillableDispatchID sets the "dispatch" edge to the DingTalkApprovalDispatch entity by ID if the given value is not nil.
func (_u *OrderUnlockRequestUpdate) SetNillableDispatchID(id *uuid.UUID) *OrderUnlockRequestUpdate {
	if id != nil {
		_u = _u.SetDispatchID(*id)
	}
	return _u
}

// SetDispatch sets the "dispatch" edge to the DingTalkApprovalDispatch entity.
func (_u *OrderUnlockRequestUpdate) SetDispatch(v *DingTalkApprovalDispatch) *OrderUnlockRequestUpdate {
	return _u.SetDispatchID(v.ID)
}

// Mutation returns the OrderUnlockRequestMutation object of the builder.
func (_u *OrderUnlockRequestUpdate) Mutation() *OrderUnlockRequestMutation {
	return _u.mutation
}

// ClearDecidedByUser clears the "decided_by_user" edge to the User entity.
func (_u *OrderUnlockRequestUpdate) ClearDecidedByUser() *OrderUnlockRequestUpdate {
	_u.mutation.ClearDecidedByUser()
	return _u
}

// ClearSupersededByRequest clears the "superseded_by_request" edge to the OrderUnlockRequest entity.
func (_u *OrderUnlockRequestUpdate) ClearSupersededByRequest() *OrderUnlockRequestUpdate {
	_u.mutation.ClearSupersededByRequest()
	return _u
}

// ClearSupersededRequests clears all "superseded_requests" edges to the OrderUnlockRequest entity.
func (_u *OrderUnlockRequestUpdate) ClearSupersededRequests() *OrderUnlockRequestUpdate {
	_u.mutation.ClearSupersededRequests()
	return _u
}

// RemoveSupersededRequestIDs removes the "superseded_requests" edge to OrderUnlockRequest entities by IDs.
func (_u *OrderUnlockRequestUpdate) RemoveSupersededRequestIDs(ids ...uuid.UUID) *OrderUnlockRequestUpdate {
	_u.mutation.RemoveSupersededRequestIDs(ids...)
	return _u
}

// RemoveSupersededRequests removes "superseded_requests" edges to OrderUnlockRequest entities.
func (_u *OrderUnlockRequestUpdate) RemoveSupersededRequests(v ...*OrderUnlockRequest) *OrderUnlockRequestUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSupersededRequestIDs(ids...)
}

// ClearApproverCandidates clears all "approver_candidates" edges to the OrderUnlockApproverCandidate entity.
func (_u *OrderUnlockRequestUpdate) ClearApproverCandidates() *OrderUnlockRequestUpdate {
	_u.mutation.ClearApproverCandidates()
	return _u
}

// RemoveApproverCandidateIDs removes the "approver_candidates" edge to OrderUnlockApproverCandidate entities by IDs.
func (_u *OrderUnlockRequestUpdate) RemoveApproverCandidateIDs(ids ...uuid.UUID) *OrderUnlockRequestUpdate {
	_u.mutation.RemoveApproverCandidateIDs(ids...)
	return _u
}

// RemoveApproverCandidates removes "approver_candidates" edges to OrderUnlockApproverCandidate entities.
func (_u *OrderUnlockRequestUpdate) RemoveApproverCandidates(v ...*OrderUnlockApproverCandidate) *OrderUnlockRequestUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveApproverCandidateIDs(ids...)
}

// ClearDispatch clears the "dispatch" edge to the DingTalkApprovalDispatch entity.
func (_u *OrderUnlockRequestUpdate) ClearDispatch() *OrderUnlockRequestUpdate {
	_u.mutation.ClearDispatch()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OrderUnlockRequestUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderUnlockRequestUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OrderUnlockRequestUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderUnlockRequestUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderUnlockRequestUpdate) check() error {
	if v, ok := _u.mutation.Reason(); ok {
		if err := orderunlockrequest.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "OrderUnlockRequest.reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := orderunlockrequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OrderUnlockRequest.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DingtalkProcessInstanceID(); ok {
		if err := orderunlockrequest.DingtalkProcessInstanceIDValidator(v); err != nil {
			return &ValidationError{Name: "dingtalk_process_instance_id", err: fmt.Errorf(`ent: validator failed for field "OrderUnlockRequest.dingtalk_process_instance_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DingtalkProcessCode(); ok {
		if err := orderunlockrequest.DingtalkProcessCodeValidator(v); err != nil {
			return &ValidationError{Name: "dingtalk_process_code", err: fmt.Errorf(`ent: validator failed for field "OrderUnlockRequest.dingtalk_process_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DecisionSource(); ok {
		if err := orderunlockrequest.DecisionSourceValidator(v); err != nil {
			return &ValidationError{Name: "decision_source", err: fmt.Errorf(`ent: validator failed for field "OrderUnlockRequest.decision_source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FailureCode(); ok {
		if err := orderunlockrequest.FailureCodeValidator(v); err != nil {
			return &ValidationError{Name: "failure_code", err: fmt.Errorf(`ent: validator failed for field "OrderUnlockRequest.failure_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FailureMessage(); ok {
		if err := orderunlockrequest.FailureMessageValidator(v); err != nil {
			return &ValidationError{Name: "failure_message", err: fmt.Errorf(`ent: validator failed for field "OrderUnlockRequest.failure_message": %w`, err)}
		}
	}
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrderUnlockRequest.organization"`)
	}
	if _u.mutation.OrderCleared() && len(_u.mutation.OrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrderUnlockRequest.order"`)
	}
	if _u.mutation.LockRecordCleared() && len(_u.mutation.LockRecordIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrderUnlockRequest.lock_record"`)
	}
	if _u.mutation.RequestedByUserCleared() && len(_u.mutation.RequestedByUserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrderUnlockRequest.requested_by_user"`)
	}
	return nil
}

func (_u *OrderUnlockRequestUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(orderunlockrequest.Table, orderunlockrequest.Columns, sqlgraph.NewFieldSpec(orderunlockrequest.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(orderunlockrequest.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(orderunlockrequest.FieldReason, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(orderunlockrequest.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DingtalkProcessInstanceID(); ok {
		_spec.SetField(orderunlockrequest.FieldDingtalkProcessInstanceID, field.TypeString, value)
	}
	if _u.mutation.DingtalkProcessInstanceIDCleared() {
		_spec.ClearField(orderunlockrequest.FieldDingtalkProcessInstanceID, field.TypeString)
	}
	if value, ok := _u.mutation.DingtalkProcessCode(); ok {
		_spec.SetField(orderunlockrequest.FieldDingtalkProcessCode, field.TypeString, value)
	}
	if _u.mutation.DingtalkProcessCodeCleared() {
		_spec.ClearField(orderunlockrequest.FieldDingtalkProcessCode, field.TypeString)
	}
	if value, ok := _u.mutation.DecidedAt(); ok {
		_spec.SetField(orderunlockrequest.FieldDecidedAt, field.TypeTime, value)
	}
	if _u.mutation.DecidedAtCleared() {
		_spec.ClearField(orderunlockrequest.FieldDecidedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DecisionSource(); ok {
		_spec.SetField(orderunlockrequest.FieldDecisionSource, field.TypeString, value)
	}
	if _u.mutation.DecisionSourceCleared() {
		_spec.ClearField(orderunlockrequest.FieldDecisionSource, field.TypeString)
	}
	if value, ok := _u.mutation.FailureCode(); ok {
		_spec.SetField(orderunlockrequest.FieldFailureCode, field.TypeString, value)
	}
	if _u.mutation.FailureCodeCleared() {
		_spec.ClearField(orderunlockrequest.FieldFailureCode, field.TypeString)
	}
	if value, ok := _u.mutation.FailureMessage(); ok {
		_spec.SetField(orderunlockrequest.FieldFailureMessage, field.TypeString, value)
	}
	if _u.mutation.FailureMessageCleared() {
		_spec.ClearField(orderunlockrequest.FieldFailureMessage, field.TypeString)
	}
	if value, ok := _u.mutation.UnlockedAt(); ok {
		_spec.SetField(orderunlockrequest.FieldUnlockedAt, field.TypeTime, value)
	}
	if _u.mutation.UnlockedAtCleared() {
		_spec.ClearField(orderunlockrequest.FieldUnlockedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ResultOrderVersion(); ok {
		_spec.SetField(orderunlockrequest.FieldResultOrderVersion, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedResultOrderVersion(); ok {
		_spec.AddField(orderunlockrequest.FieldResultOrderVersion, field.TypeUint64, value)
	}
	if _u.mutation.ResultOrderVersionCleared() {
		_spec.ClearField(orderunlockrequest.FieldResultOrderVersion, field.TypeUint64)
	}
	if _u.mutation.DecidedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderunlockrequest.DecidedByUserTable,
			Columns: []string{orderunlockrequest.DecidedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DecidedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderunlockrequest.DecidedByUserTable,
			Columns: []string{orderunlockrequest.DecidedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SupersededByRequestCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   orderunlockrequest.SupersededByRequestTable,
			Columns: []string{orderunlockrequest.SupersededByRequestColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderunlockrequest.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SupersededByRequestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   orderunlockrequest.SupersededByRequestTable,
			Columns: []string{orderunlockrequest.SupersededByRequestColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderunlockrequest.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SupersededRequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   orderunlockrequest.SupersededRequestsTable,
			Columns: []string{orderunlockrequest.SupersededRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderunlockrequest.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSupersededRequestsIDs(); len(nodes) > 0 && !_u.mutation.SupersededRequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   orderunlockrequest.SupersededRequestsTable,
			Columns: []string{orderunlockrequest.SupersededRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderunlockrequest.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SupersededRequestsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   orderunlockrequest.SupersededRequestsTable,
			Columns: []string{orderunlockrequest.SupersededRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderunlockrequest.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ApproverCandidatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   orderunlockrequest.ApproverCandidatesTable,
			Columns: []string{orderunlockrequest.ApproverCandidatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderunlockapprovercandidate.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedApproverCandidatesIDs(); len(nodes) > 0 && !_u.mutation.ApproverCandidatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   orderunlockrequest.ApproverCandidatesTable,
			Columns: []string{orderunlockrequest.ApproverCandidatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderunlockapprovercandidate.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ApproverCandidatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   orderunlockrequest.ApproverCandidatesTable,
			Columns: []string{orderunlockrequest.ApproverCandidatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderunlockapprovercandidate.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DispatchCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   orderunlockrequest.DispatchTable,
			Columns: []string{orderunlockrequest.DispatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dingtalkapprovaldispatch.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DispatchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   orderunlockrequest.DispatchTable,
			Columns: []string{orderunlockrequest.DispatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dingtalkapprovaldispatch.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orderunlockrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OrderUnlockRequestUpdateOne is the builder for updating a single OrderUnlockRequest entity.
type OrderUnlockRequestUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrderUnlockRequestMutation
}

// SetReason sets the "reason" field.
func (_u *OrderUnlockRequestUpdateOne) SetReason(v string) *OrderUnlockRequestUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *OrderUnlockRequestUpdateOne) SetNillableReason(v *string) *OrderUnlockRequestUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *OrderUnlockRequestUpdateOne) ClearReason() *OrderUnlockRequestUpdateOne {
	_u.mutation.ClearReason()
	return _u
}

// SetStatus sets the "status" field.
func (_u *OrderUnlockRequestUpdateOne) SetStatus(v orderunlockrequest.Status) *OrderUnlockRequestUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OrderUnlockRequestUpdateOne) SetNillableStatus(v *orderunlockrequest.Status) *OrderUnlockRequestUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDingtalkProcessInstanceID sets the "dingtalk_process_instance_id" field.
func (_u *OrderUnlockRequestUpdateOne) SetDingtalkProcessInstanceID(v string) *OrderUnlockRequestUpdateOne {
	_u.mutation.SetDingtalkProcessInstanceID(v)
	return _u
}

// SetNillableDingtalkProcessInstanceID sets the "dingtalk_process_instance_id" field if the given value is not nil.
func (_u *OrderUnlockRequestUpdateOne) SetNillableDingtalkProcessInstanceID(v *string) *OrderUnlockRequestUpdateOne {
	if v != nil {
		_u.SetDingtalkProcessInstanceID(*v)
	}
	return _u
}

// ClearDingtalkProcessInstanceID clears the value of the "dingtalk_process_instance_id" field.
func (_u *OrderUnlockRequestUpdateOne) ClearDingtalkProcessInstanceID() *OrderUnlockRequestUpdateOne {
	_u.mutation.ClearDingtalkProcessInstanceID()
	return _u
}

// SetDingtalkProcessCode sets the "dingtalk_process_code" field.
func (_u *OrderUnlockRequestUpdateOne) SetDingtalkProcessCode(v string) *OrderUnlockRequestUpdateOne {
	_u.mutation.SetDingtalkProcessCode(v)
	return _u
}

// SetNillableDingtalkProcessCode sets the "dingtalk_process_code" field if the given value is not nil.
func (_u *OrderUnlockRequestUpdateOne) SetNillableDingtalkProcessCode(v *string) *OrderUnlockRequestUpdateOne {
	if v != nil {
		_u.SetDingtalkProcessCode(*v)
	}
	return _u
}

// ClearDingtalkProcessCode clears the value of the "dingtalk_process_code" field.
func (_u *OrderUnlockRequestUpdateOne) ClearDingtalkProcessCode() *OrderUnlockRequestUpdateOne {
	_u.mutation.ClearDingtalkProcessCode()
	return _u
}

// SetDecidedBy sets the "decided_by" field.
func (_u *OrderUnlockRequestUpdateOne) SetDecidedBy(v uuid.UUID) *OrderUnlockRequestUpdateOne {
	_u.mutation.SetDecidedBy(v)
	return _u
}

// SetNillableDecidedBy sets the "decided_by" field if the given value is not nil.
func (_u *OrderUnlockRequestUpdateOne) SetNillableDecidedBy(v *uuid.UUID) *OrderUnlockRequestUpdateOne {
	if v != nil {
		_u.SetDecidedBy(*v)
	}
	return _u
}

// ClearDecidedBy clears the value of the "decided_by" field.
func (_u *OrderUnlockRequestUpdateOne) ClearDecidedBy() *OrderUnlockRequestUpdateOne {
	_u.mutation.ClearDecidedBy()
	return _u
}

// SetDecidedAt sets the "decided_at" field.
func (_u *OrderUnlockRequestUpdateOne) SetDecidedAt(v time.Time) *OrderUnlockRequestUpdateOne {
	_u.mutation.SetDecidedAt(v)
	return _u
}

// SetNillableDecidedAt sets the "decided_at" field if the given value is not nil.
func (_u *OrderUnlockRequestUpdateOne) SetNillableDecidedAt(v *time.Time) *OrderUnlockRequestUpdateOne {
	if v != nil {
		_u.SetDecidedAt(*v)
	}
	return _u
}

// ClearDecidedAt clears the value of the "decided_at" field.
func (_u *OrderUnlockRequestUpdateOne) ClearDecidedAt() *OrderUnlockRequestUpdateOne {
	_u.mutation.ClearDecidedAt()
	return _u
}

// SetDecisionSource sets the "decision_source" field.
func (_u *OrderUnlockRequestUpdateOne) SetDecisionSource(v string) *OrderUnlockRequestUpdateOne {
	_u.mutation.SetDecisionSource(v)
	return _u
}

// SetNillableDecisionSource sets the "decision_source" field if the given value is not nil.
func (_u *OrderUnlockRequestUpdateOne) SetNillableDecisionSource(v *string) *OrderUnlockRequestUpdateOne {
	if v != nil {
		_u.SetDecisionSource(*v)
	}
	return _u
}

// ClearDecisionSource clears the value of the "decision_source" field.
func (_u *OrderUnlockRequestUpdateOne) ClearDecisionSource() *OrderUnlockRequestUpdateOne {
	_u.mutation.ClearDecisionSource()
	return _u
}

// SetFailureCode sets the "failure_code" field.
func (_u *OrderUnlockRequestUpdateOne) SetFailureCode(v string) *OrderUnlockRequestUpdateOne {
	_u.mutation.SetFailureCode(v)
	return _u
}

// SetNillableFailureCode sets the "failure_code" field if the given value is not nil.
func (_u *OrderUnlockRequestUpdateOne) SetNillableFailureCode(v *string) *OrderUnlockRequestUpdateOne {
	if v != nil {
		_u.SetFailureCode(*v)
	}
	return _u
}

// ClearFailureCode clears the value of the "failure_code" field.
func (_u *OrderUnlockRequestUpdateOne) ClearFailureCode() *OrderUnlockRequestUpdateOne {
	_u.mutation.ClearFailureCode()
	return _u
}

// SetFailureMessage sets the "failure_message" field.
func (_u *OrderUnlockRequestUpdateOne) SetFailureMessage(v string) *OrderUnlockRequestUpdateOne {
	_u.mutation.SetFailureMessage(v)
	return _u
}

// SetNillableFailureMessage sets the "failure_message" field if the given value is not nil.
func (_u *OrderUnlockRequestUpdateOne) SetNillableFailureMessage(v *string) *OrderUnlockRequestUpdateOne {
	if v != nil {
		_u.SetFailureMessage(*v)
	}
	return _u
}

// ClearFailureMessage clears the value of the "failure_message" field.
func (_u *OrderUnlockRequestUpdateOne) ClearFailureMessage() *OrderUnlockRequestUpdateOne {
	_u.mutation.ClearFailureMessage()
	return _u
}

// SetSupersededByRequestID sets the "superseded_by_request_id" field.
func (_u *OrderUnlockRequestUpdateOne) SetSupersededByRequestID(v uuid.UUID) *OrderUnlockRequestUpdateOne {
	_u.mutation.SetSupersededByRequestID(v)
	return _u
}

// SetNillableSupersededByRequestID sets the "superseded_by_request_id" field if the given value is not nil.
func (_u *OrderUnlockRequestUpdateOne) SetNillableSupersededByRequestID(v *uuid.UUID) *OrderUnlockRequestUpdateOne {
	if v != nil {
		_u.SetSupersededByRequestID(*v)
	}
	return _u
}

// ClearSupersededByRequestID clears the value of the "superseded_by_request_id" field.
func (_u *OrderUnlockRequestUpdateOne) ClearSupersededByRequestID() *OrderUnlockRequestUpdateOne {
	_u.mutation.ClearSupersededByRequestID()
	return _u
}

// SetUnlockedAt sets the "unlocked_at" field.
func (_u *OrderUnlockRequestUpdateOne) SetUnlockedAt(v time.Time) *OrderUnlockRequestUpdateOne {
	_u.mutation.SetUnlockedAt(v)
	return _u
}

// SetNillableUnlockedAt sets the "unlocked_at" field if the given value is not nil.
func (_u *OrderUnlockRequestUpdateOne) SetNillableUnlockedAt(v *time.Time) *OrderUnlockRequestUpdateOne {
	if v != nil {
		_u.SetUnlockedAt(*v)
	}
	return _u
}

// ClearUnlockedAt clears the value of the "unlocked_at" field.
func (_u *OrderUnlockRequestUpdateOne) ClearUnlockedAt() *OrderUnlockRequestUpdateOne {
	_u.mutation.ClearUnlockedAt()
	return _u
}

// SetResultOrderVersion sets the "result_order_version" field.
func (_u *OrderUnlockRequestUpdateOne) SetResultOrderVersion(v uint64) *OrderUnlockRequestUpdateOne {
	_u.mutation.ResetResultOrderVersion()
	_u.mutation.SetResultOrderVersion(v)
	return _u
}

// SetNillableResultOrderVersion sets the "result_order_version" field if the given value is not nil.
func (_u *OrderUnlockRequestUpdateOne) SetNillableResultOrderVersion(v *uint64) *OrderUnlockRequestUpdateOne {
	if v != nil {
		_u.SetResultOrderVersion(*v)
	}
	return _u
}

// AddResultOrderVersion adds value to the "result_order_version" field.
func (_u *OrderUnlockRequestUpdateOne) AddResultOrderVersion(v int64) *OrderUnlockRequestUpdateOne {
	_u.mutation.AddResultOrderVersion(v)
	return _u
}

// ClearResultOrderVersion clears the value of the "result_order_version" field.
func (_u *OrderUnlockRequestUpdateOne) ClearResultOrderVersion() *OrderUnlockRequestUpdateOne {
	_u.mutation.ClearResultOrderVersion()
	return _u
}

// SetDecidedByUserID sets the "decided_by_user" edge to the User entity by ID.
func (_u *OrderUnlockRequestUpdateOne) SetDecidedByUserID(id uuid.UUID) *OrderUnlockRequestUpdateOne {
	_u.mutation.SetDecidedByUserID(id)
	return _u
}

// SetNillableDecidedByUserID sets the "decided_by_user" edge to the User entity by ID if the given value is not nil.
func (_u *OrderUnlockRequestUpdateOne) SetNillableDecidedByUserID(id *uuid.UUID) *OrderUnlockRequestUpdateOne {
	if id != nil {
		_u = _u.SetDecidedByUserID(*id)
	}
	return _u
}

// SetDecidedByUser sets the "decided_by_user" edge to the User entity.
func (_u *OrderUnlockRequestUpdateOne) SetDecidedByUser(v *User) *OrderUnlockRequestUpdateOne {
	return _u.SetDecidedByUserID(v.ID)
}

// SetSupersededByRequest sets the "superseded_by_request" edge to the OrderUnlockRequest entity.
func (_u *OrderUnlockRequestUpdateOne) SetSupersededByRequest(v *OrderUnlockRequest) *OrderUnlockRequestUpdateOne {
	return _u.SetSupersededByRequestID(v.ID)
}

// AddSupersededRequestIDs adds the "superseded_requests" edge to the OrderUnlockRequest entity by IDs.
func (_u *OrderUnlockRequestUpdateOne) AddSupersededRequestIDs(ids ...uuid.UUID) *OrderUnlockRequestUpdateOne {
	_u.mutation.AddSupersededRequestIDs(ids...)
	return _u
}

// AddSupersededRequests adds the "superseded_requests" edges to the OrderUnlockRequest entity.
func (_u *OrderUnlockRequestUpdateOne) AddSupersededRequests(v ...*OrderUnlockRequest) *OrderUnlockRequestUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSupersededRequestIDs(ids...)
}

// AddApproverCandidateIDs adds the "approver_candidates" edge to the OrderUnlockApproverCandidate entity by IDs.
func (_u *OrderUnlockRequestUpdateOne) AddApproverCandidateIDs(ids ...uuid.UUID) *OrderUnlockRequestUpdateOne {
	_u.mutation.AddApproverCandidateIDs(ids...)
	return _u
}

// AddApproverCandidates adds the "approver_candidates" edges to the OrderUnlockApproverCandidate entity.
func (_u *OrderUnlockRequestUpdateOne) AddApproverCandidates(v ...*OrderUnlockApproverCandidate) *OrderUnlockRequestUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddApproverCandidateIDs(ids...)
}

// SetDispatchID sets the "dispatch" edge to the DingTalkApprovalDispatch entity by ID.
func (_u *OrderUnlockRequestUpdateOne) SetDispatchID(id uuid.UUID) *OrderUnlockRequestUpdateOne {
	_u.mutation.SetDispatchID(id)
	return _u
}

// SetNillableDispatchID sets the "dispatch" edge to the DingTalkApprovalDispatch entity by ID if the given value is not nil.
func (_u *OrderUnlockRequestUpdateOne) SetNillableDispatchID(id *uuid.UUID) *OrderUnlockRequestUpdateOne {
	if id != nil {
		_u = _u.SetDispatchID(*id)
	}
	return _u
}

// SetDispatch sets the "dispatch" edge to the DingTalkApprovalDispatch entity.
func (_u *OrderUnlockRequestUpdateOne) SetDispatch(v *DingTalkApprovalDispatch) *OrderUnlockRequestUpdateOne {
	return _u.SetDispatchID(v.ID)
}

// Mutation returns the OrderUnlockRequestMutation object of the builder.
func (_u *OrderUnlockRequestUpdateOne) Mutation() *OrderUnlockRequestMutation {
	return _u.mutation
}

// ClearDecidedByUser clears the "decided_by_user" edge to the User entity.
func (_u *OrderUnlockRequestUpdateOne) ClearDecidedByUser() *OrderUnlockRequestUpdateOne {
	_u.mutation.ClearDecidedByUser()
	return _u
}

// ClearSupersededByRequest clears the "superseded_by_request" edge to the OrderUnlockRequest entity.
func (_u *OrderUnlockRequestUpdateOne) ClearSupersededByRequest() *OrderUnlockRequestUpdateOne {
	_u.mutation.ClearSupersededByRequest()
	return _u
}

// ClearSupersededRequests clears all "superseded_requests" edges to the OrderUnlockRequest entity.
func (_u *OrderUnlockRequestUpdateOne) ClearSupersededRequests() *OrderUnlockRequestUpdateOne {
	_u.mutation.ClearSupersededRequests()
	return _u
}

// RemoveSupersededRequestIDs removes the "superseded_requests" edge to OrderUnlockRequest entities by IDs.
func (_u *OrderUnlockRequestUpdateOne) RemoveSupersededRequestIDs(ids ...uuid.UUID) *OrderUnlockRequestUpdateOne {
	_u.mutation.RemoveSupersededRequestIDs(ids...)
	return _u
}

// RemoveSupersededRequests removes "superseded_requests" edges to OrderUnlockRequest entities.
func (_u *OrderUnlockRequestUpdateOne) RemoveSupersededRequests(v ...*OrderUnlockRequest) *OrderUnlockRequestUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSupersededRequestIDs(ids...)
}

// ClearApproverCandidates clears all "approver_candidates" edges to the OrderUnlockApproverCandidate entity.
func (_u *OrderUnlockRequestUpdateOne) ClearApproverCandidates() *OrderUnlockRequestUpdateOne {
	_u.mutation.ClearApproverCandidates()
	return _u
}

// RemoveApproverCandidateIDs removes the "approver_candidates" edge to OrderUnlockApproverCandidate entities by IDs.
func (_u *OrderUnlockRequestUpdateOne) RemoveApproverCandidateIDs(ids ...uuid.UUID) *OrderUnlockRequestUpdateOne {
	_u.mutation.RemoveApproverCandidateIDs(ids...)
	return _u
}

// RemoveApproverCandidates removes "approver_candidates" edges to OrderUnlockApproverCandidate entities.
func (_u *OrderUnlockRequestUpdateOne) RemoveApproverCandidates(v ...*OrderUnlockApproverCandidate) *OrderUnlockRequestUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveApproverCandidateIDs(ids...)
}

// ClearDispatch clears the "dispatch" edge to the DingTalkApprovalDispatch entity.
func (_u *OrderUnlockRequestUpdateOne) ClearDispatch() *OrderUnlockRequestUpdateOne {
	_u.mutation.ClearDispatch()
	return _u
}

// Where appends a list predicates to the OrderUnlockRequestUpdate builder.
func (_u *OrderUnlockRequestUpdateOne) Where(ps ...predicate.OrderUnlockRequest) *OrderUnlockRequestUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OrderUnlockRequestUpdateOne) Select(field string, fields ...string) *OrderUnlockRequestUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OrderUnlockRequest entity.
func (_u *OrderUnlockRequestUpdateOne) Save(ctx context.Context) (*OrderUnlockRequest, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderUnlockRequestUpdateOne) SaveX(ctx context.Context) *OrderUnlockRequest {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OrderUnlockRequestUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderUnlockRequestUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderUnlockRequestUpdateOne) check() error {
	if v, ok := _u.mutation.Reason(); ok {
		if err := orderunlockrequest.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "OrderUnlockRequest.reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := orderunlockrequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OrderUnlockRequest.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DingtalkProcessInstanceID(); ok {
		if err := orderunlockrequest.DingtalkProcessInstanceIDValidator(v); err != nil {
			return &ValidationError{Name: "dingtalk_process_instance_id", err: fmt.Errorf(`ent: validator failed for field "OrderUnlockRequest.dingtalk_process_instance_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DingtalkProcessCode(); ok {
		if err := orderunlockrequest.DingtalkProcessCodeValidator(v); err != nil {
			return &ValidationError{Name: "dingtalk_process_code", err: fmt.Errorf(`ent: validator failed for field "OrderUnlockRequest.dingtalk_process_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DecisionSource(); ok {
		if err := orderunlockrequest.DecisionSourceValidator(v); err != nil {
			return &ValidationError{Name: "decision_source", err: fmt.Errorf(`ent: validator failed for field "OrderUnlockRequest.decision_source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FailureCode(); ok {
		if err := orderunlockrequest.FailureCodeValidator(v); err != nil {
			return &ValidationError{Name: "failure_code", err: fmt.Errorf(`ent: validator failed for field "OrderUnlockRequest.failure_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FailureMessage(); ok {
		if err := orderunlockrequest.FailureMessageValidator(v); err != nil {
			return &ValidationError{Name: "failure_message", err: fmt.Errorf(`ent: validator failed for field "OrderUnlockRequest.failure_message": %w`, err)}
		}
	}
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrderUnlockRequest.organization"`)
	}
	if _u.mutation.OrderCleared() && len(_u.mutation.OrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrderUnlockRequest.order"`)
	}
	if _u.mutation.LockRecordCleared() && len(_u.mutation.LockRecordIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrderUnlockRequest.lock_record"`)
	}
	if _u.mutation.RequestedByUserCleared() && len(_u.mutation.RequestedByUserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrderUnlockRequest.requested_by_user"`)
	}
	return nil
}

func (_u *OrderUnlockRequestUpdateOne) sqlSave(ctx context.Context) (_node *OrderUnlockRequest, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(orderunlockrequest.Table, orderunlockrequest.Columns, sqlgraph.NewFieldSpec(orderunlockrequest.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OrderUnlockRequest.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, orderunlockrequest.FieldID)
		for _, f := range fields {
			if !orderunlockrequest.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != orderunlockrequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(orderunlockrequest.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(orderunlockrequest.FieldReason, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(orderunlockrequest.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.DingtalkProcessInstanceID(); ok {
		_spec.SetField(orderunlockrequest.FieldDingtalkProcessInstanceID, field.TypeString, value)
	}
	if _u.mutation.DingtalkProcessInstanceIDCleared() {
		_spec.ClearField(orderunlockrequest.FieldDingtalkProcessInstanceID, field.TypeString)
	}
	if value, ok := _u.mutation.DingtalkProcessCode(); ok {
		_spec.SetField(orderunlockrequest.FieldDingtalkProcessCode, field.TypeString, value)
	}
	if _u.mutation.DingtalkProcessCodeCleared() {
		_spec.ClearField(orderunlockrequest.FieldDingtalkProcessCode, field.TypeString)
	}
	if value, ok := _u.mutation.DecidedAt(); ok {
		_spec.SetField(orderunlockrequest.FieldDecidedAt, field.TypeTime, value)
	}
	if _u.mutation.DecidedAtCleared() {
		_spec.ClearField(orderunlockrequest.FieldDecidedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DecisionSource(); ok {
		_spec.SetField(orderunlockrequest.FieldDecisionSource, field.TypeString, value)
	}
	if _u.mutation.DecisionSourceCleared() {
		_spec.ClearField(orderunlockrequest.FieldDecisionSource, field.TypeString)
	}
	if value, ok := _u.mutation.FailureCode(); ok {
		_spec.SetField(orderunlockrequest.FieldFailureCode, field.TypeString, value)
	}
	if _u.mutation.FailureCodeCleared() {
		_spec.ClearField(orderunlockrequest.FieldFailureCode, field.TypeString)
	}
	if value, ok := _u.mutation.FailureMessage(); ok {
		_spec.SetField(orderunlockrequest.FieldFailureMessage, field.TypeString, value)
	}
	if _u.mutation.FailureMessageCleared() {
		_spec.ClearField(orderunlockrequest.FieldFailureMessage, field.TypeString)
	}
	if value, ok := _u.mutation.UnlockedAt(); ok {
		_spec.SetField(orderunlockrequest.FieldUnlockedAt, field.TypeTime, value)
	}
	if _u.mutation.UnlockedAtCleared() {
		_spec.ClearField(orderunlockrequest.FieldUnlockedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ResultOrderVersion(); ok {
		_spec.SetField(orderunlockrequest.FieldResultOrderVersion, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedResultOrderVersion(); ok {
		_spec.AddField(orderunlockrequest.FieldResultOrderVersion, field.TypeUint64, value)
	}
	if _u.mutation.ResultOrderVersionCleared() {
		_spec.ClearField(orderunlockrequest.FieldResultOrderVersion, field.TypeUint64)
	}
	if _u.mutation.DecidedByUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderunlockrequest.DecidedByUserTable,
			Columns: []string{orderunlockrequest.DecidedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DecidedByUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderunlockrequest.DecidedByUserTable,
			Columns: []string{orderunlockrequest.DecidedByUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SupersededByRequestCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   orderunlockrequest.SupersededByRequestTable,
			Columns: []string{orderunlockrequest.SupersededByRequestColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderunlockrequest.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SupersededByRequestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   orderunlockrequest.SupersededByRequestTable,
			Columns: []string{orderunlockrequest.SupersededByRequestColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderunlockrequest.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SupersededRequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   orderunlockrequest.SupersededRequestsTable,
			Columns: []string{orderunlockrequest.SupersededRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderunlockrequest.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSupersededRequestsIDs(); len(nodes) > 0 && !_u.mutation.SupersededRequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   orderunlockrequest.SupersededRequestsTable,
			Columns: []string{orderunlockrequest.SupersededRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderunlockrequest.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SupersededRequestsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   orderunlockrequest.SupersededRequestsTable,
			Columns: []string{orderunlockrequest.SupersededRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderunlockrequest.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ApproverCandidatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   orderunlockrequest.ApproverCandidatesTable,
			Columns: []string{orderunlockrequest.ApproverCandidatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderunlockapprovercandidate.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedApproverCandidatesIDs(); len(nodes) > 0 && !_u.mutation.ApproverCandidatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   orderunlockrequest.ApproverCandidatesTable,
			Columns: []string{orderunlockrequest.ApproverCandidatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderunlockapprovercandidate.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ApproverCandidatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   orderunlockrequest.ApproverCandidatesTable,
			Columns: []string{orderunlockrequest.ApproverCandidatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderunlockapprovercandidate.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DispatchCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   orderunlockrequest.DispatchTable,
			Columns: []string{orderunlockrequest.DispatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dingtalkapprovaldispatch.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DispatchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   orderunlockrequest.DispatchTable,
			Columns: []string{orderunlockrequest.DispatchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(dingtalkapprovaldispatch.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OrderUnlockRequest{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orderunlockrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
