// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/orderpersonnel"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/predicate"
)

// OrderPersonnelDelete is the builder for deleting a OrderPersonnel entity.
type OrderPersonnelDelete struct {
	config
	hooks    []Hook
	mutation *OrderPersonnelMutation
}

// Where appends a list predicates to the OrderPersonnelDelete builder.
func (_d *OrderPersonnelDelete) Where(ps ...predicate.OrderPersonnel) *OrderPersonnelDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OrderPersonnelDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OrderPersonnelDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OrderPersonnelDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(orderpersonnel.Table, sqlgraph.NewFieldSpec(orderpersonnel.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OrderPersonnelDeleteOne is the builder for deleting a single OrderPersonnel entity.
type OrderPersonnelDeleteOne struct {
	_d *OrderPersonnelDelete
}

// Where appends a list predicates to the OrderPersonnelDelete builder.
func (_d *OrderPersonnelDeleteOne) Where(ps ...predicate.OrderPersonnel) *OrderPersonnelDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OrderPersonnelDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{orderpersonnel.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OrderPersonnelDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
