// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/order"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/ordercargocategory"
)

// OrderCargoCategoryCreate is the builder for creating a OrderCargoCategory entity.
type OrderCargoCategoryCreate struct {
	config
	mutation *OrderCargoCategoryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *OrderCargoCategoryCreate) SetCreatedAt(v time.Time) *OrderCargoCategoryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OrderCargoCategoryCreate) SetNillableCreatedAt(v *time.Time) *OrderCargoCategoryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OrderCargoCategoryCreate) SetUpdatedAt(v time.Time) *OrderCargoCategoryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OrderCargoCategoryCreate) SetNillableUpdatedAt(v *time.Time) *OrderCargoCategoryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetOrderID sets the "order_id" field.
func (_c *OrderCargoCategoryCreate) SetOrderID(v uuid.UUID) *OrderCargoCategoryCreate {
	_c.mutation.SetOrderID(v)
	return _c
}

// SetMasterDataItemID sets the "master_data_item_id" field.
func (_c *OrderCargoCategoryCreate) SetMasterDataItemID(v uuid.UUID) *OrderCargoCategoryCreate {
	_c.mutation.SetMasterDataItemID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *OrderCargoCategoryCreate) SetID(v uuid.UUID) *OrderCargoCategoryCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *OrderCargoCategoryCreate) SetNillableID(v *uuid.UUID) *OrderCargoCategoryCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetOrder sets the "order" edge to the Order entity.
func (_c *OrderCargoCategoryCreate) SetOrder(v *Order) *OrderCargoCategoryCreate {
	return _c.SetOrderID(v.ID)
}

// Mutation returns the OrderCargoCategoryMutation object of the builder.
func (_c *OrderCargoCategoryCreate) Mutation() *OrderCargoCategoryMutation {
	return _c.mutation
}

// Save creates the OrderCargoCategory in the database.
func (_c *OrderCargoCategoryCreate) Save(ctx context.Context) (*OrderCargoCategory, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OrderCargoCategoryCreate) SaveX(ctx context.Context) *OrderCargoCategory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrderCargoCategoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrderCargoCategoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OrderCargoCategoryCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ordercargocategory.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := ordercargocategory.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := ordercargocategory.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OrderCargoCategoryCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OrderCargoCategory.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OrderCargoCategory.updated_at"`)}
	}
	if _, ok := _c.mutation.OrderID(); !ok {
		return &ValidationError{Name: "order_id", err: errors.New(`ent: missing required field "OrderCargoCategory.order_id"`)}
	}
	if _, ok := _c.mutation.MasterDataItemID(); !ok {
		return &ValidationError{Name: "master_data_item_id", err: errors.New(`ent: missing required field "OrderCargoCategory.master_data_item_id"`)}
	}
	if len(_c.mutation.OrderIDs()) == 0 {
		return &ValidationError{Name: "order", err: errors.New(`ent: missing required edge "OrderCargoCategory.order"`)}
	}
	return nil
}

func (_c *OrderCargoCategoryCreate) sqlSave(ctx context.Context) (*OrderCargoCategory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OrderCargoCategoryCreate) createSpec() (*OrderCargoCategory, *sqlgraph.CreateSpec) {
	var (
		_node = &OrderCargoCategory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ordercargocategory.Table, sqlgraph.NewFieldSpec(ordercargocategory.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ordercargocategory.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(ordercargocategory.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.MasterDataItemID(); ok {
		_spec.SetField(ordercargocategory.FieldMasterDataItemID, field.TypeUUID, value)
		_node.MasterDataItemID = value
	}
	if nodes := _c.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ordercargocategory.OrderTable,
			Columns: []string{ordercargocategory.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrderID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OrderCargoCategory.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OrderCargoCategoryUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OrderCargoCategoryCreate) OnConflict(opts ...sql.ConflictOption) *OrderCargoCategoryUpsertOne {
	_c.conflict = opts
	return &OrderCargoCategoryUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OrderCargoCategory.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OrderCargoCategoryCreate) OnConflictColumns(columns ...string) *OrderCargoCategoryUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OrderCargoCategoryUpsertOne{
		create: _c,
	}
}

type (
	// OrderCargoCategoryUpsertOne is the builder for "upsert"-ing
	//  one OrderCargoCategory node.
	OrderCargoCategoryUpsertOne struct {
		create *OrderCargoCategoryCreate
	}

	// OrderCargoCategoryUpsert is the "OnConflict" setter.
	OrderCargoCategoryUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OrderCargoCategoryUpsert) SetUpdatedAt(v time.Time) *OrderCargoCategoryUpsert {
	u.Set(ordercargocategory.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrderCargoCategoryUpsert) UpdateUpdatedAt() *OrderCargoCategoryUpsert {
	u.SetExcluded(ordercargocategory.FieldUpdatedAt)
	return u
}

// SetOrderID sets the "order_id" field.
func (u *OrderCargoCategoryUpsert) SetOrderID(v uuid.UUID) *OrderCargoCategoryUpsert {
	u.Set(ordercargocategory.FieldOrderID, v)
	return u
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *OrderCargoCategoryUpsert) UpdateOrderID() *OrderCargoCategoryUpsert {
	u.SetExcluded(ordercargocategory.FieldOrderID)
	return u
}

// SetMasterDataItemID sets the "master_data_item_id" field.
func (u *OrderCargoCategoryUpsert) SetMasterDataItemID(v uuid.UUID) *OrderCargoCategoryUpsert {
	u.Set(ordercargocategory.FieldMasterDataItemID, v)
	return u
}

// UpdateMasterDataItemID sets the "master_data_item_id" field to the value that was provided on create.
func (u *OrderCargoCategoryUpsert) UpdateMasterDataItemID() *OrderCargoCategoryUpsert {
	u.SetExcluded(ordercargocategory.FieldMasterDataItemID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.OrderCargoCategory.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(ordercargocategory.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OrderCargoCategoryUpsertOne) UpdateNewValues() *OrderCargoCategoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(ordercargocategory.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(ordercargocategory.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OrderCargoCategory.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OrderCargoCategoryUpsertOne) Ignore() *OrderCargoCategoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OrderCargoCategoryUpsertOne) DoNothing() *OrderCargoCategoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OrderCargoCategoryCreate.OnConflict
// documentation for more info.
func (u *OrderCargoCategoryUpsertOne) Update(set func(*OrderCargoCategoryUpsert)) *OrderCargoCategoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OrderCargoCategoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OrderCargoCategoryUpsertOne) SetUpdatedAt(v time.Time) *OrderCargoCategoryUpsertOne {
	return u.Update(func(s *OrderCargoCategoryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrderCargoCategoryUpsertOne) UpdateUpdatedAt() *OrderCargoCategoryUpsertOne {
	return u.Update(func(s *OrderCargoCategoryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetOrderID sets the "order_id" field.
func (u *OrderCargoCategoryUpsertOne) SetOrderID(v uuid.UUID) *OrderCargoCategoryUpsertOne {
	return u.Update(func(s *OrderCargoCategoryUpsert) {
		s.SetOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *OrderCargoCategoryUpsertOne) UpdateOrderID() *OrderCargoCategoryUpsertOne {
	return u.Update(func(s *OrderCargoCategoryUpsert) {
		s.UpdateOrderID()
	})
}

// SetMasterDataItemID sets the "master_data_item_id" field.
func (u *OrderCargoCategoryUpsertOne) SetMasterDataItemID(v uuid.UUID) *OrderCargoCategoryUpsertOne {
	return u.Update(func(s *OrderCargoCategoryUpsert) {
		s.SetMasterDataItemID(v)
	})
}

// UpdateMasterDataItemID sets the "master_data_item_id" field to the value that was provided on create.
func (u *OrderCargoCategoryUpsertOne) UpdateMasterDataItemID() *OrderCargoCategoryUpsertOne {
	return u.Update(func(s *OrderCargoCategoryUpsert) {
		s.UpdateMasterDataItemID()
	})
}

// Exec executes the query.
func (u *OrderCargoCategoryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OrderCargoCategoryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OrderCargoCategoryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OrderCargoCategoryUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: OrderCargoCategoryUpsertOne.ID is not supported by MySQL driver. Use OrderCargoCategoryUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OrderCargoCategoryUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OrderCargoCategoryCreateBulk is the builder for creating many OrderCargoCategory entities in bulk.
type OrderCargoCategoryCreateBulk struct {
	config
	err      error
	builders []*OrderCargoCategoryCreate
	conflict []sql.ConflictOption
}

// Save creates the OrderCargoCategory entities in the database.
func (_c *OrderCargoCategoryCreateBulk) Save(ctx context.Context) ([]*OrderCargoCategory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OrderCargoCategory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrderCargoCategoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OrderCargoCategoryCreateBulk) SaveX(ctx context.Context) []*OrderCargoCategory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrderCargoCategoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrderCargoCategoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OrderCargoCategory.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OrderCargoCategoryUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *OrderCargoCategoryCreateBulk) OnConflict(opts ...sql.ConflictOption) *OrderCargoCategoryUpsertBulk {
	_c.conflict = opts
	return &OrderCargoCategoryUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OrderCargoCategory.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OrderCargoCategoryCreateBulk) OnConflictColumns(columns ...string) *OrderCargoCategoryUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OrderCargoCategoryUpsertBulk{
		create: _c,
	}
}

// OrderCargoCategoryUpsertBulk is the builder for "upsert"-ing
// a bulk of OrderCargoCategory nodes.
type OrderCargoCategoryUpsertBulk struct {
	create *OrderCargoCategoryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OrderCargoCategory.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(ordercargocategory.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OrderCargoCategoryUpsertBulk) UpdateNewValues() *OrderCargoCategoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(ordercargocategory.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(ordercargocategory.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OrderCargoCategory.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OrderCargoCategoryUpsertBulk) Ignore() *OrderCargoCategoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OrderCargoCategoryUpsertBulk) DoNothing() *OrderCargoCategoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OrderCargoCategoryCreateBulk.OnConflict
// documentation for more info.
func (u *OrderCargoCategoryUpsertBulk) Update(set func(*OrderCargoCategoryUpsert)) *OrderCargoCategoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OrderCargoCategoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OrderCargoCategoryUpsertBulk) SetUpdatedAt(v time.Time) *OrderCargoCategoryUpsertBulk {
	return u.Update(func(s *OrderCargoCategoryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrderCargoCategoryUpsertBulk) UpdateUpdatedAt() *OrderCargoCategoryUpsertBulk {
	return u.Update(func(s *OrderCargoCategoryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetOrderID sets the "order_id" field.
func (u *OrderCargoCategoryUpsertBulk) SetOrderID(v uuid.UUID) *OrderCargoCategoryUpsertBulk {
	return u.Update(func(s *OrderCargoCategoryUpsert) {
		s.SetOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *OrderCargoCategoryUpsertBulk) UpdateOrderID() *OrderCargoCategoryUpsertBulk {
	return u.Update(func(s *OrderCargoCategoryUpsert) {
		s.UpdateOrderID()
	})
}

// SetMasterDataItemID sets the "master_data_item_id" field.
func (u *OrderCargoCategoryUpsertBulk) SetMasterDataItemID(v uuid.UUID) *OrderCargoCategoryUpsertBulk {
	return u.Update(func(s *OrderCargoCategoryUpsert) {
		s.SetMasterDataItemID(v)
	})
}

// UpdateMasterDataItemID sets the "master_data_item_id" field to the value that was provided on create.
func (u *OrderCargoCategoryUpsertBulk) UpdateMasterDataItemID() *OrderCargoCategoryUpsertBulk {
	return u.Update(func(s *OrderCargoCategoryUpsert) {
		s.UpdateMasterDataItemID()
	})
}

// Exec executes the query.
func (u *OrderCargoCategoryUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OrderCargoCategoryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OrderCargoCategoryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OrderCargoCategoryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
