// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/financeinvoice"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/partnerinvoiceprofile"
	"github.com/roncin/roncin-go-admin/server/internal/data/ent/predicate"
)

// PartnerInvoiceProfileUpdate is the builder for updating PartnerInvoiceProfile entities.
type PartnerInvoiceProfileUpdate struct {
	config
	hooks    []Hook
	mutation *PartnerInvoiceProfileMutation
}

// Where appends a list predicates to the PartnerInvoiceProfileUpdate builder.
func (_u *PartnerInvoiceProfileUpdate) Where(ps ...predicate.PartnerInvoiceProfile) *PartnerInvoiceProfileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PartnerInvoiceProfileUpdate) SetUpdatedAt(v time.Time) *PartnerInvoiceProfileUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetInvoiceTitle sets the "invoice_title" field.
func (_u *PartnerInvoiceProfileUpdate) SetInvoiceTitle(v string) *PartnerInvoiceProfileUpdate {
	_u.mutation.SetInvoiceTitle(v)
	return _u
}

// SetNillableInvoiceTitle sets the "invoice_title" field if the given value is not nil.
func (_u *PartnerInvoiceProfileUpdate) SetNillableInvoiceTitle(v *string) *PartnerInvoiceProfileUpdate {
	if v != nil {
		_u.SetInvoiceTitle(*v)
	}
	return _u
}

// SetTaxpayerIdentificationNo sets the "taxpayer_identification_no" field.
func (_u *PartnerInvoiceProfileUpdate) SetTaxpayerIdentificationNo(v string) *PartnerInvoiceProfileUpdate {
	_u.mutation.SetTaxpayerIdentificationNo(v)
	return _u
}

// SetNillableTaxpayerIdentificationNo sets the "taxpayer_identification_no" field if the given value is not nil.
func (_u *PartnerInvoiceProfileUpdate) SetNillableTaxpayerIdentificationNo(v *string) *PartnerInvoiceProfileUpdate {
	if v != nil {
		_u.SetTaxpayerIdentificationNo(*v)
	}
	return _u
}

// SetRegisteredAddress sets the "registered_address" field.
func (_u *PartnerInvoiceProfileUpdate) SetRegisteredAddress(v string) *PartnerInvoiceProfileUpdate {
	_u.mutation.SetRegisteredAddress(v)
	return _u
}

// SetNillableRegisteredAddress sets the "registered_address" field if the given value is not nil.
func (_u *PartnerInvoiceProfileUpdate) SetNillableRegisteredAddress(v *string) *PartnerInvoiceProfileUpdate {
	if v != nil {
		_u.SetRegisteredAddress(*v)
	}
	return _u
}

// ClearRegisteredAddress clears the value of the "registered_address" field.
func (_u *PartnerInvoiceProfileUpdate) ClearRegisteredAddress() *PartnerInvoiceProfileUpdate {
	_u.mutation.ClearRegisteredAddress()
	return _u
}

// SetRegisteredPhone sets the "registered_phone" field.
func (_u *PartnerInvoiceProfileUpdate) SetRegisteredPhone(v string) *PartnerInvoiceProfileUpdate {
	_u.mutation.SetRegisteredPhone(v)
	return _u
}

// SetNillableRegisteredPhone sets the "registered_phone" field if the given value is not nil.
func (_u *PartnerInvoiceProfileUpdate) SetNillableRegisteredPhone(v *string) *PartnerInvoiceProfileUpdate {
	if v != nil {
		_u.SetRegisteredPhone(*v)
	}
	return _u
}

// ClearRegisteredPhone clears the value of the "registered_phone" field.
func (_u *PartnerInvoiceProfileUpdate) ClearRegisteredPhone() *PartnerInvoiceProfileUpdate {
	_u.mutation.ClearRegisteredPhone()
	return _u
}

// SetBankName sets the "bank_name" field.
func (_u *PartnerInvoiceProfileUpdate) SetBankName(v string) *PartnerInvoiceProfileUpdate {
	_u.mutation.SetBankName(v)
	return _u
}

// SetNillableBankName sets the "bank_name" field if the given value is not nil.
func (_u *PartnerInvoiceProfileUpdate) SetNillableBankName(v *string) *PartnerInvoiceProfileUpdate {
	if v != nil {
		_u.SetBankName(*v)
	}
	return _u
}

// ClearBankName clears the value of the "bank_name" field.
func (_u *PartnerInvoiceProfileUpdate) ClearBankName() *PartnerInvoiceProfileUpdate {
	_u.mutation.ClearBankName()
	return _u
}

// SetBankAccount sets the "bank_account" field.
func (_u *PartnerInvoiceProfileUpdate) SetBankAccount(v string) *PartnerInvoiceProfileUpdate {
	_u.mutation.SetBankAccount(v)
	return _u
}

// SetNillableBankAccount sets the "bank_account" field if the given value is not nil.
func (_u *PartnerInvoiceProfileUpdate) SetNillableBankAccount(v *string) *PartnerInvoiceProfileUpdate {
	if v != nil {
		_u.SetBankAccount(*v)
	}
	return _u
}

// ClearBankAccount clears the value of the "bank_account" field.
func (_u *PartnerInvoiceProfileUpdate) ClearBankAccount() *PartnerInvoiceProfileUpdate {
	_u.mutation.ClearBankAccount()
	return _u
}

// SetDefaultInvoiceType sets the "default_invoice_type" field.
func (_u *PartnerInvoiceProfileUpdate) SetDefaultInvoiceType(v partnerinvoiceprofile.DefaultInvoiceType) *PartnerInvoiceProfileUpdate {
	_u.mutation.SetDefaultInvoiceType(v)
	return _u
}

// SetNillableDefaultInvoiceType sets the "default_invoice_type" field if the given value is not nil.
func (_u *PartnerInvoiceProfileUpdate) SetNillableDefaultInvoiceType(v *partnerinvoiceprofile.DefaultInvoiceType) *PartnerInvoiceProfileUpdate {
	if v != nil {
		_u.SetDefaultInvoiceType(*v)
	}
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *PartnerInvoiceProfileUpdate) SetIsDefault(v bool) *PartnerInvoiceProfileUpdate {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *PartnerInvoiceProfileUpdate) SetNillableIsDefault(v *bool) *PartnerInvoiceProfileUpdate {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *PartnerInvoiceProfileUpdate) SetEnabled(v bool) *PartnerInvoiceProfileUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *PartnerInvoiceProfileUpdate) SetNillableEnabled(v *bool) *PartnerInvoiceProfileUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *PartnerInvoiceProfileUpdate) SetVersion(v uint64) *PartnerInvoiceProfileUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *PartnerInvoiceProfileUpdate) SetNillableVersion(v *uint64) *PartnerInvoiceProfileUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *PartnerInvoiceProfileUpdate) AddVersion(v int64) *PartnerInvoiceProfileUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// AddFinanceInvoiceIDs adds the "finance_invoices" edge to the FinanceInvoice entity by IDs.
func (_u *PartnerInvoiceProfileUpdate) AddFinanceInvoiceIDs(ids ...uuid.UUID) *PartnerInvoiceProfileUpdate {
	_u.mutation.AddFinanceInvoiceIDs(ids...)
	return _u
}

// AddFinanceInvoices adds the "finance_invoices" edges to the FinanceInvoice entity.
func (_u *PartnerInvoiceProfileUpdate) AddFinanceInvoices(v ...*FinanceInvoice) *PartnerInvoiceProfileUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFinanceInvoiceIDs(ids...)
}

// Mutation returns the PartnerInvoiceProfileMutation object of the builder.
func (_u *PartnerInvoiceProfileUpdate) Mutation() *PartnerInvoiceProfileMutation {
	return _u.mutation
}

// ClearFinanceInvoices clears all "finance_invoices" edges to the FinanceInvoice entity.
func (_u *PartnerInvoiceProfileUpdate) ClearFinanceInvoices() *PartnerInvoiceProfileUpdate {
	_u.mutation.ClearFinanceInvoices()
	return _u
}

// RemoveFinanceInvoiceIDs removes the "finance_invoices" edge to FinanceInvoice entities by IDs.
func (_u *PartnerInvoiceProfileUpdate) RemoveFinanceInvoiceIDs(ids ...uuid.UUID) *PartnerInvoiceProfileUpdate {
	_u.mutation.RemoveFinanceInvoiceIDs(ids...)
	return _u
}

// RemoveFinanceInvoices removes "finance_invoices" edges to FinanceInvoice entities.
func (_u *PartnerInvoiceProfileUpdate) RemoveFinanceInvoices(v ...*FinanceInvoice) *PartnerInvoiceProfileUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFinanceInvoiceIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PartnerInvoiceProfileUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PartnerInvoiceProfileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PartnerInvoiceProfileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PartnerInvoiceProfileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PartnerInvoiceProfileUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := partnerinvoiceprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PartnerInvoiceProfileUpdate) check() error {
	if v, ok := _u.mutation.InvoiceTitle(); ok {
		if err := partnerinvoiceprofile.InvoiceTitleValidator(v); err != nil {
			return &ValidationError{Name: "invoice_title", err: fmt.Errorf(`ent: validator failed for field "PartnerInvoiceProfile.invoice_title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaxpayerIdentificationNo(); ok {
		if err := partnerinvoiceprofile.TaxpayerIdentificationNoValidator(v); err != nil {
			return &ValidationError{Name: "taxpayer_identification_no", err: fmt.Errorf(`ent: validator failed for field "PartnerInvoiceProfile.taxpayer_identification_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RegisteredAddress(); ok {
		if err := partnerinvoiceprofile.RegisteredAddressValidator(v); err != nil {
			return &ValidationError{Name: "registered_address", err: fmt.Errorf(`ent: validator failed for field "PartnerInvoiceProfile.registered_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RegisteredPhone(); ok {
		if err := partnerinvoiceprofile.RegisteredPhoneValidator(v); err != nil {
			return &ValidationError{Name: "registered_phone", err: fmt.Errorf(`ent: validator failed for field "PartnerInvoiceProfile.registered_phone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BankName(); ok {
		if err := partnerinvoiceprofile.BankNameValidator(v); err != nil {
			return &ValidationError{Name: "bank_name", err: fmt.Errorf(`ent: validator failed for field "PartnerInvoiceProfile.bank_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BankAccount(); ok {
		if err := partnerinvoiceprofile.BankAccountValidator(v); err != nil {
			return &ValidationError{Name: "bank_account", err: fmt.Errorf(`ent: validator failed for field "PartnerInvoiceProfile.bank_account": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultInvoiceType(); ok {
		if err := partnerinvoiceprofile.DefaultInvoiceTypeValidator(v); err != nil {
			return &ValidationError{Name: "default_invoice_type", err: fmt.Errorf(`ent: validator failed for field "PartnerInvoiceProfile.default_invoice_type": %w`, err)}
		}
	}
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PartnerInvoiceProfile.organization"`)
	}
	if _u.mutation.PartnerCleared() && len(_u.mutation.PartnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PartnerInvoiceProfile.partner"`)
	}
	return nil
}

func (_u *PartnerInvoiceProfileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(partnerinvoiceprofile.Table, partnerinvoiceprofile.Columns, sqlgraph.NewFieldSpec(partnerinvoiceprofile.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(partnerinvoiceprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.InvoiceTitle(); ok {
		_spec.SetField(partnerinvoiceprofile.FieldInvoiceTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaxpayerIdentificationNo(); ok {
		_spec.SetField(partnerinvoiceprofile.FieldTaxpayerIdentificationNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.RegisteredAddress(); ok {
		_spec.SetField(partnerinvoiceprofile.FieldRegisteredAddress, field.TypeString, value)
	}
	if _u.mutation.RegisteredAddressCleared() {
		_spec.ClearField(partnerinvoiceprofile.FieldRegisteredAddress, field.TypeString)
	}
	if value, ok := _u.mutation.RegisteredPhone(); ok {
		_spec.SetField(partnerinvoiceprofile.FieldRegisteredPhone, field.TypeString, value)
	}
	if _u.mutation.RegisteredPhoneCleared() {
		_spec.ClearField(partnerinvoiceprofile.FieldRegisteredPhone, field.TypeString)
	}
	if value, ok := _u.mutation.BankName(); ok {
		_spec.SetField(partnerinvoiceprofile.FieldBankName, field.TypeString, value)
	}
	if _u.mutation.BankNameCleared() {
		_spec.ClearField(partnerinvoiceprofile.FieldBankName, field.TypeString)
	}
	if value, ok := _u.mutation.BankAccount(); ok {
		_spec.SetField(partnerinvoiceprofile.FieldBankAccount, field.TypeString, value)
	}
	if _u.mutation.BankAccountCleared() {
		_spec.ClearField(partnerinvoiceprofile.FieldBankAccount, field.TypeString)
	}
	if value, ok := _u.mutation.DefaultInvoiceType(); ok {
		_spec.SetField(partnerinvoiceprofile.FieldDefaultInvoiceType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(partnerinvoiceprofile.FieldIsDefault, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(partnerinvoiceprofile.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(partnerinvoiceprofile.FieldVersion, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(partnerinvoiceprofile.FieldVersion, field.TypeUint64, value)
	}
	if _u.mutation.FinanceInvoicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   partnerinvoiceprofile.FinanceInvoicesTable,
			Columns: []string{partnerinvoiceprofile.FinanceInvoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(financeinvoice.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFinanceInvoicesIDs(); len(nodes) > 0 && !_u.mutation.FinanceInvoicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   partnerinvoiceprofile.FinanceInvoicesTable,
			Columns: []string{partnerinvoiceprofile.FinanceInvoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(financeinvoice.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FinanceInvoicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   partnerinvoiceprofile.FinanceInvoicesTable,
			Columns: []string{partnerinvoiceprofile.FinanceInvoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(financeinvoice.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{partnerinvoiceprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PartnerInvoiceProfileUpdateOne is the builder for updating a single PartnerInvoiceProfile entity.
type PartnerInvoiceProfileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PartnerInvoiceProfileMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PartnerInvoiceProfileUpdateOne) SetUpdatedAt(v time.Time) *PartnerInvoiceProfileUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetInvoiceTitle sets the "invoice_title" field.
func (_u *PartnerInvoiceProfileUpdateOne) SetInvoiceTitle(v string) *PartnerInvoiceProfileUpdateOne {
	_u.mutation.SetInvoiceTitle(v)
	return _u
}

// SetNillableInvoiceTitle sets the "invoice_title" field if the given value is not nil.
func (_u *PartnerInvoiceProfileUpdateOne) SetNillableInvoiceTitle(v *string) *PartnerInvoiceProfileUpdateOne {
	if v != nil {
		_u.SetInvoiceTitle(*v)
	}
	return _u
}

// SetTaxpayerIdentificationNo sets the "taxpayer_identification_no" field.
func (_u *PartnerInvoiceProfileUpdateOne) SetTaxpayerIdentificationNo(v string) *PartnerInvoiceProfileUpdateOne {
	_u.mutation.SetTaxpayerIdentificationNo(v)
	return _u
}

// SetNillableTaxpayerIdentificationNo sets the "taxpayer_identification_no" field if the given value is not nil.
func (_u *PartnerInvoiceProfileUpdateOne) SetNillableTaxpayerIdentificationNo(v *string) *PartnerInvoiceProfileUpdateOne {
	if v != nil {
		_u.SetTaxpayerIdentificationNo(*v)
	}
	return _u
}

// SetRegisteredAddress sets the "registered_address" field.
func (_u *PartnerInvoiceProfileUpdateOne) SetRegisteredAddress(v string) *PartnerInvoiceProfileUpdateOne {
	_u.mutation.SetRegisteredAddress(v)
	return _u
}

// SetNillableRegisteredAddress sets the "registered_address" field if the given value is not nil.
func (_u *PartnerInvoiceProfileUpdateOne) SetNillableRegisteredAddress(v *string) *PartnerInvoiceProfileUpdateOne {
	if v != nil {
		_u.SetRegisteredAddress(*v)
	}
	return _u
}

// ClearRegisteredAddress clears the value of the "registered_address" field.
func (_u *PartnerInvoiceProfileUpdateOne) ClearRegisteredAddress() *PartnerInvoiceProfileUpdateOne {
	_u.mutation.ClearRegisteredAddress()
	return _u
}

// SetRegisteredPhone sets the "registered_phone" field.
func (_u *PartnerInvoiceProfileUpdateOne) SetRegisteredPhone(v string) *PartnerInvoiceProfileUpdateOne {
	_u.mutation.SetRegisteredPhone(v)
	return _u
}

// SetNillableRegisteredPhone sets the "registered_phone" field if the given value is not nil.
func (_u *PartnerInvoiceProfileUpdateOne) SetNillableRegisteredPhone(v *string) *PartnerInvoiceProfileUpdateOne {
	if v != nil {
		_u.SetRegisteredPhone(*v)
	}
	return _u
}

// ClearRegisteredPhone clears the value of the "registered_phone" field.
func (_u *PartnerInvoiceProfileUpdateOne) ClearRegisteredPhone() *PartnerInvoiceProfileUpdateOne {
	_u.mutation.ClearRegisteredPhone()
	return _u
}

// SetBankName sets the "bank_name" field.
func (_u *PartnerInvoiceProfileUpdateOne) SetBankName(v string) *PartnerInvoiceProfileUpdateOne {
	_u.mutation.SetBankName(v)
	return _u
}

// SetNillableBankName sets the "bank_name" field if the given value is not nil.
func (_u *PartnerInvoiceProfileUpdateOne) SetNillableBankName(v *string) *PartnerInvoiceProfileUpdateOne {
	if v != nil {
		_u.SetBankName(*v)
	}
	return _u
}

// ClearBankName clears the value of the "bank_name" field.
func (_u *PartnerInvoiceProfileUpdateOne) ClearBankName() *PartnerInvoiceProfileUpdateOne {
	_u.mutation.ClearBankName()
	return _u
}

// SetBankAccount sets the "bank_account" field.
func (_u *PartnerInvoiceProfileUpdateOne) SetBankAccount(v string) *PartnerInvoiceProfileUpdateOne {
	_u.mutation.SetBankAccount(v)
	return _u
}

// SetNillableBankAccount sets the "bank_account" field if the given value is not nil.
func (_u *PartnerInvoiceProfileUpdateOne) SetNillableBankAccount(v *string) *PartnerInvoiceProfileUpdateOne {
	if v != nil {
		_u.SetBankAccount(*v)
	}
	return _u
}

// ClearBankAccount clears the value of the "bank_account" field.
func (_u *PartnerInvoiceProfileUpdateOne) ClearBankAccount() *PartnerInvoiceProfileUpdateOne {
	_u.mutation.ClearBankAccount()
	return _u
}

// SetDefaultInvoiceType sets the "default_invoice_type" field.
func (_u *PartnerInvoiceProfileUpdateOne) SetDefaultInvoiceType(v partnerinvoiceprofile.DefaultInvoiceType) *PartnerInvoiceProfileUpdateOne {
	_u.mutation.SetDefaultInvoiceType(v)
	return _u
}

// SetNillableDefaultInvoiceType sets the "default_invoice_type" field if the given value is not nil.
func (_u *PartnerInvoiceProfileUpdateOne) SetNillableDefaultInvoiceType(v *partnerinvoiceprofile.DefaultInvoiceType) *PartnerInvoiceProfileUpdateOne {
	if v != nil {
		_u.SetDefaultInvoiceType(*v)
	}
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *PartnerInvoiceProfileUpdateOne) SetIsDefault(v bool) *PartnerInvoiceProfileUpdateOne {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *PartnerInvoiceProfileUpdateOne) SetNillableIsDefault(v *bool) *PartnerInvoiceProfileUpdateOne {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *PartnerInvoiceProfileUpdateOne) SetEnabled(v bool) *PartnerInvoiceProfileUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *PartnerInvoiceProfileUpdateOne) SetNillableEnabled(v *bool) *PartnerInvoiceProfileUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *PartnerInvoiceProfileUpdateOne) SetVersion(v uint64) *PartnerInvoiceProfileUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *PartnerInvoiceProfileUpdateOne) SetNillableVersion(v *uint64) *PartnerInvoiceProfileUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *PartnerInvoiceProfileUpdateOne) AddVersion(v int64) *PartnerInvoiceProfileUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// AddFinanceInvoiceIDs adds the "finance_invoices" edge to the FinanceInvoice entity by IDs.
func (_u *PartnerInvoiceProfileUpdateOne) AddFinanceInvoiceIDs(ids ...uuid.UUID) *PartnerInvoiceProfileUpdateOne {
	_u.mutation.AddFinanceInvoiceIDs(ids...)
	return _u
}

// AddFinanceInvoices adds the "finance_invoices" edges to the FinanceInvoice entity.
func (_u *PartnerInvoiceProfileUpdateOne) AddFinanceInvoices(v ...*FinanceInvoice) *PartnerInvoiceProfileUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFinanceInvoiceIDs(ids...)
}

// Mutation returns the PartnerInvoiceProfileMutation object of the builder.
func (_u *PartnerInvoiceProfileUpdateOne) Mutation() *PartnerInvoiceProfileMutation {
	return _u.mutation
}

// ClearFinanceInvoices clears all "finance_invoices" edges to the FinanceInvoice entity.
func (_u *PartnerInvoiceProfileUpdateOne) ClearFinanceInvoices() *PartnerInvoiceProfileUpdateOne {
	_u.mutation.ClearFinanceInvoices()
	return _u
}

// RemoveFinanceInvoiceIDs removes the "finance_invoices" edge to FinanceInvoice entities by IDs.
func (_u *PartnerInvoiceProfileUpdateOne) RemoveFinanceInvoiceIDs(ids ...uuid.UUID) *PartnerInvoiceProfileUpdateOne {
	_u.mutation.RemoveFinanceInvoiceIDs(ids...)
	return _u
}

// RemoveFinanceInvoices removes "finance_invoices" edges to FinanceInvoice entities.
func (_u *PartnerInvoiceProfileUpdateOne) RemoveFinanceInvoices(v ...*FinanceInvoice) *PartnerInvoiceProfileUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFinanceInvoiceIDs(ids...)
}

// Where appends a list predicates to the PartnerInvoiceProfileUpdate builder.
func (_u *PartnerInvoiceProfileUpdateOne) Where(ps ...predicate.PartnerInvoiceProfile) *PartnerInvoiceProfileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PartnerInvoiceProfileUpdateOne) Select(field string, fields ...string) *PartnerInvoiceProfileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PartnerInvoiceProfile entity.
func (_u *PartnerInvoiceProfileUpdateOne) Save(ctx context.Context) (*PartnerInvoiceProfile, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PartnerInvoiceProfileUpdateOne) SaveX(ctx context.Context) *PartnerInvoiceProfile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PartnerInvoiceProfileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PartnerInvoiceProfileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PartnerInvoiceProfileUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := partnerinvoiceprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PartnerInvoiceProfileUpdateOne) check() error {
	if v, ok := _u.mutation.InvoiceTitle(); ok {
		if err := partnerinvoiceprofile.InvoiceTitleValidator(v); err != nil {
			return &ValidationError{Name: "invoice_title", err: fmt.Errorf(`ent: validator failed for field "PartnerInvoiceProfile.invoice_title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaxpayerIdentificationNo(); ok {
		if err := partnerinvoiceprofile.TaxpayerIdentificationNoValidator(v); err != nil {
			return &ValidationError{Name: "taxpayer_identification_no", err: fmt.Errorf(`ent: validator failed for field "PartnerInvoiceProfile.taxpayer_identification_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RegisteredAddress(); ok {
		if err := partnerinvoiceprofile.RegisteredAddressValidator(v); err != nil {
			return &ValidationError{Name: "registered_address", err: fmt.Errorf(`ent: validator failed for field "PartnerInvoiceProfile.registered_address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RegisteredPhone(); ok {
		if err := partnerinvoiceprofile.RegisteredPhoneValidator(v); err != nil {
			return &ValidationError{Name: "registered_phone", err: fmt.Errorf(`ent: validator failed for field "PartnerInvoiceProfile.registered_phone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BankName(); ok {
		if err := partnerinvoiceprofile.BankNameValidator(v); err != nil {
			return &ValidationError{Name: "bank_name", err: fmt.Errorf(`ent: validator failed for field "PartnerInvoiceProfile.bank_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BankAccount(); ok {
		if err := partnerinvoiceprofile.BankAccountValidator(v); err != nil {
			return &ValidationError{Name: "bank_account", err: fmt.Errorf(`ent: validator failed for field "PartnerInvoiceProfile.bank_account": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultInvoiceType(); ok {
		if err := partnerinvoiceprofile.DefaultInvoiceTypeValidator(v); err != nil {
			return &ValidationError{Name: "default_invoice_type", err: fmt.Errorf(`ent: validator failed for field "PartnerInvoiceProfile.default_invoice_type": %w`, err)}
		}
	}
	if _u.mutation.OrganizationCleared() && len(_u.mutation.OrganizationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PartnerInvoiceProfile.organization"`)
	}
	if _u.mutation.PartnerCleared() && len(_u.mutation.PartnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PartnerInvoiceProfile.partner"`)
	}
	return nil
}

func (_u *PartnerInvoiceProfileUpdateOne) sqlSave(ctx context.Context) (_node *PartnerInvoiceProfile, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(partnerinvoiceprofile.Table, partnerinvoiceprofile.Columns, sqlgraph.NewFieldSpec(partnerinvoiceprofile.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PartnerInvoiceProfile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, partnerinvoiceprofile.FieldID)
		for _, f := range fields {
			if !partnerinvoiceprofile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != partnerinvoiceprofile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(partnerinvoiceprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.InvoiceTitle(); ok {
		_spec.SetField(partnerinvoiceprofile.FieldInvoiceTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaxpayerIdentificationNo(); ok {
		_spec.SetField(partnerinvoiceprofile.FieldTaxpayerIdentificationNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.RegisteredAddress(); ok {
		_spec.SetField(partnerinvoiceprofile.FieldRegisteredAddress, field.TypeString, value)
	}
	if _u.mutation.RegisteredAddressCleared() {
		_spec.ClearField(partnerinvoiceprofile.FieldRegisteredAddress, field.TypeString)
	}
	if value, ok := _u.mutation.RegisteredPhone(); ok {
		_spec.SetField(partnerinvoiceprofile.FieldRegisteredPhone, field.TypeString, value)
	}
	if _u.mutation.RegisteredPhoneCleared() {
		_spec.ClearField(partnerinvoiceprofile.FieldRegisteredPhone, field.TypeString)
	}
	if value, ok := _u.mutation.BankName(); ok {
		_spec.SetField(partnerinvoiceprofile.FieldBankName, field.TypeString, value)
	}
	if _u.mutation.BankNameCleared() {
		_spec.ClearField(partnerinvoiceprofile.FieldBankName, field.TypeString)
	}
	if value, ok := _u.mutation.BankAccount(); ok {
		_spec.SetField(partnerinvoiceprofile.FieldBankAccount, field.TypeString, value)
	}
	if _u.mutation.BankAccountCleared() {
		_spec.ClearField(partnerinvoiceprofile.FieldBankAccount, field.TypeString)
	}
	if value, ok := _u.mutation.DefaultInvoiceType(); ok {
		_spec.SetField(partnerinvoiceprofile.FieldDefaultInvoiceType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(partnerinvoiceprofile.FieldIsDefault, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(partnerinvoiceprofile.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(partnerinvoiceprofile.FieldVersion, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(partnerinvoiceprofile.FieldVersion, field.TypeUint64, value)
	}
	if _u.mutation.FinanceInvoicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   partnerinvoiceprofile.FinanceInvoicesTable,
			Columns: []string{partnerinvoiceprofile.FinanceInvoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(financeinvoice.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFinanceInvoicesIDs(); len(nodes) > 0 && !_u.mutation.FinanceInvoicesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   partnerinvoiceprofile.FinanceInvoicesTable,
			Columns: []string{partnerinvoiceprofile.FinanceInvoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(financeinvoice.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FinanceInvoicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   partnerinvoiceprofile.FinanceInvoicesTable,
			Columns: []string{partnerinvoiceprofile.FinanceInvoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(financeinvoice.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PartnerInvoiceProfile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{partnerinvoiceprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
