root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/roncin-server.exe ./cmd/server"
bin = "./tmp/roncin-server.exe"
args_bin = ["-conf", "configs"]
include_ext = ["go", "yaml", "yml"]
exclude_dir = ["api", "bin", "tmp", "var", "internal/data/ent", "internal/webassets/dist"]
delay = 500
stop_on_error = true
send_interrupt = true
kill_delay = "500ms"
