syntax = "proto3";

package admin.v1;

option go_package = "github.com/roncin/roncin-go-admin/server/api/admin/v1;v1";

enum ErrorReason {
  ERROR_REASON_ADMIN_UNSPECIFIED = 0;
  ERROR_REASON_ADMIN_ORGANIZATION_NOT_FOUND = 1;
  ERROR_REASON_ADMIN_ORGANIZATION_CODE_EXISTS = 2;
  ERROR_REASON_ADMIN_USER_NOT_FOUND = 3;
  ERROR_REASON_ADMIN_USERNAME_EXISTS = 4;
  ERROR_REASON_ADMIN_ROLE_NOT_FOUND = 5;
  ERROR_REASON_ADMIN_ROLE_CODE_EXISTS = 6;
  ERROR_REASON_ADMIN_PERMISSION_INVALID = 7;
  ERROR_REASON_ADMIN_INVALID_ARGUMENT = 8;
  ERROR_REASON_ADMIN_USER_SELF_DELETE = 9;
}
