// Code generated by ent, DO NOT EDIT.

package financecommissionapplication

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the financecommissionapplication type in the database.
	Label = "finance_commission_application"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldOrganizationID holds the string denoting the organization_id field in the database.
	FieldOrganizationID = "organization_id"
	// FieldEmployeeID holds the string denoting the employee_id field in the database.
	FieldEmployeeID = "employee_id"
	// FieldApplicationMonth holds the string denoting the application_month field in the database.
	FieldApplicationMonth = "application_month"
	// FieldCoverageTo holds the string denoting the coverage_to field in the database.
	FieldCoverageTo = "coverage_to"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldCommissionCount holds the string denoting the commission_count field in the database.
	FieldCommissionCount = "commission_count"
	// FieldBaseCurrency holds the string denoting the base_currency field in the database.
	FieldBaseCurrency = "base_currency"
	// FieldTotalCommissionAmount holds the string denoting the total_commission_amount field in the database.
	FieldTotalCommissionAmount = "total_commission_amount"
	// FieldTotalCnyCommissionAmount holds the string denoting the total_cny_commission_amount field in the database.
	FieldTotalCnyCommissionAmount = "total_cny_commission_amount"
	// FieldSubmittedAt holds the string denoting the submitted_at field in the database.
	FieldSubmittedAt = "submitted_at"
	// FieldSubmittedBy holds the string denoting the submitted_by field in the database.
	FieldSubmittedBy = "submitted_by"
	// FieldDecidedAt holds the string denoting the decided_at field in the database.
	FieldDecidedAt = "decided_at"
	// FieldDecidedBy holds the string denoting the decided_by field in the database.
	FieldDecidedBy = "decided_by"
	// FieldDecisionReason holds the string denoting the decision_reason field in the database.
	FieldDecisionReason = "decision_reason"
	// EdgeOrganization holds the string denoting the organization edge name in mutations.
	EdgeOrganization = "organization"
	// EdgeEmployee holds the string denoting the employee edge name in mutations.
	EdgeEmployee = "employee"
	// EdgeSubmittedByUser holds the string denoting the submitted_by_user edge name in mutations.
	EdgeSubmittedByUser = "submitted_by_user"
	// EdgeDecidedByUser holds the string denoting the decided_by_user edge name in mutations.
	EdgeDecidedByUser = "decided_by_user"
	// EdgeLines holds the string denoting the lines edge name in mutations.
	EdgeLines = "lines"
	// Table holds the table name of the financecommissionapplication in the database.
	Table = "finance_commission_applications"
	// OrganizationTable is the table that holds the organization relation/edge.
	OrganizationTable = "finance_commission_applications"
	// OrganizationInverseTable is the table name for the Organization entity.
	// It exists in this package in order to avoid circular dependency with the "organization" package.
	OrganizationInverseTable = "organizations"
	// OrganizationColumn is the table column denoting the organization relation/edge.
	OrganizationColumn = "organization_id"
	// EmployeeTable is the table that holds the employee relation/edge.
	EmployeeTable = "finance_commission_applications"
	// EmployeeInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	EmployeeInverseTable = "users"
	// EmployeeColumn is the table column denoting the employee relation/edge.
	EmployeeColumn = "employee_id"
	// SubmittedByUserTable is the table that holds the submitted_by_user relation/edge.
	SubmittedByUserTable = "finance_commission_applications"
	// SubmittedByUserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	SubmittedByUserInverseTable = "users"
	// SubmittedByUserColumn is the table column denoting the submitted_by_user relation/edge.
	SubmittedByUserColumn = "submitted_by"
	// DecidedByUserTable is the table that holds the decided_by_user relation/edge.
	DecidedByUserTable = "finance_commission_applications"
	// DecidedByUserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	DecidedByUserInverseTable = "users"
	// DecidedByUserColumn is the table column denoting the decided_by_user relation/edge.
	DecidedByUserColumn = "decided_by"
	// LinesTable is the table that holds the lines relation/edge.
	LinesTable = "finance_commission_application_lines"
	// LinesInverseTable is the table name for the FinanceCommissionApplicationLine entity.
	// It exists in this package in order to avoid circular dependency with the "financecommissionapplicationline" package.
	LinesInverseTable = "finance_commission_application_lines"
	// LinesColumn is the table column denoting the lines relation/edge.
	LinesColumn = "application_id"
)

// Columns holds all SQL columns for financecommissionapplication fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldOrganizationID,
	FieldEmployeeID,
	FieldApplicationMonth,
	FieldCoverageTo,
	FieldStatus,
	FieldVersion,
	FieldCommissionCount,
	FieldBaseCurrency,
	FieldTotalCommissionAmount,
	FieldTotalCnyCommissionAmount,
	FieldSubmittedAt,
	FieldSubmittedBy,
	FieldDecidedAt,
	FieldDecidedBy,
	FieldDecisionReason,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ApplicationMonthValidator is a validator for the "application_month" field. It is called by the builders before save.
	ApplicationMonthValidator func(string) error
	// CoverageToValidator is a validator for the "coverage_to" field. It is called by the builders before save.
	CoverageToValidator func(string) error
	// DefaultVersion holds the default value on creation for the "version" field.
	DefaultVersion uint64
	// CommissionCountValidator is a validator for the "commission_count" field. It is called by the builders before save.
	CommissionCountValidator func(int) error
	// BaseCurrencyValidator is a validator for the "base_currency" field. It is called by the builders before save.
	BaseCurrencyValidator func(string) error
	// DecisionReasonValidator is a validator for the "decision_reason" field. It is called by the builders before save.
	DecisionReasonValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPENDING_REVIEW is the default value of the Status enum.
const DefaultStatus = StatusPENDING_REVIEW

// Status values.
const (
	StatusPENDING_REVIEW Status = "PENDING_REVIEW"
	StatusREJECTED       Status = "REJECTED"
	StatusAPPROVED       Status = "APPROVED"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPENDING_REVIEW, StatusREJECTED, StatusAPPROVED:
		return nil
	default:
		return fmt.Errorf("financecommissionapplication: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the FinanceCommissionApplication queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByOrganizationID orders the results by the organization_id field.
func ByOrganizationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrganizationID, opts...).ToFunc()
}

// ByEmployeeID orders the results by the employee_id field.
func ByEmployeeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmployeeID, opts...).ToFunc()
}

// ByApplicationMonth orders the results by the application_month field.
func ByApplicationMonth(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApplicationMonth, opts...).ToFunc()
}

// ByCoverageTo orders the results by the coverage_to field.
func ByCoverageTo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCoverageTo, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByCommissionCount orders the results by the commission_count field.
func ByCommissionCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommissionCount, opts...).ToFunc()
}

// ByBaseCurrency orders the results by the base_currency field.
func ByBaseCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseCurrency, opts...).ToFunc()
}

// ByTotalCommissionAmount orders the results by the total_commission_amount field.
func ByTotalCommissionAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalCommissionAmount, opts...).ToFunc()
}

// ByTotalCnyCommissionAmount orders the results by the total_cny_commission_amount field.
func ByTotalCnyCommissionAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalCnyCommissionAmount, opts...).ToFunc()
}

// BySubmittedAt orders the results by the submitted_at field.
func BySubmittedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubmittedAt, opts...).ToFunc()
}

// BySubmittedBy orders the results by the submitted_by field.
func BySubmittedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubmittedBy, opts...).ToFunc()
}

// ByDecidedAt orders the results by the decided_at field.
func ByDecidedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDecidedAt, opts...).ToFunc()
}

// ByDecidedBy orders the results by the decided_by field.
func ByDecidedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDecidedBy, opts...).ToFunc()
}

// ByDecisionReason orders the results by the decision_reason field.
func ByDecisionReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDecisionReason, opts...).ToFunc()
}

// ByOrganizationField orders the results by organization field.
func ByOrganizationField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOrganizationStep(), sql.OrderByField(field, opts...))
	}
}

// ByEmployeeField orders the results by employee field.
func ByEmployeeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEmployeeStep(), sql.OrderByField(field, opts...))
	}
}

// BySubmittedByUserField orders the results by submitted_by_user field.
func BySubmittedByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSubmittedByUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByDecidedByUserField orders the results by decided_by_user field.
func ByDecidedByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDecidedByUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByLinesCount orders the results by lines count.
func ByLinesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newLinesStep(), opts...)
	}
}

// ByLines orders the results by lines terms.
func ByLines(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLinesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newOrganizationStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OrganizationInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OrganizationTable, OrganizationColumn),
	)
}
func newEmployeeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EmployeeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, EmployeeTable, EmployeeColumn),
	)
}
func newSubmittedByUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SubmittedByUserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SubmittedByUserTable, SubmittedByUserColumn),
	)
}
func newDecidedByUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DecidedByUserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DecidedByUserTable, DecidedByUserColumn),
	)
}
func newLinesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LinesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, LinesTable, LinesColumn),
	)
}
