syntax = "proto3";

package partner.v1;

option go_package = "github.com/roncin/roncin-go-admin/server/api/partner/v1;v1";

enum ErrorReason {
  ERROR_REASON_PARTNER_UNSPECIFIED = 0;
  ERROR_REASON_PARTNER_NOT_FOUND = 1;
  ERROR_REASON_PARTNER_CODE_EXISTS = 2;
  ERROR_REASON_PARTNER_NAME_EXISTS = 3;
  ERROR_REASON_PARTNER_USCC_EXISTS = 4;
  ERROR_REASON_PARTNER_ROLE_REQUIRED = 5;
  ERROR_REASON_PARTNER_INVALID_ROLE = 6;
  ERROR_REASON_PARTNER_INVALID_ARGUMENT = 7;
  ERROR_REASON_PARTNER_PRIMARY_CONTACT_CONFLICT = 8;
  ERROR_REASON_PARTNER_ALIAS_EXISTS = 9;
  ERROR_REASON_PARTNER_SUPPLIER_ROLE_REQUIRED = 10;
  ERROR_REASON_PARTNER_BLACKLIST_REASON_REQUIRED = 11;
  ERROR_REASON_PARTNER_BLACKLISTED_SUPPLIER_ROLE = 12;
  ERROR_REASON_PARTNER_ACCOUNT_NOT_FOUND = 13;
  ERROR_REASON_PARTNER_ACCOUNT_INVALID_ARGUMENT = 14;
  ERROR_REASON_PARTNER_ACCOUNT_DEFAULT_CONFLICT = 15;
  ERROR_REASON_PARTNER_CONTRACT_NOT_FOUND = 16;
  ERROR_REASON_PARTNER_CONTRACT_NO_EXISTS = 17;
  ERROR_REASON_PARTNER_CONTRACT_INVALID_ARGUMENT = 18;
  ERROR_REASON_PARTNER_CONTRACT_STATUS_CONFLICT = 19;
  ERROR_REASON_PARTNER_SETTLEMENT_RULE_NOT_FOUND = 20;
  ERROR_REASON_PARTNER_SETTLEMENT_RULE_EXISTS = 21;
  ERROR_REASON_PARTNER_SETTLEMENT_RULE_INVALID_ARGUMENT = 22;
  ERROR_REASON_PARTNER_ATTACHMENT_NOT_FOUND = 23;
  ERROR_REASON_PARTNER_ATTACHMENT_EXISTS = 24;
  ERROR_REASON_PARTNER_ATTACHMENT_INVALID_ARGUMENT = 25;
  ERROR_REASON_PARTNER_TAX_IDENTIFIER_REQUIRED = 26;
}
