// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: access/v1/access.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AccessMode 定义接口进入业务处理前需要执行的访问控制模式。
type AccessMode int32

const (
	AccessMode_ACCESS_MODE_UNSPECIFIED      AccessMode = 0
	AccessMode_ACCESS_MODE_PUBLIC           AccessMode = 1
	AccessMode_ACCESS_MODE_AUTHENTICATED    AccessMode = 2
	AccessMode_ACCESS_MODE_PERMISSION       AccessMode = 3
	AccessMode_ACCESS_MODE_ORDER_PERMISSION AccessMode = 4
)

// Enum value maps for AccessMode.
var (
	AccessMode_name = map[int32]string{
		0: "ACCESS_MODE_UNSPECIFIED",
		1: "ACCESS_MODE_PUBLIC",
		2: "ACCESS_MODE_AUTHENTICATED",
		3: "ACCESS_MODE_PERMISSION",
		4: "ACCESS_MODE_ORDER_PERMISSION",
	}
	AccessMode_value = map[string]int32{
		"ACCESS_MODE_UNSPECIFIED":      0,
		"ACCESS_MODE_PUBLIC":           1,
		"ACCESS_MODE_AUTHENTICATED":    2,
		"ACCESS_MODE_PERMISSION":       3,
		"ACCESS_MODE_ORDER_PERMISSION": 4,
	}
)

func (x AccessMode) Enum() *AccessMode {
	p := new(AccessMode)
	*p = x
	return p
}

func (x AccessMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessMode) Descriptor() protoreflect.EnumDescriptor {
	return file_access_v1_access_proto_enumTypes[0].Descriptor()
}

func (AccessMode) Type() protoreflect.EnumType {
	return &file_access_v1_access_proto_enumTypes[0]
}

func (x AccessMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessMode.Descriptor instead.
func (AccessMode) EnumDescriptor() ([]byte, []int) {
	return file_access_v1_access_proto_rawDescGZIP(), []int{0}
}

// DataScope 定义执行接口所需的最小数据范围。
type DataScope int32

const (
	DataScope_DATA_SCOPE_UNSPECIFIED       DataScope = 0
	DataScope_DATA_SCOPE_ALL               DataScope = 1
	DataScope_DATA_SCOPE_ORGANIZATION      DataScope = 2
	DataScope_DATA_SCOPE_ORGANIZATION_TREE DataScope = 3
	DataScope_DATA_SCOPE_SELF              DataScope = 4
)

// Enum value maps for DataScope.
var (
	DataScope_name = map[int32]string{
		0: "DATA_SCOPE_UNSPECIFIED",
		1: "DATA_SCOPE_ALL",
		2: "DATA_SCOPE_ORGANIZATION",
		3: "DATA_SCOPE_ORGANIZATION_TREE",
		4: "DATA_SCOPE_SELF",
	}
	DataScope_value = map[string]int32{
		"DATA_SCOPE_UNSPECIFIED":       0,
		"DATA_SCOPE_ALL":               1,
		"DATA_SCOPE_ORGANIZATION":      2,
		"DATA_SCOPE_ORGANIZATION_TREE": 3,
		"DATA_SCOPE_SELF":              4,
	}
)

func (x DataScope) Enum() *DataScope {
	p := new(DataScope)
	*p = x
	return p
}

func (x DataScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataScope) Descriptor() protoreflect.EnumDescriptor {
	return file_access_v1_access_proto_enumTypes[1].Descriptor()
}

func (DataScope) Type() protoreflect.EnumType {
	return &file_access_v1_access_proto_enumTypes[1]
}

func (x DataScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataScope.Descriptor instead.
func (DataScope) EnumDescriptor() ([]byte, []int) {
	return file_access_v1_access_proto_rawDescGZIP(), []int{1}
}

// Rule 是 RPC 的访问控制声明。
type Rule struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Mode           AccessMode             `protobuf:"varint,1,opt,name=mode,proto3,enum=access.v1.AccessMode" json:"mode,omitempty"`
	Permission     string                 `protobuf:"bytes,2,opt,name=permission,proto3" json:"permission,omitempty"`
	OrderOperation string                 `protobuf:"bytes,3,opt,name=order_operation,json=orderOperation,proto3" json:"order_operation,omitempty"`
	Scope          DataScope              `protobuf:"varint,4,opt,name=scope,proto3,enum=access.v1.DataScope" json:"scope,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_access_v1_access_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_access_v1_access_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_access_v1_access_proto_rawDescGZIP(), []int{0}
}

func (x *Rule) GetMode() AccessMode {
	if x != nil {
		return x.Mode
	}
	return AccessMode_ACCESS_MODE_UNSPECIFIED
}

func (x *Rule) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

func (x *Rule) GetOrderOperation() string {
	if x != nil {
		return x.OrderOperation
	}
	return ""
}

func (x *Rule) GetScope() DataScope {
	if x != nil {
		return x.Scope
	}
	return DataScope_DATA_SCOPE_UNSPECIFIED
}

var file_access_v1_access_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Rule)(nil),
		Field:         50000,
		Name:          "access.v1.rule",
		Tag:           "bytes,50000,opt,name=rule",
		Filename:      "access/v1/access.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional access.v1.Rule rule = 50000;
	E_Rule = &file_access_v1_access_proto_extTypes[0]
)

var File_access_v1_access_proto protoreflect.FileDescriptor

const file_access_v1_access_proto_rawDesc = "" +
	"\n" +
	"\x16access/v1/access.proto\x12\taccess.v1\x1a google/protobuf/descriptor.proto\"\xa6\x01\n" +
	"\x04Rule\x12)\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x15.access.v1.AccessModeR\x04mode\x12\x1e\n" +
	"\n" +
	"permission\x18\x02 \x01(\tR\n" +
	"permission\x12'\n" +
	"\x0forder_operation\x18\x03 \x01(\tR\x0eorderOperation\x12*\n" +
	"\x05scope\x18\x04 \x01(\x0e2\x14.access.v1.DataScopeR\x05scope*\x9e\x01\n" +
	"\n" +
	"AccessMode\x12\x1b\n" +
	"\x17ACCESS_MODE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ACCESS_MODE_PUBLIC\x10\x01\x12\x1d\n" +
	"\x19ACCESS_MODE_AUTHENTICATED\x10\x02\x12\x1a\n" +
	"\x16ACCESS_MODE_PERMISSION\x10\x03\x12 \n" +
	"\x1cACCESS_MODE_ORDER_PERMISSION\x10\x04*\x8f\x01\n" +
	"\tDataScope\x12\x1a\n" +
	"\x16DATA_SCOPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eDATA_SCOPE_ALL\x10\x01\x12\x1b\n" +
	"\x17DATA_SCOPE_ORGANIZATION\x10\x02\x12 \n" +
	"\x1cDATA_SCOPE_ORGANIZATION_TREE\x10\x03\x12\x13\n" +
	"\x0fDATA_SCOPE_SELF\x10\x04:E\n" +
	"\x04rule\x12\x1e.google.protobuf.MethodOptions\x18І\x03 \x01(\v2\x0f.access.v1.RuleR\x04ruleB;Z9github.com/roncin/roncin-go-admin/server/api/access/v1;v1b\x06proto3"

var (
	file_access_v1_access_proto_rawDescOnce sync.Once
	file_access_v1_access_proto_rawDescData []byte
)

func file_access_v1_access_proto_rawDescGZIP() []byte {
	file_access_v1_access_proto_rawDescOnce.Do(func() {
		file_access_v1_access_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_access_v1_access_proto_rawDesc), len(file_access_v1_access_proto_rawDesc)))
	})
	return file_access_v1_access_proto_rawDescData
}

var file_access_v1_access_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_access_v1_access_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_access_v1_access_proto_goTypes = []any{
	(AccessMode)(0),                    // 0: access.v1.AccessMode
	(DataScope)(0),                     // 1: access.v1.DataScope
	(*Rule)(nil),                       // 2: access.v1.Rule
	(*descriptorpb.MethodOptions)(nil), // 3: google.protobuf.MethodOptions
}
var file_access_v1_access_proto_depIdxs = []int32{
	0, // 0: access.v1.Rule.mode:type_name -> access.v1.AccessMode
	1, // 1: access.v1.Rule.scope:type_name -> access.v1.DataScope
	3, // 2: access.v1.rule:extendee -> google.protobuf.MethodOptions
	2, // 3: access.v1.rule:type_name -> access.v1.Rule
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	3, // [3:4] is the sub-list for extension type_name
	2, // [2:3] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_access_v1_access_proto_init() }
func file_access_v1_access_proto_init() {
	if File_access_v1_access_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_access_v1_access_proto_rawDesc), len(file_access_v1_access_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_access_v1_access_proto_goTypes,
		DependencyIndexes: file_access_v1_access_proto_depIdxs,
		EnumInfos:         file_access_v1_access_proto_enumTypes,
		MessageInfos:      file_access_v1_access_proto_msgTypes,
		ExtensionInfos:    file_access_v1_access_proto_extTypes,
	}.Build()
	File_access_v1_access_proto = out.File
	file_access_v1_access_proto_goTypes = nil
	file_access_v1_access_proto_depIdxs = nil
}
