// 自动生成：依据 server/api/**/error_reason.proto 生成，请勿手工修改。
// 再生成命令：pnpm run generate:proto-constants
export const adminErrorReasons = {
  ADMIN_ORGANIZATION_NOT_FOUND: 'ADMIN_ORGANIZATION_NOT_FOUND',
  ADMIN_ORGANIZATION_CODE_EXISTS: 'ADMIN_ORGANIZATION_CODE_EXISTS',
  ADMIN_USER_NOT_FOUND: 'ADMIN_USER_NOT_FOUND',
  ADMIN_USERNAME_EXISTS: 'ADMIN_USERNAME_EXISTS',
  ADMIN_ROLE_NOT_FOUND: 'ADMIN_ROLE_NOT_FOUND',
  ADMIN_ROLE_CODE_EXISTS: 'ADMIN_ROLE_CODE_EXISTS',
  ADMIN_PERMISSION_INVALID: 'ADMIN_PERMISSION_INVALID',
  ADMIN_INVALID_ARGUMENT: 'ADMIN_INVALID_ARGUMENT',
  ADMIN_USER_SELF_DELETE: 'ADMIN_USER_SELF_DELETE',
} as const;

export type AdminErrorReason = (typeof adminErrorReasons)[keyof typeof adminErrorReasons];

export const authErrorReasons = {
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_SESSION_REQUIRED: 'AUTH_SESSION_REQUIRED',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_PERMISSION_DENIED: 'AUTH_PERMISSION_DENIED',
  AUTH_ORGANIZATION_FORBIDDEN: 'AUTH_ORGANIZATION_FORBIDDEN',
} as const;

export type AuthErrorReason = (typeof authErrorReasons)[keyof typeof authErrorReasons];

export const financeErrorReasons = {
  FEE_EXCHANGE_RATE_MISSING: 'FEE_EXCHANGE_RATE_MISSING',
  FINANCE_BILL_FEE_INVALID: 'FINANCE_BILL_FEE_INVALID',
  FINANCE_BILL_PREVIEW_STALE: 'FINANCE_BILL_PREVIEW_STALE',
  FINANCE_INVOICE_PROFILE_REQUIRED: 'FINANCE_INVOICE_PROFILE_REQUIRED',
  FINANCE_COMMISSION_ADJUSTMENT_EXCEEDS: 'FINANCE_COMMISSION_ADJUSTMENT_EXCEEDS',
  FINANCE_COMMISSION_ADJUSTMENT_TRANSITION: 'FINANCE_COMMISSION_ADJUSTMENT_TRANSITION',
  FINANCE_COMMISSION_SOURCE_CHANGED: 'FINANCE_COMMISSION_SOURCE_CHANGED',
  FINANCE_COMMISSION_UNCONFIRMED_FEES: 'FINANCE_COMMISSION_UNCONFIRMED_FEES',
  FINANCE_COMMISSION_TRANSITION: 'FINANCE_COMMISSION_TRANSITION',
  FINANCE_COMMISSION_RULE_CONFLICT: 'FINANCE_COMMISSION_RULE_CONFLICT',
} as const;

export type FinanceErrorReason = (typeof financeErrorReasons)[keyof typeof financeErrorReasons];

export const masterdataErrorReasons = {
  MASTER_DATA_INVALID_ARGUMENT: 'MASTER_DATA_INVALID_ARGUMENT',
  MASTER_DATA_NOT_FOUND: 'MASTER_DATA_NOT_FOUND',
  MASTER_DATA_CODE_EXISTS: 'MASTER_DATA_CODE_EXISTS',
  MASTER_DATA_INVALID_KIND: 'MASTER_DATA_INVALID_KIND',
  NUMBER_RULE_NOT_FOUND: 'NUMBER_RULE_NOT_FOUND',
  NUMBER_RULE_EXISTS: 'NUMBER_RULE_EXISTS',
  STATUS_TEMPLATE_NOT_FOUND: 'STATUS_TEMPLATE_NOT_FOUND',
  STATUS_TEMPLATE_EXISTS: 'STATUS_TEMPLATE_EXISTS',
  STATUS_TEMPLATE_INVALID: 'STATUS_TEMPLATE_INVALID',
  NUMBER_SEQUENCE_EXHAUSTED: 'NUMBER_SEQUENCE_EXHAUSTED',
  STATUS_TEMPLATE_DEFAULT_CONFLICT: 'STATUS_TEMPLATE_DEFAULT_CONFLICT',
  REFERENCE_DATA_INVALID_ARGUMENT: 'REFERENCE_DATA_INVALID_ARGUMENT',
} as const;

export type MasterdataErrorReason = (typeof masterdataErrorReasons)[keyof typeof masterdataErrorReasons];

export const orderErrorReasons = {
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_INVALID_ARGUMENT: 'ORDER_INVALID_ARGUMENT',
  ORDER_NUMBER_EXISTS: 'ORDER_NUMBER_EXISTS',
  ORDER_CUSTOMER_INVALID: 'ORDER_CUSTOMER_INVALID',
  ORDER_STATUS_INVALID: 'ORDER_STATUS_INVALID',
  ORDER_STATUS_CONFLICT: 'ORDER_STATUS_CONFLICT',
  ORDER_STATUS_TEMPLATE_REQUIRED: 'ORDER_STATUS_TEMPLATE_REQUIRED',
  ORDER_ATTACHMENT_NOT_FOUND: 'ORDER_ATTACHMENT_NOT_FOUND',
  ORDER_ATTACHMENT_EXISTS: 'ORDER_ATTACHMENT_EXISTS',
  ORDER_ATTACHMENT_INVALID_ARGUMENT: 'ORDER_ATTACHMENT_INVALID_ARGUMENT',
  ORDER_PERSONNEL_NOT_FOUND: 'ORDER_PERSONNEL_NOT_FOUND',
  ORDER_PERSONNEL_EXISTS: 'ORDER_PERSONNEL_EXISTS',
  ORDER_PERSONNEL_INVALID_ARGUMENT: 'ORDER_PERSONNEL_INVALID_ARGUMENT',
  ORDER_PERSONNEL_USER_INVALID: 'ORDER_PERSONNEL_USER_INVALID',
  ORDER_CONTAINER_NOT_FOUND: 'ORDER_CONTAINER_NOT_FOUND',
  ORDER_CONTAINER_EXISTS: 'ORDER_CONTAINER_EXISTS',
  ORDER_CONTAINER_INVALID_ARGUMENT: 'ORDER_CONTAINER_INVALID_ARGUMENT',
  ORDER_CONTAINER_SPEC_INVALID: 'ORDER_CONTAINER_SPEC_INVALID',
  ORDER_CARGO_ITEM_NOT_FOUND: 'ORDER_CARGO_ITEM_NOT_FOUND',
  ORDER_CARGO_ITEM_INVALID_ARGUMENT: 'ORDER_CARGO_ITEM_INVALID_ARGUMENT',
  ORDER_SHIPPING_DOCUMENT_NOT_FOUND: 'ORDER_SHIPPING_DOCUMENT_NOT_FOUND',
  ORDER_SHIPPING_DOCUMENT_EXISTS: 'ORDER_SHIPPING_DOCUMENT_EXISTS',
  ORDER_SHIPPING_DOCUMENT_INVALID_ARGUMENT: 'ORDER_SHIPPING_DOCUMENT_INVALID_ARGUMENT',
  ORDER_SHIPPING_DOCUMENT_INVALID_STATUS: 'ORDER_SHIPPING_DOCUMENT_INVALID_STATUS',
  ORDER_SHIPPING_DOCUMENT_STATUS_CONFLICT: 'ORDER_SHIPPING_DOCUMENT_STATUS_CONFLICT',
  ORDER_ABNORMAL_CASE_NOT_FOUND: 'ORDER_ABNORMAL_CASE_NOT_FOUND',
  ORDER_ABNORMAL_CASE_EXISTS: 'ORDER_ABNORMAL_CASE_EXISTS',
  ORDER_ABNORMAL_CASE_INVALID_ARGUMENT: 'ORDER_ABNORMAL_CASE_INVALID_ARGUMENT',
  ORDER_ABNORMAL_CASE_KIND_INVALID: 'ORDER_ABNORMAL_CASE_KIND_INVALID',
  ORDER_ABNORMAL_CASE_STATUS_CONFLICT: 'ORDER_ABNORMAL_CASE_STATUS_CONFLICT',
  ORDER_RELEASE_POD_NOT_FOUND: 'ORDER_RELEASE_POD_NOT_FOUND',
  ORDER_RELEASE_POD_INVALID_ARGUMENT: 'ORDER_RELEASE_POD_INVALID_ARGUMENT',
  ORDER_RELEASE_POD_INVALID_STATUS: 'ORDER_RELEASE_POD_INVALID_STATUS',
  ORDER_RELEASE_POD_STATUS_CONFLICT: 'ORDER_RELEASE_POD_STATUS_CONFLICT',
  ORDER_RELEASE_POD_DOCUMENT_INVALID: 'ORDER_RELEASE_POD_DOCUMENT_INVALID',
  SEA_MASTER_BILL_NOT_FOUND: 'SEA_MASTER_BILL_NOT_FOUND',
  SEA_MASTER_BILL_INVALID_ARGUMENT: 'SEA_MASTER_BILL_INVALID_ARGUMENT',
  SEA_MASTER_BILL_EXISTS: 'SEA_MASTER_BILL_EXISTS',
  SEA_MASTER_BILL_CONFIRMATION_REQUIRED: 'SEA_MASTER_BILL_CONFIRMATION_REQUIRED',
  SEA_MASTER_BILL_VOYAGE_CONFLICT: 'SEA_MASTER_BILL_VOYAGE_CONFLICT',
  SEA_MASTER_BILL_STATUS_CONFLICT: 'SEA_MASTER_BILL_STATUS_CONFLICT',
  SEA_MASTER_BILL_CORRECTION_BLOCKED: 'SEA_MASTER_BILL_CORRECTION_BLOCKED',
  SEA_HOUSE_BILL_NOT_FOUND: 'SEA_HOUSE_BILL_NOT_FOUND',
  SEA_HOUSE_BILL_INVALID_ARGUMENT: 'SEA_HOUSE_BILL_INVALID_ARGUMENT',
  SEA_HOUSE_BILL_EXISTS: 'SEA_HOUSE_BILL_EXISTS',
  SEA_HOUSE_BILL_STATUS_CONFLICT: 'SEA_HOUSE_BILL_STATUS_CONFLICT',
  SEA_DOCUMENT_STRUCTURE_CONFLICT: 'SEA_DOCUMENT_STRUCTURE_CONFLICT',
  SEA_DOCUMENT_STRUCTURE_INVALID: 'SEA_DOCUMENT_STRUCTURE_INVALID',
  SEA_HOUSE_BILL_CONFLICT: 'SEA_HOUSE_BILL_CONFLICT',
  SEA_MASTER_BILL_CONFLICT: 'SEA_MASTER_BILL_CONFLICT',
  SEA_DOCUMENT_NO_ACTIVE_LINK: 'SEA_DOCUMENT_NO_ACTIVE_LINK',
  SEA_BILL_CONTENT_INVALID_ARGUMENT: 'SEA_BILL_CONTENT_INVALID_ARGUMENT',
  ORDER_CUSTOMER_CHANGE_WITH_HOUSE_BILL_BLOCKED: 'ORDER_CUSTOMER_CHANGE_WITH_HOUSE_BILL_BLOCKED',
  SEA_DOCUMENT_DIRECT_ADD_HBL_BLOCKED: 'SEA_DOCUMENT_DIRECT_ADD_HBL_BLOCKED',
  SEA_DOCUMENT_DELETE_LAST_HBL_CONFIRMATION_REQUIRED: 'SEA_DOCUMENT_DELETE_LAST_HBL_CONFIRMATION_REQUIRED',
  SEA_DOCUMENT_INVALID_ARGUMENT: 'SEA_DOCUMENT_INVALID_ARGUMENT',
  SEA_CARGO_ALLOCATION_INVALID_ARGUMENT: 'SEA_CARGO_ALLOCATION_INVALID_ARGUMENT',
  SEA_CARGO_ALLOCATION_INVALID_REFERENCE: 'SEA_CARGO_ALLOCATION_INVALID_REFERENCE',
  SEA_CARGO_ALLOCATION_EXCEEDED: 'SEA_CARGO_ALLOCATION_EXCEEDED',
  SEA_CARGO_ALLOCATION_INCOMPLETE: 'SEA_CARGO_ALLOCATION_INCOMPLETE',
  SEA_CARGO_ALLOCATION_CONFLICT: 'SEA_CARGO_ALLOCATION_CONFLICT',
  SEA_CARGO_ALLOCATION_STATUS_CONFLICT: 'SEA_CARGO_ALLOCATION_STATUS_CONFLICT',
  SEA_ORDER_SPLIT_INVALID_ARGUMENT: 'SEA_ORDER_SPLIT_INVALID_ARGUMENT',
  SEA_ORDER_SPLIT_BLOCKED: 'SEA_ORDER_SPLIT_BLOCKED',
  SEA_ORDER_SPLIT_CONSERVATION_FAILED: 'SEA_ORDER_SPLIT_CONSERVATION_FAILED',
  SEA_ORDER_SPLIT_ENTITY_CROSSES_RESULTS: 'SEA_ORDER_SPLIT_ENTITY_CROSSES_RESULTS',
  SEA_ORDER_SPLIT_VERSION_CONFLICT: 'SEA_ORDER_SPLIT_VERSION_CONFLICT',
  SEA_ORDER_SPLIT_IDEMPOTENCY_CONFLICT: 'SEA_ORDER_SPLIT_IDEMPOTENCY_CONFLICT',
  SEA_ORDER_REASSIGNMENT_INVALID_ARGUMENT: 'SEA_ORDER_REASSIGNMENT_INVALID_ARGUMENT',
  SEA_ORDER_REASSIGNMENT_BLOCKED: 'SEA_ORDER_REASSIGNMENT_BLOCKED',
  SEA_ORDER_REASSIGNMENT_TARGET_CONFLICT: 'SEA_ORDER_REASSIGNMENT_TARGET_CONFLICT',
  SEA_ORDER_REASSIGNMENT_VERSION_CONFLICT: 'SEA_ORDER_REASSIGNMENT_VERSION_CONFLICT',
  SEA_ORDER_REASSIGNMENT_IDEMPOTENCY_CONFLICT: 'SEA_ORDER_REASSIGNMENT_IDEMPOTENCY_CONFLICT',
} as const;

export type OrderErrorReason = (typeof orderErrorReasons)[keyof typeof orderErrorReasons];

export const partnerErrorReasons = {
  PARTNER_NOT_FOUND: 'PARTNER_NOT_FOUND',
  PARTNER_CODE_EXISTS: 'PARTNER_CODE_EXISTS',
  PARTNER_NAME_EXISTS: 'PARTNER_NAME_EXISTS',
  PARTNER_USCC_EXISTS: 'PARTNER_USCC_EXISTS',
  PARTNER_ROLE_REQUIRED: 'PARTNER_ROLE_REQUIRED',
  PARTNER_INVALID_ROLE: 'PARTNER_INVALID_ROLE',
  PARTNER_INVALID_ARGUMENT: 'PARTNER_INVALID_ARGUMENT',
  PARTNER_PRIMARY_CONTACT_CONFLICT: 'PARTNER_PRIMARY_CONTACT_CONFLICT',
  PARTNER_ALIAS_EXISTS: 'PARTNER_ALIAS_EXISTS',
  PARTNER_SUPPLIER_ROLE_REQUIRED: 'PARTNER_SUPPLIER_ROLE_REQUIRED',
  PARTNER_BLACKLIST_REASON_REQUIRED: 'PARTNER_BLACKLIST_REASON_REQUIRED',
  PARTNER_BLACKLISTED_SUPPLIER_ROLE: 'PARTNER_BLACKLISTED_SUPPLIER_ROLE',
  PARTNER_ACCOUNT_NOT_FOUND: 'PARTNER_ACCOUNT_NOT_FOUND',
  PARTNER_ACCOUNT_INVALID_ARGUMENT: 'PARTNER_ACCOUNT_INVALID_ARGUMENT',
  PARTNER_ACCOUNT_DEFAULT_CONFLICT: 'PARTNER_ACCOUNT_DEFAULT_CONFLICT',
  PARTNER_CONTRACT_NOT_FOUND: 'PARTNER_CONTRACT_NOT_FOUND',
  PARTNER_CONTRACT_NO_EXISTS: 'PARTNER_CONTRACT_NO_EXISTS',
  PARTNER_CONTRACT_INVALID_ARGUMENT: 'PARTNER_CONTRACT_INVALID_ARGUMENT',
  PARTNER_CONTRACT_STATUS_CONFLICT: 'PARTNER_CONTRACT_STATUS_CONFLICT',
  PARTNER_SETTLEMENT_RULE_NOT_FOUND: 'PARTNER_SETTLEMENT_RULE_NOT_FOUND',
  PARTNER_SETTLEMENT_RULE_EXISTS: 'PARTNER_SETTLEMENT_RULE_EXISTS',
  PARTNER_SETTLEMENT_RULE_INVALID_ARGUMENT: 'PARTNER_SETTLEMENT_RULE_INVALID_ARGUMENT',
  PARTNER_ATTACHMENT_NOT_FOUND: 'PARTNER_ATTACHMENT_NOT_FOUND',
  PARTNER_ATTACHMENT_EXISTS: 'PARTNER_ATTACHMENT_EXISTS',
  PARTNER_ATTACHMENT_INVALID_ARGUMENT: 'PARTNER_ATTACHMENT_INVALID_ARGUMENT',
  PARTNER_TAX_IDENTIFIER_REQUIRED: 'PARTNER_TAX_IDENTIFIER_REQUIRED',
} as const;

export type PartnerErrorReason = (typeof partnerErrorReasons)[keyof typeof partnerErrorReasons];

export const taskErrorReasons = {
  BACKGROUND_TASK_NOT_FOUND: 'BACKGROUND_TASK_NOT_FOUND',
  BACKGROUND_TASK_INVALID_ARGUMENT: 'BACKGROUND_TASK_INVALID_ARGUMENT',
  BACKGROUND_TASK_EXISTS: 'BACKGROUND_TASK_EXISTS',
  BACKGROUND_TASK_LEASE_MISMATCH: 'BACKGROUND_TASK_LEASE_MISMATCH',
  BACKGROUND_TASK_NO_TASK: 'BACKGROUND_TASK_NO_TASK',
  BACKGROUND_TASK_INVALID_STATUS: 'BACKGROUND_TASK_INVALID_STATUS',
  BACKGROUND_TASK_NOT_REQUEUEABLE: 'BACKGROUND_TASK_NOT_REQUEUEABLE',
} as const;

export type TaskErrorReason = (typeof taskErrorReasons)[keyof typeof taskErrorReasons];
