package main

import "strings"

type airlineMetadata struct {
	NameZH      string
	NameEN      string
	AWBPrefix   string
	CountryCode string
	ICAOCode    string
	CargoOnly   bool
}

var openFlightsCountryToISO2 = map[string]string{
	"afghanistan":                           "AF",
	"albania":                               "AL",
	"alaska":                                "US",
	"algeria":                               "DZ",
	"american samoa":                        "AS",
	"angola":                                "AO",
	"antigua and barbuda":                   "AG",
	"argentina":                             "AR",
	"armenia":                               "AM",
	"aruba":                                 "AW",
	"australia":                             "AU",
	"austria":                               "AT",
	"avianca":                               "CO",
	"azerbaijan":                            "AZ",
	"bahamas":                               "BS",
	"bahrain":                               "BH",
	"bangladesh":                            "BD",
	"barbados":                              "BB",
	"belarus":                               "BY",
	"belgium":                               "BE",
	"belize":                                "BZ",
	"benin":                                 "BJ",
	"bermuda":                               "BM",
	"bhutan":                                "BT",
	"bolivia":                               "BO",
	"bosnia and herzegovina":                "BA",
	"botswana":                              "BW",
	"brazil":                                "BR",
	"british virgin islands":                "VG",
	"brunei":                                "BN",
	"bulgaria":                              "BG",
	"burkina faso":                          "BF",
	"burma":                                 "MM",
	"burundi":                               "BI",
	"cambodia":                              "KH",
	"cameroon":                              "CM",
	"canadian territories":                  "CA",
	"canada":                                "CA",
	"cape verde":                            "CV",
	"cayman islands":                        "KY",
	"central african republic":              "CF",
	"chad":                                  "TD",
	"chile":                                 "CL",
	"china":                                 "CN",
	"colombia":                              "CO",
	"comoros":                               "KM",
	"congo (brazzaville)":                   "CG",
	"congo (kinshasa)":                      "CD",
	"cook islands":                          "CK",
	"costa rica":                            "CR",
	"cote d'ivoire":                         "CI",
	"croatia":                               "HR",
	"cuba":                                  "CU",
	"cyprus":                                "CY",
	"czech republic":                        "CZ",
	"democratic people's republic of korea": "KP",
	"denmark":                               "DK",
	"djibouti":                              "DJ",
	"dominican republic":                    "DO",
	"dr congo":                              "CD",
	"dragon":                                "HK",
	"ecuador":                               "EC",
	"egypt":                                 "EG",
	"el salvador":                           "SV",
	"equatorial guinea":                     "GQ",
	"eritrea":                               "ER",
	"estonia":                               "EE",
	"eswatini":                              "SZ",
	"ethiopia":                              "ET",
	"faeroe islands":                        "FO",
	"faroe islands":                         "FO",
	"fiji":                                  "FJ",
	"finland":                               "FI",
	"france":                                "FR",
	"french guiana":                         "GF",
	"french polynesia":                      "PF",
	"gabon":                                 "GA",
	"gambia":                                "GM",
	"georgia":                               "GE",
	"germany":                               "DE",
	"ghana":                                 "GH",
	"greece":                                "GR",
	"greenland":                             "GL",
	"guadeloupe":                            "GP",
	"guatemala":                             "GT",
	"guinea":                                "GN",
	"guinea-bissau":                         "GW",
	"guyana":                                "GY",
	"haiti":                                 "HT",
	"honduras":                              "HN",
	"hong kong":                             "HK",
	"hong kong sar of china":                "HK",
	"hungary":                               "HU",
	"iceland":                               "IS",
	"india":                                 "IN",
	"indonesia":                             "ID",
	"iran":                                  "IR",
	"iraq":                                  "IQ",
	"ireland":                               "IE",
	"israel":                                "IL",
	"italy":                                 "IT",
	"ivory coast":                           "CI",
	"jamaica":                               "JM",
	"japan":                                 "JP",
	"jordan":                                "JO",
	"kazakhstan":                            "KZ",
	"kenya":                                 "KE",
	"kiribati":                              "KI",
	"kuwait":                                "KW",
	"kyrgyzstan":                            "KG",
	"lao peoples democratic republic":       "LA",
	"laos":                                  "LA",
	"latvia":                                "LV",
	"lebanon":                               "LB",
	"lesotho":                               "LS",
	"liberia":                               "LR",
	"libya":                                 "LY",
	"lithuania":                             "LT",
	"luxembourg":                            "LU",
	"macao":                                 "MO",
	"macau":                                 "MO",
	"macedonia":                             "MK",
	"madagascar":                            "MG",
	"malawi":                                "MW",
	"malaysia":                              "MY",
	"maldives":                              "MV",
	"mali":                                  "ML",
	"malta":                                 "MT",
	"marshall islands":                      "MH",
	"mauritania":                            "MR",
	"mauritius":                             "MU",
	"mexico":                                "MX",
	"micronesia":                            "FM",
	"moldova":                               "MD",
	"monaco":                                "MC",
	"mongolia":                              "MN",
	"montenegro":                            "ME",
	"morocco":                               "MA",
	"mozambique":                            "MZ",
	"myanmar":                               "MM",
	"namibia":                               "NA",
	"nauru":                                 "NR",
	"nepal":                                 "NP",
	"netherlands antilles":                  "BQ",
	"netherlands":                           "NL",
	"new caledonia":                         "NC",
	"new zealand":                           "NZ",
	"nicaragua":                             "NI",
	"niger":                                 "NE",
	"nigeria":                               "NG",
	"north korea":                           "KP",
	"norway":                                "NO",
	"oman":                                  "OM",
	"pakistan":                              "PK",
	"palau":                                 "PW",
	"palestinian territory":                 "PS",
	"panama":                                "PA",
	"papua new guinea":                      "PG",
	"paraguay":                              "PY",
	"peru":                                  "PE",
	"philippines":                           "PH",
	"poland":                                "PL",
	"portugal":                              "PT",
	"puerto rico":                           "PR",
	"qatar":                                 "QA",
	"republic of korea":                     "KR",
	"republic of the congo":                 "CG",
	"reunion":                               "RE",
	"romania":                               "RO",
	"russia":                                "RU",
	"russian federation":                    "RU",
	"rwanda":                                "RW",
	"s.a.":                                  "CO",
	"saint kitts and nevis":                 "KN",
	"saint lucia":                           "LC",
	"saint vincent and the grenadines":      "VC",
	"samoa":                                 "WS",
	"sao tome and principe":                 "ST",
	"saudi arabia":                          "SA",
	"senegal":                               "SN",
	"serbia":                                "RS",
	"seychelles":                            "SC",
	"sierra leone":                          "SL",
	"singapore":                             "SG",
	"slovakia":                              "SK",
	"slovenia":                              "SI",
	"solomon islands":                       "SB",
	"somalia":                               "SO",
	"south africa":                          "ZA",
	"south korea":                           "KR",
	"south sudan":                           "SS",
	"spain":                                 "ES",
	"sri lanka":                             "LK",
	"sudan":                                 "SD",
	"suriname":                              "SR",
	"swaziland":                             "SZ",
	"sweden":                                "SE",
	"switzerland":                           "CH",
	"syria":                                 "SY",
	"syrian arab republic":                  "SY",
	"taiwan":                                "TW",
	"tajikistan":                            "TJ",
	"tanzania":                              "TZ",
	"thailand":                              "TH",
	"togo":                                  "TG",
	"tonga":                                 "TO",
	"trinidad and tobago":                   "TT",
	"tunisia":                               "TN",
	"turkey":                                "TR",
	"turkmenistan":                          "TM",
	"turks and caicos islands":              "TC",
	"tuvalu":                                "TV",
	"uganda":                                "UG",
	"ukraine":                               "UA",
	"united arab emirates":                  "AE",
	"united kingdom":                        "GB",
	"united states":                         "US",
	"uruguay":                               "UY",
	"uzbekistan":                            "UZ",
	"vanuatu":                               "VU",
	"venezuela":                             "VE",
	"vietnam":                               "VN",
	"yemen":                                 "YE",
	"zambia":                                "ZM",
	"zimbabwe":                              "ZW",
}

var knownAirlines = map[string]airlineMetadata{
	// 中国大陆主要民航及货运航司
	"CA": {NameZH: "中国国际航空", NameEN: "Air China", AWBPrefix: "999", CountryCode: "CN", ICAOCode: "CCA", CargoOnly: false},
	"MU": {NameZH: "中国东方航空", NameEN: "China Eastern Airlines", AWBPrefix: "112", CountryCode: "CN", ICAOCode: "CES", CargoOnly: false},
	"CZ": {NameZH: "中国南方航空", NameEN: "China Southern Airlines", AWBPrefix: "784", CountryCode: "CN", ICAOCode: "CSN", CargoOnly: false},
	"HU": {NameZH: "海南航空", NameEN: "Hainan Airlines", AWBPrefix: "880", CountryCode: "CN", ICAOCode: "CHH", CargoOnly: false},
	"MF": {NameZH: "厦门航空", NameEN: "XiamenAir", AWBPrefix: "731", CountryCode: "CN", ICAOCode: "CXA", CargoOnly: false},
	"3U": {NameZH: "四川航空", NameEN: "Sichuan Airlines", AWBPrefix: "876", CountryCode: "CN", ICAOCode: "CSC", CargoOnly: false},
	"ZH": {NameZH: "深圳航空", NameEN: "Shenzhen Airlines", AWBPrefix: "479", CountryCode: "CN", ICAOCode: "CSZ", CargoOnly: false},
	"9C": {NameZH: "春秋航空", NameEN: "Spring Airlines", AWBPrefix: "089", CountryCode: "CN", ICAOCode: "CQH", CargoOnly: false},
	"HO": {NameZH: "吉祥航空", NameEN: "Juneyao Airlines", AWBPrefix: "018", CountryCode: "CN", ICAOCode: "DKH", CargoOnly: false},
	"SC": {NameZH: "山东航空", NameEN: "Shandong Airlines", AWBPrefix: "324", CountryCode: "CN", ICAOCode: "CDG", CargoOnly: false},
	"O3": {NameZH: "顺丰航空", NameEN: "SF Airlines", AWBPrefix: "921", CountryCode: "CN", ICAOCode: "CSS", CargoOnly: true},
	"YG": {NameZH: "圆通航空", NameEN: "YTO Cargo Airlines", AWBPrefix: "801", CountryCode: "CN", ICAOCode: "HYT", CargoOnly: true},
	"CF": {NameZH: "中国邮政航空", NameEN: "China Postal Airlines", AWBPrefix: "970", CountryCode: "CN", ICAOCode: "CYZ", CargoOnly: true},
	"Y8": {NameZH: "金鹏航空", NameEN: "Suparna Airlines", AWBPrefix: "871", CountryCode: "CN", ICAOCode: "YZR", CargoOnly: false},
	"I9": {NameZH: "中州航空", NameEN: "Central Airlines", AWBPrefix: "063", CountryCode: "CN", ICAOCode: "HLF", CargoOnly: true},
	"GJ": {NameZH: "浙江长龙航空", NameEN: "Loong Air", AWBPrefix: "891", CountryCode: "CN", ICAOCode: "CDC", CargoOnly: false},
	"JR": {NameZH: "幸福航空", NameEN: "Joy Air", AWBPrefix: "050", CountryCode: "CN", ICAOCode: "JOY", CargoOnly: false},
	"EU": {NameZH: "成都航空", NameEN: "Chengdu Airlines", AWBPrefix: "856", CountryCode: "CN", ICAOCode: "UEA", CargoOnly: false},
	"TV": {NameZH: "西藏航空", NameEN: "Tibet Airlines", AWBPrefix: "088", CountryCode: "CN", ICAOCode: "TBA", CargoOnly: false},
	"G5": {NameZH: "华夏航空", NameEN: "China Express Airlines", AWBPrefix: "987", CountryCode: "CN", ICAOCode: "HXA", CargoOnly: false},
	"GS": {NameZH: "天津航空", NameEN: "Tianjin Airlines", AWBPrefix: "826", CountryCode: "CN", ICAOCode: "GCR", CargoOnly: false},
	"JD": {NameZH: "首都航空", NameEN: "Beijing Capital Airlines", AWBPrefix: "898", CountryCode: "CN", ICAOCode: "CBJ", CargoOnly: false},
	"8L": {NameZH: "祥鹏航空", NameEN: "Lucky Air", AWBPrefix: "859", CountryCode: "CN", ICAOCode: "LKE", CargoOnly: false},
	"UQ": {NameZH: "乌鲁木齐航空", NameEN: "Urumqi Air", AWBPrefix: "886", CountryCode: "CN", ICAOCode: "CUH", CargoOnly: false},
	"FU": {NameZH: "福州航空", NameEN: "Fuzhou Airlines", AWBPrefix: "874", CountryCode: "CN", ICAOCode: "FZA", CargoOnly: false},
	"RY": {NameZH: "江西航空", NameEN: "Jiangxi Air", AWBPrefix: "872", CountryCode: "CN", ICAOCode: "CJX", CargoOnly: false},
	"GZ": {NameZH: "多彩贵州航空", NameEN: "Colorful Guizhou Airlines", AWBPrefix: "092", CountryCode: "CN", ICAOCode: "CGZ", CargoOnly: false},
	"GT": {NameZH: "桂林航空", NameEN: "Air Guilin", AWBPrefix: "899", CountryCode: "CN", ICAOCode: "CGH", CargoOnly: false},
	"KY": {NameZH: "昆明航空", NameEN: "Kunming Airlines", AWBPrefix: "844", CountryCode: "CN", ICAOCode: "KNA", CargoOnly: false},
	"NS": {NameZH: "河北航空", NameEN: "Hebei Airlines", AWBPrefix: "884", CountryCode: "CN", ICAOCode: "HBH", CargoOnly: false},
	"KN": {NameZH: "中国联合航空", NameEN: "China United Airlines", AWBPrefix: "822", CountryCode: "CN", ICAOCode: "CUA", CargoOnly: false},
	"DZ": {NameZH: "东海航空", NameEN: "Donghai Airlines", AWBPrefix: "981", CountryCode: "CN", ICAOCode: "EPA", CargoOnly: false},
	"9H": {NameZH: "长安航空", NameEN: "Air Changan", AWBPrefix: "878", CountryCode: "CN", ICAOCode: "CGN", CargoOnly: false},
	"LT": {NameZH: "龙江航空", NameEN: "Longjiang Airlines", AWBPrefix: "855", CountryCode: "CN", ICAOCode: "SNG", CargoOnly: false},
	"QW": {NameZH: "青岛航空", NameEN: "Qingdao Airlines", AWBPrefix: "912", CountryCode: "CN", ICAOCode: "QDA", CargoOnly: false},
	"A6": {NameZH: "湖南航空", NameEN: "Hunan Airlines", AWBPrefix: "890", CountryCode: "CN", ICAOCode: "OTC", CargoOnly: false},
	"DR": {NameZH: "瑞丽航空", NameEN: "Ruili Airlines", AWBPrefix: "879", CountryCode: "CN", ICAOCode: "RLH", CargoOnly: false},

	// 港澳台地区主流航司
	"CX": {NameZH: "国泰航空", NameEN: "Cathay Pacific", AWBPrefix: "160", CountryCode: "HK", ICAOCode: "CPA", CargoOnly: false},
	"HX": {NameZH: "香港航空", NameEN: "Hong Kong Airlines", AWBPrefix: "851", CountryCode: "HK", ICAOCode: "CRK", CargoOnly: false},
	"UO": {NameZH: "香港快运航空", NameEN: "HK Express", AWBPrefix: "128", CountryCode: "HK", ICAOCode: "HKE", CargoOnly: false},
	"LD": {NameZH: "香港华民航空", NameEN: "Air Hong Kong", AWBPrefix: "288", CountryCode: "HK", ICAOCode: "AHK", CargoOnly: true},
	"HB": {NameZH: "大湾区航空", NameEN: "Greater Bay Airlines", AWBPrefix: "368", CountryCode: "HK", ICAOCode: "HGB", CargoOnly: false},
	"NX": {NameZH: "澳门航空", NameEN: "Air Macau", AWBPrefix: "675", CountryCode: "MO", ICAOCode: "AMU", CargoOnly: false},
	"CI": {NameZH: "中华航空", NameEN: "China Airlines", AWBPrefix: "297", CountryCode: "TW", ICAOCode: "CAL", CargoOnly: false},
	"BR": {NameZH: "长荣航空", NameEN: "EVA Air", AWBPrefix: "695", CountryCode: "TW", ICAOCode: "EVA", CargoOnly: false},
	"JX": {NameZH: "星宇航空", NameEN: "Starlux Airlines", AWBPrefix: "189", CountryCode: "TW", ICAOCode: "SJX", CargoOnly: false},
	"AE": {NameZH: "华信航空", NameEN: "Mandarin Airlines", AWBPrefix: "803", CountryCode: "TW", ICAOCode: "MDA", CargoOnly: false},
	"B7": {NameZH: "立荣航空", NameEN: "UNI Air", AWBPrefix: "525", CountryCode: "TW", ICAOCode: "UIA", CargoOnly: false},

	// 亚太地区主流航司
	"SQ": {NameZH: "新加坡航空", NameEN: "Singapore Airlines", AWBPrefix: "618", CountryCode: "SG", ICAOCode: "SIA", CargoOnly: false},
	"TR": {NameZH: "酷航", NameEN: "Scoot", AWBPrefix: "668", CountryCode: "SG", ICAOCode: "SCO", CargoOnly: false},
	"NH": {NameZH: "全日空航空", NameEN: "All Nippon Airways", AWBPrefix: "205", CountryCode: "JP", ICAOCode: "ANA", CargoOnly: false},
	"JL": {NameZH: "日本航空", NameEN: "Japan Airlines", AWBPrefix: "131", CountryCode: "JP", ICAOCode: "JAL", CargoOnly: false},
	"KZ": {NameZH: "日本货物航空", NameEN: "Nippon Cargo Airlines", AWBPrefix: "933", CountryCode: "JP", ICAOCode: "NCA", CargoOnly: true},
	"KE": {NameZH: "大韩航空", NameEN: "Korean Air", AWBPrefix: "180", CountryCode: "KR", ICAOCode: "KAL", CargoOnly: false},
	"OZ": {NameZH: "韩亚航空", NameEN: "Asiana Airlines", AWBPrefix: "988", CountryCode: "KR", ICAOCode: "AAR", CargoOnly: false},
	"7C": {NameZH: "济州航空", NameEN: "Jeju Air", AWBPrefix: "806", CountryCode: "KR", ICAOCode: "JJA", CargoOnly: false},
	"BX": {NameZH: "釜山航空", NameEN: "Air Busan", AWBPrefix: "984", CountryCode: "KR", ICAOCode: "ABL", CargoOnly: false},
	"LJ": {NameZH: "真航空", NameEN: "Jin Air", AWBPrefix: "718", CountryCode: "KR", ICAOCode: "JNA", CargoOnly: false},
	"MH": {NameZH: "马来西亚航空", NameEN: "Malaysia Airlines", AWBPrefix: "232", CountryCode: "MY", ICAOCode: "MAS", CargoOnly: false},
	"AK": {NameZH: "亚洲航空", NameEN: "AirAsia", AWBPrefix: "807", CountryCode: "MY", ICAOCode: "AXM", CargoOnly: false},
	"D7": {NameZH: "全亚洲航空", NameEN: "AirAsia X", AWBPrefix: "843", CountryCode: "MY", ICAOCode: "XAX", CargoOnly: false},
	"TG": {NameZH: "泰国国际航空", NameEN: "Thai Airways", AWBPrefix: "217", CountryCode: "TH", ICAOCode: "THA", CargoOnly: false},
	"VN": {NameZH: "越南航空", NameEN: "Vietnam Airlines", AWBPrefix: "738", CountryCode: "VN", ICAOCode: "HVN", CargoOnly: false},
	"VJ": {NameZH: "越捷航空", NameEN: "VietJet Air", AWBPrefix: "978", CountryCode: "VN", ICAOCode: "VJC", CargoOnly: false},
	"GA": {NameZH: "印度尼西亚鹰航", NameEN: "Garuda Indonesia", AWBPrefix: "126", CountryCode: "ID", ICAOCode: "GIA", CargoOnly: false},
	"PR": {NameZH: "菲律宾航空", NameEN: "Philippine Airlines", AWBPrefix: "079", CountryCode: "PH", ICAOCode: "PAL", CargoOnly: false},
	"5J": {NameZH: "宿务太平洋航空", NameEN: "Cebu Pacific", AWBPrefix: "203", CountryCode: "PH", ICAOCode: "CEB", CargoOnly: false},
	"AI": {NameZH: "印度航空", NameEN: "Air India", AWBPrefix: "098", CountryCode: "IN", ICAOCode: "AIC", CargoOnly: false},
	"6E": {NameZH: "靛蓝航空", NameEN: "IndiGo", AWBPrefix: "312", CountryCode: "IN", ICAOCode: "IGO", CargoOnly: false},
	"UL": {NameZH: "斯里兰卡航空", NameEN: "SriLankan Airlines", AWBPrefix: "603", CountryCode: "LK", ICAOCode: "ALK", CargoOnly: false},
	"RA": {NameZH: "尼泊尔航空", NameEN: "Nepal Airlines", AWBPrefix: "285", CountryCode: "NP", ICAOCode: "RNA", CargoOnly: false},

	// 中东地区主流航司
	"EK": {NameZH: "阿联酋航空", NameEN: "Emirates", AWBPrefix: "176", CountryCode: "AE", ICAOCode: "UAE", CargoOnly: false},
	"QR": {NameZH: "卡塔尔航空", NameEN: "Qatar Airways", AWBPrefix: "157", CountryCode: "QA", ICAOCode: "QTR", CargoOnly: false},
	"EY": {NameZH: "阿提哈德航空", NameEN: "Etihad Airways", AWBPrefix: "607", CountryCode: "AE", ICAOCode: "ETD", CargoOnly: false},
	"TK": {NameZH: "土耳其航空", NameEN: "Turkish Airlines", AWBPrefix: "235", CountryCode: "TR", ICAOCode: "THY", CargoOnly: false},
	"SV": {NameZH: "沙特阿拉伯航空", NameEN: "Saudia", AWBPrefix: "065", CountryCode: "SA", ICAOCode: "SVA", CargoOnly: false},
	"WY": {NameZH: "阿曼航空", NameEN: "Oman Air", AWBPrefix: "910", CountryCode: "OM", ICAOCode: "OMA", CargoOnly: false},
	"GF": {NameZH: "海湾航空", NameEN: "Gulf Air", AWBPrefix: "072", CountryCode: "BH", ICAOCode: "GFA", CargoOnly: false},
	"RJ": {NameZH: "约旦皇家航空", NameEN: "Royal Jordanian", AWBPrefix: "512", CountryCode: "JO", ICAOCode: "RJA", CargoOnly: false},
	"ME": {NameZH: "中东航空", NameEN: "Middle East Airlines", AWBPrefix: "076", CountryCode: "LB", ICAOCode: "MEA", CargoOnly: false},
	"LY": {NameZH: "以色列航空", NameEN: "EL AL Israel Airlines", AWBPrefix: "114", CountryCode: "IL", ICAOCode: "ELY", CargoOnly: false},
	"KU": {NameZH: "科威特航空", NameEN: "Kuwait Airways", AWBPrefix: "229", CountryCode: "KW", ICAOCode: "KAC", CargoOnly: false},
	"FZ": {NameZH: "迪拜航空", NameEN: "flydubai", AWBPrefix: "141", CountryCode: "AE", ICAOCode: "FDB", CargoOnly: false},

	// 欧洲地区主流航司
	"LH": {NameZH: "德国汉莎航空", NameEN: "Lufthansa", AWBPrefix: "020", CountryCode: "DE", ICAOCode: "DLH", CargoOnly: false},
	"AF": {NameZH: "法国航空", NameEN: "Air France", AWBPrefix: "057", CountryCode: "FR", ICAOCode: "AFR", CargoOnly: false},
	"KL": {NameZH: "荷兰皇家航空", NameEN: "KLM", AWBPrefix: "074", CountryCode: "NL", ICAOCode: "KLM", CargoOnly: false},
	"BA": {NameZH: "英国航空", NameEN: "British Airways", AWBPrefix: "125", CountryCode: "GB", ICAOCode: "BAW", CargoOnly: false},
	"VS": {NameZH: "维珍大西洋航空", NameEN: "Virgin Atlantic", AWBPrefix: "932", CountryCode: "GB", ICAOCode: "VIR", CargoOnly: false},
	"AY": {NameZH: "芬兰航空", NameEN: "Finnair", AWBPrefix: "105", CountryCode: "FI", ICAOCode: "FIN", CargoOnly: false},
	"SK": {NameZH: "北欧航空", NameEN: "Scandinavian Airlines", AWBPrefix: "117", CountryCode: "SE", ICAOCode: "SAS", CargoOnly: false},
	"LX": {NameZH: "瑞士国际航空", NameEN: "Swiss International Air Lines", AWBPrefix: "724", CountryCode: "CH", ICAOCode: "SWR", CargoOnly: false},
	"OS": {NameZH: "奥地利航空", NameEN: "Austrian Airlines", AWBPrefix: "257", CountryCode: "AT", ICAOCode: "AUA", CargoOnly: false},
	"SU": {NameZH: "俄罗斯航空", NameEN: "Aeroflot", AWBPrefix: "555", CountryCode: "RU", ICAOCode: "AFL", CargoOnly: false},
	"IB": {NameZH: "西班牙国家航空", NameEN: "Iberia", AWBPrefix: "075", CountryCode: "ES", ICAOCode: "IBE", CargoOnly: false},
	"AZ": {NameZH: "意大利航空", NameEN: "ITA Airways", AWBPrefix: "055", CountryCode: "IT", ICAOCode: "ITY", CargoOnly: false},
	"TP": {NameZH: "葡萄牙航空", NameEN: "TAP Air Portugal", AWBPrefix: "047", CountryCode: "PT", ICAOCode: "TAP", CargoOnly: false},
	"SN": {NameZH: "布鲁塞尔航空", NameEN: "Brussels Airlines", AWBPrefix: "082", CountryCode: "BE", ICAOCode: "BEL", CargoOnly: false},
	"LO": {NameZH: "波兰航空", NameEN: "LOT Polish Airlines", AWBPrefix: "080", CountryCode: "PL", ICAOCode: "LOT", CargoOnly: false},
	"OK": {NameZH: "捷克航空", NameEN: "Czech Airlines", AWBPrefix: "064", CountryCode: "CZ", ICAOCode: "CSA", CargoOnly: false},
	"RO": {NameZH: "罗马尼亚航空", NameEN: "TAROM", AWBPrefix: "281", CountryCode: "RO", ICAOCode: "ROT", CargoOnly: false},
	"A3": {NameZH: "爱琴海航空", NameEN: "Aegean Airlines", AWBPrefix: "390", CountryCode: "GR", ICAOCode: "AEE", CargoOnly: false},
	"EI": {NameZH: "爱尔兰航空", NameEN: "Aer Lingus", AWBPrefix: "053", CountryCode: "IE", ICAOCode: "EIN", CargoOnly: false},

	// 美洲地区主流航司
	"AA": {NameZH: "美国航空", NameEN: "American Airlines", AWBPrefix: "001", CountryCode: "US", ICAOCode: "AAL", CargoOnly: false},
	"UA": {NameZH: "联合航空", NameEN: "United Airlines", AWBPrefix: "016", CountryCode: "US", ICAOCode: "UAL", CargoOnly: false},
	"DL": {NameZH: "达美航空", NameEN: "Delta Air Lines", AWBPrefix: "006", CountryCode: "US", ICAOCode: "DAL", CargoOnly: false},
	"WN": {NameZH: "西南航空", NameEN: "Southwest Airlines", AWBPrefix: "526", CountryCode: "US", ICAOCode: "SWA", CargoOnly: false},
	"B6": {NameZH: "捷蓝航空", NameEN: "JetBlue Airways", AWBPrefix: "279", CountryCode: "US", ICAOCode: "JBU", CargoOnly: false},
	"AS": {NameZH: "阿拉斯加航空", NameEN: "Alaska Airlines", AWBPrefix: "027", CountryCode: "US", ICAOCode: "ASA", CargoOnly: false},
	"HA": {NameZH: "夏威夷航空", NameEN: "Hawaiian Airlines", AWBPrefix: "173", CountryCode: "US", ICAOCode: "HAL", CargoOnly: false},
	"AC": {NameZH: "加拿大航空", NameEN: "Air Canada", AWBPrefix: "014", CountryCode: "CA", ICAOCode: "ACA", CargoOnly: false},
	"WS": {NameZH: "西捷航空", NameEN: "WestJet", AWBPrefix: "838", CountryCode: "CA", ICAOCode: "WJA", CargoOnly: false},
	"AM": {NameZH: "墨西哥国际航空", NameEN: "Aeromexico", AWBPrefix: "139", CountryCode: "MX", ICAOCode: "AMX", CargoOnly: false},
	"LA": {NameZH: "智利南美航空", NameEN: "LATAM Airlines", AWBPrefix: "045", CountryCode: "CL", ICAOCode: "LAN", CargoOnly: false},
	"AV": {NameZH: "哥伦比亚航空", NameEN: "Avianca", AWBPrefix: "134", CountryCode: "CO", ICAOCode: "AVA", CargoOnly: false},
	"CM": {NameZH: "巴拿马航空", NameEN: "Copa Airlines", AWBPrefix: "230", CountryCode: "PA", ICAOCode: "CMP", CargoOnly: false},
	"AR": {NameZH: "阿根廷航空", NameEN: "Aerolineas Argentinas", AWBPrefix: "044", CountryCode: "AR", ICAOCode: "ARG", CargoOnly: false},

	// 全球主要全货运航空 (Dedicated Cargo Airlines)
	"FX": {NameZH: "联邦快递", NameEN: "Federal Express", AWBPrefix: "023", CountryCode: "US", ICAOCode: "FDX", CargoOnly: true},
	"5X": {NameZH: "联合包裹", NameEN: "United Parcel Service", AWBPrefix: "406", CountryCode: "US", ICAOCode: "UPS", CargoOnly: true},
	"5Y": {NameZH: "阿特拉斯航空", NameEN: "Atlas Air", AWBPrefix: "369", CountryCode: "US", ICAOCode: "GTI", CargoOnly: true},
	"PO": {NameZH: "极地货运航空", NameEN: "Polar Air Cargo", AWBPrefix: "403", CountryCode: "US", ICAOCode: "PAC", CargoOnly: true},
	"K4": {NameZH: "卡利塔航空", NameEN: "Kalitta Air", AWBPrefix: "272", CountryCode: "US", ICAOCode: "CKS", CargoOnly: true},
	"CV": {NameZH: "卢森堡国际货运航空", NameEN: "Cargolux Airlines International", AWBPrefix: "172", CountryCode: "LU", ICAOCode: "CLX", CargoOnly: true},
	"7L": {NameZH: "丝绸之路西部航空", NameEN: "Silk Way West Airlines", AWBPrefix: "463", CountryCode: "AZ", ICAOCode: "AZG", CargoOnly: true},
	"RU": {NameZH: "空桥货运航空", NameEN: "AirBridgeCargo Airlines", AWBPrefix: "580", CountryCode: "RU", ICAOCode: "ABW", CargoOnly: true},
	"N8": {NameZH: "国家航空", NameEN: "National Airlines", AWBPrefix: "820", CountryCode: "US", ICAOCode: "NCR", CargoOnly: true},
	"KJ": {NameZH: "仁川航空", NameEN: "Air Incheon", AWBPrefix: "996", CountryCode: "KR", ICAOCode: "AIH", CargoOnly: true},

	// 大洋洲及非洲地区
	"QF": {NameZH: "澳洲航空", NameEN: "Qantas", AWBPrefix: "081", CountryCode: "AU", ICAOCode: "QFA", CargoOnly: false},
	"VA": {NameZH: "维珍澳洲航空", NameEN: "Virgin Australia", AWBPrefix: "795", CountryCode: "AU", ICAOCode: "VAU", CargoOnly: false},
	"NZ": {NameZH: "新西兰航空", NameEN: "Air New Zealand", AWBPrefix: "086", CountryCode: "NZ", ICAOCode: "ANZ", CargoOnly: false},
	"FJ": {NameZH: "斐济航空", NameEN: "Fiji Airways", AWBPrefix: "260", CountryCode: "FJ", ICAOCode: "FJI", CargoOnly: false},
	"ET": {NameZH: "埃塞俄比亚航空", NameEN: "Ethiopian Airlines", AWBPrefix: "071", CountryCode: "ET", ICAOCode: "ETH", CargoOnly: false},
	"MS": {NameZH: "埃及航空", NameEN: "EgyptAir", AWBPrefix: "077", CountryCode: "EG", ICAOCode: "MSR", CargoOnly: false},
	"SA": {NameZH: "南非航空", NameEN: "South African Airways", AWBPrefix: "083", CountryCode: "ZA", ICAOCode: "SAA", CargoOnly: false},
	"KQ": {NameZH: "肯尼亚航空", NameEN: "Kenya Airways", AWBPrefix: "706", CountryCode: "KE", ICAOCode: "KQA", CargoOnly: false},
	"AT": {NameZH: "摩洛哥皇家航空", NameEN: "Royal Air Maroc", AWBPrefix: "147", CountryCode: "MA", ICAOCode: "RAM", CargoOnly: false},
	"AH": {NameZH: "阿尔及利亚航空", NameEN: "Air Algerie", AWBPrefix: "124", CountryCode: "DZ", ICAOCode: "DAH", CargoOnly: false},
}

func mapOpenFlightsCountry(countryName string) string {
	key := strings.ToLower(strings.TrimSpace(countryName))
	if code, ok := openFlightsCountryToISO2[key]; ok {
		return code
	}
	return ""
}

func enrichAirlineInfo(iataCode string) (meta airlineMetadata, found bool) {
	iata := strings.ToUpper(strings.TrimSpace(iataCode))
	meta, found = knownAirlines[iata]
	return
}
