export default [
  {
    path: '/user',
    layout: false,
    routes: [
      {
        name: '登录',
        path: '/user/login',
        component: './user/login',
      },
      {
        name: '企业微信登录',
        path: '/user/login/wecom/callback',
        component: './user/login/wecom-callback',
      },
      {
        name: '钉钉登录',
        path: '/user/login/dingtalk/callback',
        component: './user/login/dingtalk-callback',
      },
    ],
  },
  {
    path: '/welcome',
    name: '工作台',
    icon: 'dashboard',
    access: 'canAccessPlatform',
    component: './Welcome',
  },
  {
    path: '/partners',
    redirect: '/partners/customers',
  },
  {
    path: '/partners/customers',
    name: '客户',
    icon: 'contacts',
    access: 'canReadPartners',
    hideInMenu: true,
    component: './partners',
  },
  {
    path: '/partners/customers/create',
    name: '新建客户',
    access: 'canCreatePartners',
    hideInMenu: true,
    component: './partners/partner-detail',
  },
  {
    path: '/partners/customers/:id',
    name: '客户详情',
    access: 'canReadPartners',
    hideInMenu: true,
    component: './partners/partner-detail',
  },
  {
    path: '/partners/suppliers',
    name: '供应商',
    icon: 'shop',
    access: 'canReadPartners',
    hideInMenu: true,
    component: './partners',
  },
  {
    path: '/partners/suppliers/create',
    name: '新建供应商',
    access: 'canCreatePartners',
    hideInMenu: true,
    component: './partners/partner-detail',
  },
  {
    path: '/partners/suppliers/:id',
    name: '供应商详情',
    access: 'canReadPartners',
    hideInMenu: true,
    component: './partners/partner-detail',
  },
  {
    path: '/partners/foreign-agents',
    name: '国外代理',
    icon: 'global',
    access: 'canReadPartners',
    hideInMenu: true,
    component: './partners',
  },
  {
    path: '/partners/foreign-agents/create',
    name: '新建国外代理',
    access: 'canCreatePartners',
    hideInMenu: true,
    component: './partners/partner-detail',
  },
  {
    path: '/partners/foreign-agents/:id',
    name: '国外代理详情',
    access: 'canReadPartners',
    hideInMenu: true,
    component: './partners/partner-detail',
  },
  {
    path: '/orders',
    redirect: '/orders/sea-export',
  },
  {
    path: '/orders',
    name: '订单管理',
    icon: 'orderedList',
    access: 'canReadAnyOrders',
    routes: [
      {
        path: '/orders/sea-export',
        name: '海运出口',
        access: 'canReadSEOrders',
        component: './orders/list',
      },
      {
        path: '/orders/sea-import',
        name: '海运进口',
        access: 'canReadSIOrders',
        component: './orders/list',
      },
      {
        path: '/orders/air-export',
        name: '空运出口',
        access: 'canReadAEOrders',
        component: './orders/list',
      },
      {
        path: '/orders/air-import',
        name: '空运进口',
        access: 'canReadAIOrders',
        component: './orders/list',
      },
      {
        path: '/orders/:kind/new',
        name: '新建订单',
        hideInMenu: true,
        component: './orders/new',
      },
    ],
  },
  {
    path: '/settings',
    name: '参数设置',
    icon: 'setting',
    access: 'canReadParameterSettings',
    hideInMenu: true,
    component: './settings',
  },
  {
    path: '/master-data',
    name: '主数据',
    icon: 'database',
    access: 'canReadMasterData',
    hideInMenu: true,
    component: './master-data',
  },
  {
    path: '/finance/fee-settings',
    name: '费用设置',
    icon: 'accountBook',
    access: 'canReadFeeSettings',
    hideInMenu: true,
    component: './finance/fee-settings',
  },
  {
    path: '/finance/exchange-rates',
    name: '汇率设置',
    icon: 'moneyCollect',
    access: 'canReadExchangeRates',
    hideInMenu: true,
    component: './finance/exchange-rates',
  },
  {
    path: '/admin',
    name: '系统管理',
    icon: 'setting',
    access: 'canAccessPlatform',
    hideInMenu: true,
    component: './admin',
  },
  {
    path: '/',
    redirect: '/welcome',
  },
  {
    component: './NotFound',
    layout: false,
    path: './*',
  },
];
